/* ==========================================================================
   gherkin-ai-cli - Flutter project (Dart kernel, http client, widget tests, feature binder)
   Used as a frontend (./frontend) or as the main Dart project (root).
   ========================================================================== */

import { DomainModel, stepRegex } from '../../kernel/domain-model';
import { FeFile } from './client';

// Dart raw string r'...' keeps regex backslashes; escape the quote itself by splitting.
const dartRaw = (s: string) => (s.includes("'") ? `r"${s}"` : `r'${s}'`);
const dartStr = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$')}'`;

export function renderFlutterProject(m: DomainModel, opts: { root?: string; packageName: string; featurePathFromPackage: string }): FeFile[] {
  const root = opts.root ? `${opts.root}/` : '';
  const f = (p: string) => `${root}${p}`;
  const pkg = opts.packageName;
  const first = m.commands[0];
  return [
    {
      filename: f('pubspec.yaml'),
      content: `name: ${pkg}
description: ${JSON.stringify(`${m.feature} client (generated by gherkin-ai).`)}
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
`
    },
    { filename: f('analysis_options.yaml'), content: `include: package:flutter_lints/flutter.yaml\n` },
    {
      filename: f(`lib/domain/${m.snake}_aggregate.dart`),
      content: `/// Domain kernel for ${JSON.stringify(m.feature)} (generated by gherkin-ai).
/// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
library;

class DomainValidationException implements Exception {
  DomainValidationException(this.message);
  final String message;

  @override
  String toString() => message;
}

class ${m.pascal}Command {
  const ${m.pascal}Command(this.id, [this.payload = const {}]);
  final String id;
  final Map<String, Object?> payload;
}

class ${m.pascal}DomainEvent {
  const ${m.pascal}DomainEvent({required this.type, required this.aggregateId, required this.version, required this.occurredOn, required this.payload});
  final String type;
  final String aggregateId;
  final int version;
  final DateTime occurredOn;
  final Map<String, Object?> payload;
}

class ${m.pascal}Aggregate {
  ${m.pascal}Aggregate(this.id) {
    if (id.trim().isEmpty) throw DomainValidationException('${m.pascal} id is required');
  }

  static const states = [${m.states.map(dartStr).join(', ')}];
  static const eventTypes = [${m.events.map(dartStr).join(', ')}];

  final String id;
  String state = ${dartStr(m.initialState)};
  int version = 0;
  final List<${m.pascal}DomainEvent> _pendingEvents = [];

  /// Events recorded since the aggregate was loaded (to be saved via the outbox).
  List<${m.pascal}DomainEvent> get pendingEvents => List.unmodifiable(_pendingEvents);
${m.commands.map(c => `
  ${m.pascal}DomainEvent ${c.method}(${m.pascal}Command command) {
    _assertValid(command);
    return _record(${dartStr(c.event)}, command.payload);
  }`).join('\n')}

  void _assertValid(${m.pascal}Command command) {
    if (command.id.trim().isEmpty) throw DomainValidationException('Command id is required');
    if (command.id != id) throw DomainValidationException('Command targets \${command.id}, not \$id');
  }

  ${m.pascal}DomainEvent _record(String type, Map<String, Object?> payload) {
    version += 1;
    final event = ${m.pascal}DomainEvent(type: type, aggregateId: id, version: version, occurredOn: DateTime.now().toUtc(), payload: payload);
    _pendingEvents.add(event);
    return event;
  }
}
`
    },
    {
      filename: f(`lib/api/${m.snake}_client.dart`),
      content: `/// API client for ${JSON.stringify(m.feature)} (generated by gherkin-ai).
/// Contract: POST /api/v1/${m.kebab}/{id}/{command} -> 201 { type, aggregateId, version }
library;

import 'dart:convert';
import 'dart:math';

import 'package:http/http.dart' as http;

const commands = [${m.commands.map(c => dartStr(c.snake)).join(', ')}];

class CommandResult {
  const CommandResult(this.type, this.aggregateId, this.version);
  final String type;
  final String aggregateId;
  final int version;

  factory CommandResult.fromJson(Map<String, dynamic> json) =>
      CommandResult(json['type'] as String, json['aggregateId'] as String, (json['version'] as num).toInt());
}

class ApiException implements Exception {
  ApiException(this.status, this.message);
  final int status;
  final String message;

  @override
  String toString() => message;
}

String _hex(int bytes) => List.generate(bytes, (_) => Random.secure().nextInt(256).toRadixString(16).padLeft(2, '0')).join();

/// A new sampled W3C traceparent (version 00) for a request that starts a trace.
String newTraceparent() => '00-\${_hex(16)}-\${_hex(8)}-01';

class ${m.pascal}Client {
  /// [traceparent] supplies the W3C trace context sent with each request, so the backend's spans join
  /// the caller's trace. Default: a new sampled root context per request; return null to send none.
  ${m.pascal}Client({http.Client? httpClient, this.baseUrl = '', this.tenantId, String? Function()? traceparent})
      : _http = httpClient ?? http.Client(),
        _traceparent = traceparent ?? newTraceparent;

  final http.Client _http;
  final String baseUrl;
  final String? tenantId;
  final String? Function() _traceparent;

  static String _newKey() => List.generate(16, (_) => Random.secure().nextInt(16).toRadixString(16)).join();

  Future<CommandResult> execute(String id, String command, {Map<String, Object?> payload = const {}, String? idempotencyKey}) async {
    final uri = Uri.parse('\${baseUrl.replaceAll(RegExp(r'/$'), '')}/api/v1/${m.kebab}/\${Uri.encodeComponent(id)}/\$command');
    final traceparent = _traceparent();
    final res = await _http.post(
      uri,
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        if (tenantId != null) 'X-Tenant-Id': tenantId!,
        'X-Idempotency-Key': idempotencyKey ?? _newKey(),
        if (traceparent != null) 'traceparent': traceparent,
      },
      body: jsonEncode(payload),
    );
    final body = res.body.isEmpty ? <String, dynamic>{} : jsonDecode(res.body) as Map<String, dynamic>;
    if (res.statusCode >= 400) throw ApiException(res.statusCode, (body['detail'] as String?) ?? 'Request failed with status \${res.statusCode}');
    return CommandResult.fromJson(body);
  }
}
`
    },
    {
      filename: f(`lib/${m.snake}_panel.dart`),
      content: `import 'package:flutter/material.dart';

import 'api/${m.snake}_client.dart';

class ${m.pascal}Panel extends StatefulWidget {
  const ${m.pascal}Panel({super.key, required this.client});
  final ${m.pascal}Client client;

  @override
  State<${m.pascal}Panel> createState() => _${m.pascal}PanelState();
}

class _${m.pascal}PanelState extends State<${m.pascal}Panel> {
  final _id = TextEditingController();
  final _events = <CommandResult>[];
  String? _error;
  bool _loading = false;

  Future<void> _run(String command) async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      final event = await widget.client.execute(_id.text, command);
      setState(() => _events.add(event));
    } catch (e) {
      setState(() => _error = e.toString());
    } finally {
      setState(() => _loading = false);
    }
  }

  @override
  void dispose() {
    _id.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text(${dartStr(m.feature)})),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          TextField(key: const Key('aggregate-id'), controller: _id, decoration: const InputDecoration(labelText: 'Aggregate id'), onChanged: (_) => setState(() {})),
          for (final command in commands)
            ElevatedButton(key: Key(command), onPressed: _id.text.isEmpty || _loading ? null : () => _run(command), child: Text(command)),
          if (_error != null) Text(_error!, key: const Key('error')),
          for (final e in _events) Text('\${e.type} v\${e.version}'),
        ],
      ),
    );
  }
}
`
    },
    {
      filename: f('lib/main.dart'),
      content: `import 'package:flutter/material.dart';

import 'api/${m.snake}_client.dart';
import '${m.snake}_panel.dart';

void main() {
  runApp(MaterialApp(home: ${m.pascal}Panel(client: ${m.pascal}Client(baseUrl: const String.fromEnvironment('API_URL')))));
}
`
    },
    {
      filename: f(`test/domain/${m.snake}_aggregate_test.dart`),
      content: `import 'package:flutter_test/flutter_test.dart';
import 'package:${pkg}/domain/${m.snake}_aggregate.dart';

void main() {
  test('starts in the initial state with no events', () {
    final aggregate = ${m.pascal}Aggregate('agg-1');
    expect(aggregate.state, ${dartStr(m.initialState)});
    expect(aggregate.version, 0);
    expect(aggregate.pendingEvents, isEmpty);
  });

  test('rejects an aggregate without id', () {
    expect(() => ${m.pascal}Aggregate(''), throwsA(isA<DomainValidationException>()));
  });
${m.commands.map(c => `
  test('${c.method} records ${c.event} and bumps the version', () {
    final aggregate = ${m.pascal}Aggregate('agg-1');
    final event = aggregate.${c.method}(const ${m.pascal}Command('agg-1'));
    expect(event.type, ${dartStr(c.event)});
    expect(event.version, 1);
    expect(aggregate.version, 1);
    expect(aggregate.pendingEvents, hasLength(1));
  });

  test('${c.method} rejects a command without id', () {
    final aggregate = ${m.pascal}Aggregate('agg-1');
    expect(() => aggregate.${c.method}(const ${m.pascal}Command('')), throwsA(isA<DomainValidationException>()));
    expect(aggregate.pendingEvents, isEmpty);
  });`).join('\n')}
}
`
    },
    {
      filename: f(`test/api/${m.snake}_client_test.dart`),
      content: `import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:${pkg}/api/${m.snake}_client.dart';

void main() {
  test('posts the command with tenant and idempotency headers', () async {
    late http.Request sent;
    final client = ${m.pascal}Client(
      baseUrl: 'https://api.test/',
      tenantId: 'acme',
      httpClient: MockClient((req) async {
        sent = req;
        return http.Response(jsonEncode({'type': '${first.event}', 'aggregateId': 'agg-1', 'version': 1}), 201);
      }),
    );

    final result = await client.execute('agg-1', '${first.snake}', payload: {'amount': 100}, idempotencyKey: 'key-1');

    expect(result.type, '${first.event}');
    expect(sent.url.toString(), 'https://api.test/api/v1/${m.kebab}/agg-1/${first.snake}');
    expect(sent.headers['X-Tenant-Id'], 'acme');
    expect(sent.headers['X-Idempotency-Key'], 'key-1');
    expect(jsonDecode(sent.body), {'amount': 100});
  });

  test('sends a W3C traceparent that starts a new trace per request', () async {
    final sent = <String?>[];
    final client = ${m.pascal}Client(httpClient: MockClient((req) async {
      sent.add(req.headers['traceparent']);
      return http.Response(jsonEncode({'type': '${first.event}', 'aggregateId': 'agg-1', 'version': 1}), 201);
    }));

    await client.execute('agg-1', '${first.snake}');
    await client.execute('agg-1', '${first.snake}');

    final pattern = RegExp(r'^00-[0-9a-f]{32}-[0-9a-f]{16}-01$');
    expect(sent.every((tp) => tp != null && pattern.hasMatch(tp)), isTrue, reason: '$sent');
    expect(sent[0], isNot(sent[1]));
  });

  test('propagates the caller trace context or none when disabled', () async {
    const parent = '00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01';
    Future<String?> received(String? Function() traceparent) async {
      String? value = 'unset';
      await ${m.pascal}Client(traceparent: traceparent, httpClient: MockClient((req) async {
        value = req.headers['traceparent'];
        return http.Response(jsonEncode({'type': '${first.event}', 'aggregateId': 'agg-1', 'version': 1}), 201);
      })).execute('agg-1', '${first.snake}');
      return value;
    }

    expect(await received(() => parent), parent);
    expect(await received(() => null), isNull);
  });

  test('throws ApiException with the server detail on failure', () async {
    final client = ${m.pascal}Client(httpClient: MockClient((_) async => http.Response(jsonEncode({'detail': 'Command id is required'}), 422)));
    expect(() => client.execute('agg-1', '${first.snake}'), throwsA(isA<ApiException>().having((e) => e.status, 'status', 422)));
  });
}
`
    },
    {
      filename: f(`test/${m.snake}_panel_test.dart`),
      content: `import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:${pkg}/api/${m.snake}_client.dart';
import 'package:${pkg}/${m.snake}_panel.dart';

void main() {
  testWidgets('executes a command and lists the resulting event', (tester) async {
    final client = ${m.pascal}Client(
      httpClient: MockClient((_) async => http.Response(jsonEncode({'type': '${first.event}', 'aggregateId': 'agg-1', 'version': 1}), 201)),
    );
    await tester.pumpWidget(MaterialApp(home: ${m.pascal}Panel(client: client)));

    await tester.enterText(find.byKey(const Key('aggregate-id')), 'agg-1');
    await tester.pump();
    await tester.tap(find.byKey(const Key('${first.snake}')));
    await tester.pumpAndSettle();

    expect(find.text('${first.event} v1'), findsOneWidget);
  });
}
`
    },
    {
      filename: f(`test/features/${m.snake}_feature_test.dart`),
      content: `// Binds ${opts.featurePathFromPackage} to flutter test (generated by gherkin-ai).
// Each scenario is a test, skipped while it has pending steps. Undefined steps fail the run.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

enum StepStatus { pending, implemented }

/// (keyword, pattern, status): switch a step to implemented once it asserts real behavior.
final stepDefinitions = <(String, RegExp, StepStatus)>[
${m.steps.map(s => `  ('${s.keyword}', RegExp(${dartRaw(stepRegex(s.text))}), StepStatus.pending),`).join('\n')}
];

List<(String, List<(String, String)>)> parseScenarios(String source) {
  final scenarios = <(String, List<(String, String)>)>[];
  var last = 'Given';
  for (final raw in source.split(RegExp(r'\\r?\\n'))) {
    final line = raw.trim();
    final scenario = RegExp(r'^Scenario(?: Outline)?:\\s*(.+)$').firstMatch(line);
    if (scenario != null) {
      scenarios.add((scenario.group(1)!, <(String, String)>[]));
      last = 'Given';
      continue;
    }
    final step = RegExp(r'^(Given|When|Then|And|But)\\s+(.+)$').firstMatch(line);
    if (step != null && scenarios.isNotEmpty) {
      final kw = step.group(1)!;
      if (kw != 'And' && kw != 'But') last = kw;
      scenarios.last.$2.add((last, step.group(2)!));
    }
  }
  return scenarios;
}

(String, RegExp, StepStatus)? definitionFor(String kw, String text) {
  for (final d in stepDefinitions) {
    if (d.$1 == kw && d.$2.hasMatch(text)) return d;
  }
  return null;
}

void main() {
  final scenarios = parseScenarios(File(${dartStr(opts.featurePathFromPackage)}).readAsStringSync());

  test('every step in the feature has a definition', () {
    final undefined = [
      for (final s in scenarios)
        for (final st in s.$2)
          if (definitionFor(st.$1, st.$2) == null) '\${s.$1}: \${st.$1} \${st.$2}'
    ];
    expect(undefined, isEmpty, reason: 'Undefined steps');
  });

  for (final s in scenarios) {
    final pending = s.$2.any((st) => definitionFor(st.$1, st.$2)?.$3 == StepStatus.pending);
    test('Scenario: \${s.$1}', () {
      // Pending: implement the steps, mark them implemented above and assert here.
    }, skip: pending ? 'pending steps' : null);
  }
}
`
    }
  ];
}
