/* ==========================================================================
   gherkin-ai-cli - Go Structs & Domain Interfaces Generator
   ========================================================================== */

import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';
import { SpecificationIR } from '../core/semantic-ir';

export function generateGoContracts(parsed: ParsedFeature, ir: SpecificationIR, config: GherkinAIConfig): string {
  const featurePascal = parsed.featureName.replace(/[^a-zA-Z0-9]/g, '');

  return `/* ==========================================================================
   Generated Domain Contracts & Go Structs
   Feature: ${parsed.featureName}
   Stack: Go + ${config.stack.framework} + ${config.stack.orm}
   Generated by gherkin-ai CLI v1.5.0
   ========================================================================== */

package contracts

import (
	"context"
	"time"
)

// --------------------------------------------------------------------------
// 1. Domain Event Interface
// --------------------------------------------------------------------------
type IDomainEvent interface {
	GetEventID() string
	GetOccurredOn() time.Time
	GetEventType() string
}

${ir.events.map((ev, i) => `type Event${i + 1} struct {
	EventID    uuid.UUID              \`json:"eventId"\`
	OccurredOn time.Time              \`json:"occurredOn"\`
	EventType  string                 \`json:"eventType"\`
	Payload    map[string]interface{} \`json:"payload"\`
}

func (e Event${i + 1}) GetEventID() string       { return e.EventID }
func (e Event${i + 1}) GetOccurredOn() time.Time { return e.OccurredOn }
func (e Event${i + 1}) GetEventType() string    { return "${ev.name.replace(/[^a-zA-Z0-9]/g, '')}" }`).join('\n\n')}

// --------------------------------------------------------------------------
// 2. Command DTO Struct
// --------------------------------------------------------------------------
type ${featurePascal}Command struct {
	RequestID string                 \`json:"request_id" validate:"required,uuid"\`
	Timestamp time.Time              \`json:"timestamp" validate:"required"\`
	Payload   map[string]interface{} \`json:"payload" validate:"required"\`
}

// --------------------------------------------------------------------------
// 3. Domain Repository Port
// --------------------------------------------------------------------------
type I${featurePascal}Repository interface {
	FindByID(ctx context.Context, id string) (interface{}, error)
	Save(ctx context.Context, entity interface{}) error
	Delete(ctx context.Context, id string) error
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
type IEventPublisher interface {
	Publish(ctx context.Context, event IDomainEvent) error
}
`;
}
