/* ==========================================================================
   gherkin-ai-cli - C# 11 Records & Interfaces Generator
   ========================================================================== */

import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';

export function generateCsharpContracts(parsed: ParsedFeature, config: GherkinAIConfig): string {
  const featurePascal = parsed.featureName.replace(/[^a-zA-Z0-9]/g, '');

  return `/* ==========================================================================
   Generated Domain Contracts & C# 11 Records
   Feature: ${parsed.featureName}
   Stack: C# + ${config.stack.framework} + ${config.stack.orm}
   Generated by gherkin-ai CLI v1.5.0
   ========================================================================== */

namespace Domain.Contracts.${featurePascal};

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

// --------------------------------------------------------------------------
// 1. Domain Event Interface & Record Implementations
// --------------------------------------------------------------------------
public interface IDomainEvent
{
    Guid EventId { get; }
    DateTime OccurredOn { get; }
    string EventType { get; }
}

${parsed.domainAnalysis.events.map((ev, i) => `public record Event${i + 1}(
    Guid EventId,
    DateTime OccurredOn,
    Dictionary<string, object> Payload
) : IDomainEvent
{
    public string EventType => "${ev.replace(/[^a-zA-Z0-9]/g, '')}";
}`).join('\n\n')}

// --------------------------------------------------------------------------
// 2. Command DTO Record
// --------------------------------------------------------------------------
public record ${featurePascal}Command(
    Guid RequestId,
    DateTime Timestamp,
    Dictionary<string, object> Payload
);

// --------------------------------------------------------------------------
// 3. Domain Repository Port
// --------------------------------------------------------------------------
public interface I${featurePascal}Repository
{
    Task<object?> FindByIdAsync(string id);
    Task SaveAsync(object entity);
    Task DeleteAsync(string id);
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
public interface IEventPublisher
{
    Task PublishAsync(IDomainEvent domainEvent);
}
`;
}
