/* ==========================================================================
   gherkin-ai-cli - Multi-Language Domain Contracts & OpenAPI Generator
   ========================================================================== */

import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';
import { getArchRule } from '../core/arch-rules';
import { getStackSpec } from '../core/stack-specs';
import { generatePythonContracts } from './contracts-python';
import { generatePhpContracts } from './contracts-php';
import { generateGoContracts } from './contracts-go';
import { generateCsharpContracts } from './contracts-csharp';

export interface GeneratedContractsOutput {
  contractsTs: string;
  adrMd: string;
  openApiJson: string;
  asyncApiJson: string;
  nativeContract?: {
    filename: string;
    content: string;
  };
}

import { SpecificationIR } from '../core/semantic-ir';

export function generateContracts(parsed: ParsedFeature, ir: SpecificationIR, config: GherkinAIConfig): GeneratedContractsOutput {
  const arch = getArchRule(config.architecture);
  const spec = getStackSpec(config.stack);
  const isCqrs = config.architecture === 'cqrs';

  const featurePascal = parsed.featureName.replace(/[^a-zA-Z0-9]/g, '');

  const cqrsSection = isCqrs ? `
// --------------------------------------------------------------------------
// CQRS + Event Sourcing Infrastructure Contracts
// --------------------------------------------------------------------------
export interface IAggregateRoot<T> {
  id: string;
  version: number;
  uncommittedEvents: IDomainEvent[];
  apply(event: IDomainEvent): void;
  clearUncommittedEvents(): void;
}

export interface IEventStore {
  saveEvents(aggregateId: string, events: IDomainEvent[], expectedVersion: number): Promise<void>;
  getEventsForAggregate(aggregateId: string): Promise<IDomainEvent[]>;
}

export interface ISnapshotStore<T> {
  getSnapshot(aggregateId: string): Promise<{ version: number; state: T } | null>;
  saveSnapshot(aggregateId: string, version: number, state: T): Promise<void>;
}
` : '';

  const contractsTs = `/* ==========================================================================
   Generated Domain Contracts & DTO Schemas
   Feature: ${parsed.featureName}
   Architecture: ${arch.name}
   Stack: ${config.stack.language} + ${config.stack.framework} + ${config.stack.orm}
   Generated by gherkin-ai CLI v2.6.1
   ========================================================================== */

import { z } from '${spec.validationPackage.split('@')[0]}';

// --------------------------------------------------------------------------
// 1. Domain Event Interfaces
// --------------------------------------------------------------------------
export interface IDomainEvent {
  eventId: string;
  occurredOn: Date;
  eventType: string;
}

${ir.events.map((ev, i) => `export interface Event${i + 1} extends IDomainEvent {
  eventType: '${ev.name.replace(/[^a-zA-Z0-9]/g, '')}';
  payload: {
${ir.fields.map(f => `    ${f.name}: ${f.type};`).join('\n')}
  };
}`).join('\n\n')}

// --------------------------------------------------------------------------
// 2. Command DTO Schemas (Zod Validation)
// --------------------------------------------------------------------------
export const ${featurePascal}CommandSchema = z.object({
  requestId: z.string().uuid(),
  timestamp: z.string().datetime(),
  payload: z.object({
${ir.fields.map(f => {
  let zType = f.type === 'number' ? 'z.number()' : 'z.string()';
  f.validations.forEach((v: any) => {
    if (v.type === 'email') zType += '.email()';
    if (v.type === 'range' && v.params) zType += `.min(${v.params.min || 0}).max(${v.params.max || 100})`;
  });
  return `    ${f.name}: ${zType}`;
}).join(',\n')}
  })
});

export type ${featurePascal}Command = z.infer<typeof ${featurePascal}CommandSchema>;

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
export interface I${featurePascal}Repository {
  findById(id: string): Promise<unknown | null>;
  save(entity: unknown): Promise<void>;
  delete(id: string): Promise<void>;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
export interface IEventPublisher {
  publish(event: IDomainEvent): Promise<void>;
}
${cqrsSection}`;

  const feDecisions = (config.frontendStack && config.frontendStack.framework !== 'none') ? `
- **Frontend Framework**: ${config.frontendStack.framework}
- **Frontend Language**: ${config.frontendStack.language}
- **Frontend Bundler**: ${config.frontendStack.bundler || 'none'}
- **Frontend Unit Testing**: ${config.frontendStack.unitTesting || 'none'}
- **Frontend E2E Testing**: ${config.frontendStack.e2eTesting || 'none'}` : '';

  const langProhibited: Record<string, string[]> = {
    php: ['laravel/framework', 'symfony/symfony', 'illuminate/*'],
    python: ['django', 'fastapi', 'flask', 'eval()'],
    java: ['org.springframework.*', 'java.sql.Statement without PreparedStatement'],
    csharp: ['Microsoft.AspNetCore.*', 'System.Data.SqlClient unparameterized queries'],
    typescript: ['express', '@nestjs/common', 'prisma', 'typeorm'],
    javascript: ['express', 'pg', 'mysql2']
  };

  const effectiveProhibited = Array.from(new Set([
    ...arch.prohibitedImports,
    ...(langProhibited[config.stack.language?.toLowerCase() || ''] || [])
  ]));

  const adrMd = `# ADR 001: Architecture Decisions for ${parsed.featureName}

## Status
Accepted

## Context
Project requiring structured implementation matching Gherkin specification.

## Decisions
- **Architecture Style**: ${arch.name} (${arch.id})
- **Primary Backend Language**: ${config.stack.language}
- **Backend Framework**: ${config.stack.framework} (${spec.frameworkVersion})
- **ORM / Persistence**: ${config.stack.orm} (${spec.ormPackage})
- **Validation**: ${config.stack.validation} (${spec.validationPackage})
- **Authentication**: ${config.stack.auth} (bcrypt cost factor ${spec.bcryptCostFactor}, JWT TTL ${spec.jwtTtlSeconds}s)
- **Backend Testing Framework**: ${config.stack.testing} (${spec.testPackages.join(', ')})${feDecisions}

## Prohibited Layer Dependencies
Domain core must NOT import:
${effectiveProhibited.map(p => `- \`${p}\``).join('\n')}
`;

  const openApiJson = JSON.stringify({
    openapi: '3.0.3',
    info: {
      title: `${parsed.featureName} API Specification`,
      version: '1.0.0',
      description: `Auto-generated OpenAPI specification for ${parsed.featureName} from Gherkin feature spec.`
    },
    paths: ir.apiEndpoints.reduce((acc, ep) => {
      if (!acc[ep.path]) acc[ep.path] = {};
      
      acc[ep.path][ep.method.toLowerCase()] = {
        summary: `${ep.method} ${ep.path}`,
        operationId: ep.operationId,
        security: ep.authRequired ? [{ bearerAuth: [] }] : [],
        requestBody: ep.method !== 'GET' ? {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  requestId: { type: 'string', format: 'uuid' },
                  timestamp: { type: 'string', format: 'date-time' },
                  payload: { 
                    type: 'object',
                    properties: ep.requestFields.reduce((fAcc, f) => {
                      fAcc[f.name] = { type: f.type === 'number' ? 'number' : 'string' };
                      return fAcc;
                    }, {} as Record<string, any>),
                    required: ep.requestFields.filter(f => f.required).map(f => f.name)
                  }
                },
                required: ['requestId', 'timestamp', 'payload']
              }
            }
          }
        } : undefined,
        responses: ep.httpCodes.reduce((resAcc, code) => {
          resAcc[code.code] = { description: code.description };
          return resAcc;
        }, {} as Record<string, any>)
      };
      
      return acc;
    }, {} as Record<string, any>),
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT'
        }
      }
    }
  }, null, 2);

  const asyncApiJson = JSON.stringify({
    asyncapi: '2.6.0',
    info: {
      title: `${parsed.featureName} AsyncAPI Specification`,
      version: '1.0.0',
      description: `Auto-generated AsyncAPI events for ${parsed.featureName} from Gherkin feature spec.`
    },
    defaultContentType: 'application/json',
    channels: ir.events.reduce((acc, ev) => {
      const eventName = ev.name;
      acc[`${featurePascal.toLowerCase()}/events/${eventName.toLowerCase()}`] = {
        bindings: {
          rabbitmq: {
            is: 'routingKey',
            queue: {
              name: `${featurePascal.toLowerCase()}.${eventName.toLowerCase()}.queue`,
              durable: true,
              exclusive: false,
              autoDelete: false
            },
            bindingVersion: '0.2.0'
          },
          kafka: {
            topic: `${featurePascal.toLowerCase()}.${eventName.toLowerCase()}`,
            partitions: 3,
            replicas: 2,
            bindingVersion: '0.3.0'
          }
        },
        publish: {
          summary: `Publish ${eventName} event`,
          message: {
            name: eventName,
            correlationId: {
              description: 'Correlation ID set in the header',
              location: '$message.header#/correlationId'
            },
            headers: {
              type: 'object',
              properties: {
                correlationId: { type: 'string', format: 'uuid', description: 'Correlation ID for distributed tracing' },
                causationId: { type: 'string', format: 'uuid', description: 'ID of the event/command that caused this event' },
                schemaVersion: { type: 'string', default: '1.0' },
                retryCount: { type: 'integer', default: 0 },
                dlqReason: { type: 'string', description: 'Reason for moving to DLQ (if applicable)' }
              },
              required: ['correlationId', 'schemaVersion']
            },
            payload: {
              type: 'object',
              properties: {
                eventId: { type: 'string', format: 'uuid' },
                occurredOn: { type: 'string', format: 'date-time' },
                eventType: { type: 'string', enum: [eventName] },
                payload: { 
                  type: 'object',
                  properties: ir.fields.reduce((fAcc, f) => {
                    fAcc[f.name] = { type: f.type === 'number' ? 'number' : 'string' };
                    return fAcc;
                  }, {} as Record<string, any>),
                  required: ir.fields.filter(f => f.required).map(f => f.name)
                }
              },
              required: ['eventId', 'occurredOn', 'eventType', 'payload']
            }
          }
        }
      };
      return acc;
    }, {} as Record<string, any>)
  }, null, 2);

  // Generate Native Contract file based on target stack language
  let nativeContract: GeneratedContractsOutput['nativeContract'];

  if (config.stack.language === 'python') {
    nativeContract = {
      filename: `${featurePascal.toLowerCase()}.contract.py`,
      content: generatePythonContracts(parsed, ir, config)
    };
  } else if (config.stack.language === 'php') {
    nativeContract = {
      filename: `${featurePascal.toLowerCase()}.contract.php`,
      content: generatePhpContracts(parsed, ir, config)
    };
  } else if (config.stack.language === 'go') {
    nativeContract = {
      filename: `${featurePascal.toLowerCase()}.contract.go`,
      content: generateGoContracts(parsed, ir, config)
    };
  } else if (config.stack.language === 'csharp') {
    nativeContract = {
      filename: `${featurePascal.toLowerCase()}.contract.cs`,
      content: generateCsharpContracts(parsed, ir, config)
    };
  }

  return { contractsTs, adrMd, openApiJson, asyncApiJson, nativeContract };
}
