/* ==========================================================================
   gherkin-ai-cli - TypeScript Contracts & Schemas Generator
   ========================================================================== */

import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';
import { getArchRule } from '../core/arch-rules';
import { getStackSpec } from '../core/stack-specs';

export function generateContracts(parsed: ParsedFeature, config: GherkinAIConfig): { contractsTs: string; adrMd: string } {
  const arch = getArchRule(config.architecture);
  const spec = getStackSpec(config.stack);

  const featurePascal = parsed.featureName.replace(/[^a-zA-Z0-9]/g, '');

  const contractsTs = `/* ==========================================================================
   Generated Domain Contracts & DTO Schemas
   Feature: ${parsed.featureName}
   Architecture: ${arch.name}
   Stack: ${config.stack.language} + ${config.stack.framework} + ${config.stack.orm}
   Generated by gherkin-ai CLI v1.0.0
   ========================================================================== */

import { z } from '${spec.validationPackage.split('@')[0]}';

// --------------------------------------------------------------------------
// 1. Domain Event Interfaces
// --------------------------------------------------------------------------
export interface IDomainEvent {
  eventId: string;
  occurredOn: Date;
  eventType: string;
}

${parsed.domainAnalysis.events.map((ev, i) => `export interface Event${i + 1} extends IDomainEvent {
  eventType: '${ev.replace(/[^a-zA-Z0-9]/g, '')}';
  payload: Record<string, unknown>;
}`).join('\n\n')}

// --------------------------------------------------------------------------
// 2. Command DTO Schemas (Zod Validation)
// --------------------------------------------------------------------------
export const ${featurePascal}CommandSchema = z.object({
  requestId: z.string().uuid(),
  timestamp: z.string().datetime(),
  payload: z.record(z.unknown())
});

export type ${featurePascal}Command = z.infer<typeof ${featurePascal}CommandSchema>;

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
export interface I${featurePascal}Repository {
  findById(id: string): Promise<unknown | null>;
  save(entity: unknown): Promise<void>;
  delete(id: string): Promise<void>;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
export interface IEventPublisher {
  publish(event: IDomainEvent): Promise<void>;
}
`;

  const adrMd = `# ADR 001: Architecture Decisions for ${parsed.featureName}

## Status
Accepted

## Context
Project requiring structured implementation matching Gherkin specification.

## Decisions
- **Architecture Style**: ${arch.name} (${arch.id})
- **Primary Language**: ${config.stack.language}
- **Framework**: ${config.stack.framework} (${spec.frameworkVersion})
- **ORM / Persistence**: ${config.stack.orm} (${spec.ormPackage})
- **Validation**: ${config.stack.validation} (${spec.validationPackage})
- **Authentication**: ${config.stack.auth} (bcrypt cost factor ${spec.bcryptCostFactor}, JWT TTL ${spec.jwtTtlSeconds}s)
- **Testing Framework**: ${config.stack.testing} (${spec.testPackages.join(', ')})

## Prohibited Layer Dependencies
Domain core must NOT import:
${arch.prohibitedImports.map(p => `- \`${p}\``).join('\n')}
`;

  return { contractsTs, adrMd };
}
