/* ==========================================================================
   gherkin-ai-cli - PHP 8.2 Domain Contracts & DTOs Generator
   ========================================================================== */

import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';

export function generatePhpContracts(parsed: ParsedFeature, config: GherkinAIConfig): string {
  const featurePascal = parsed.featureName.replace(/[^a-zA-Z0-9]/g, '');

  return `<?php

declare(strict_types=1);

/* ==========================================================================
   Generated Domain Contracts & PHP DTOs
   Feature: ${parsed.featureName}
   Stack: PHP 8.2 + ${config.stack.framework} + ${config.stack.orm}
   Generated by gherkin-ai CLI v1.5.0
   ========================================================================== */

namespace App\\Domain\\Contracts\\${featurePascal};

use DateTimeImmutable;

// --------------------------------------------------------------------------
// 1. Base Domain Event Interface
// --------------------------------------------------------------------------
interface IDomainEvent
{
    public function getEventId(): string;
    public function getOccurredOn(): DateTimeImmutable;
    public function getEventType(): string;
}

${parsed.domainAnalysis.events.map((ev, i) => `readonly class Event${i + 1} implements IDomainEvent
{
    public function __construct(
        public string $eventId,
        public DateTimeImmutable $occurredOn,
        public array $payload = []
    ) {}

    public function getEventId(): string { return $this->eventId; }
    public function getOccurredOn(): DateTimeImmutable { return $this->occurredOn; }
    public function getEventType(): string { return '${ev.replace(/[^a-zA-Z0-9]/g, '')}'; }
}`).join('\n\n')}

// --------------------------------------------------------------------------
// 2. Command DTO Class (Readonly PHP 8.2)
// --------------------------------------------------------------------------
readonly class ${featurePascal}Command
{
    public function __construct(
        public string $requestId,
        public DateTimeImmutable $timestamp,
        public array $payload
    ) {}
}

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
interface I${featurePascal}Repository
{
    public function findById(string $id): mixed;
    public function save(mixed $entity): void;
    public function delete(string $id): void;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
interface IEventPublisher
{
    public function publish(IDomainEvent $event): void;
}
`;
}
