/* ==========================================================================
   gherkin-ai-cli - Python Pydantic v2 & Domain Contracts Generator
   ========================================================================== */

import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';

export function generatePythonContracts(parsed: ParsedFeature, config: GherkinAIConfig): string {
  const featurePascal = parsed.featureName.replace(/[^a-zA-Z0-9]/g, '');

  return `# ==========================================================================
# Generated Domain Contracts & Pydantic DTO Schemas
# Feature: ${parsed.featureName}
# Stack: Python + ${config.stack.framework} + ${config.stack.orm}
# Generated by gherkin-ai CLI v1.5.0
# ==========================================================================

from datetime import datetime
from typing import Protocol, Any, Dict, Optional
from pydantic import BaseModel, Field, UUID4

# --------------------------------------------------------------------------
# 1. Base Domain Event & Event Schemas
# --------------------------------------------------------------------------
class IDomainEvent(BaseModel):
    event_id: UUID4
    occurred_on: datetime = Field(default_factory=datetime.utcnow)
    event_type: str

${parsed.domainAnalysis.events.map((ev, i) => `class Event${i + 1}(IDomainEvent):
    event_type: str = "${ev.replace(/[^a-zA-Z0-9]/g, '')}"
    payload: Dict[str, Any]`).join('\n\n')}

# --------------------------------------------------------------------------
# 2. Command DTO Schema (Pydantic v2 Validation)
# --------------------------------------------------------------------------
class ${featurePascal}Command(BaseModel):
    request_id: UUID4
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    payload: Dict[str, Any]

# --------------------------------------------------------------------------
# 3. Domain Repository Port (Outbound Protocol)
# --------------------------------------------------------------------------
class I${featurePascal}Repository(Protocol):
    async def find_by_id(self, entity_id: str) -> Optional[Any]:
        ...

    async def save(self, entity: Any) -> None:
        ...

    async def delete(self, entity_id: str) -> None:
        ...

# --------------------------------------------------------------------------
# 4. Application Event Publisher Port
# --------------------------------------------------------------------------
class IEventPublisher(Protocol):
    async def publish(self, event: IDomainEvent) -> None:
        ...
`;
}
