/* ==========================================================================
   gherkin-ai-cli - Multi-Language Domain Contracts & OpenAPI Generator
   ========================================================================== */

import { CLI_VERSION } from '../version';
import { renderPom } from './kernel/java';
import { renderGoMod } from './kernel/go';
import { renderGradleKts, renderGradleSettings } from './kernel/kotlin';
import { toKebab } from './kernel/domain-model';
import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';
import { getArchRule } from '../core/arch-rules';
import { getStackSpec } from '../core/stack-specs';
import { generatePythonContracts } from './contracts-python';
import { generatePhpContracts } from './contracts-php';
import { generateGoContracts } from './contracts-go';
import { generateCsharpContracts } from './contracts-csharp';
import { generateKotlinContracts } from './contracts-kotlin';

export interface GeneratedContractsOutput {
  contractsTs: string;
  adrMd: string;
  openApiJson: string;
  asyncApiJson: string;
  nativeContract?: {
    filename: string;
    content: string;
  };
  projectRootFile?: {
    filename: string;
    content: string;
  } | {
    filename: string;
    content: string;
  }[];
}

import { SpecificationIR } from '../core/semantic-ir';

/** Dependencies the generated Node sources import (kept in sync with scripts/golden-build.js). */
function nodeDependencies(config: GherkinAIConfig): { scripts: Record<string, string>; dependencies: Record<string, string>; devDependencies: Record<string, string> } {
  if ((config.stack.framework || '').toLowerCase() !== 'nestjs') {
    return { scripts: { start: 'node dist/main', build: 'tsc', test: 'jest' }, dependencies: {}, devDependencies: {} };
  }
  return {
    scripts: {
      start: 'node dist/src/main',
      build: 'tsc -p tsconfig.build.json',
      // Unit tests, then BDD scenarios (pending steps do not fail the run).
      test: 'jest && cucumber-js'
    },
    dependencies: {
      '@nestjs/common': '^10.4.0',
      '@nestjs/core': '^10.4.0',
      '@nestjs/cqrs': '^10.2.0',
      '@nestjs/platform-express': '^10.4.0',
      '@nestjs/schedule': '^4.1.0',
      '@prisma/client': '^5.22.0',
      'reflect-metadata': '^0.2.0',
      rxjs: '^7.8.0',
      zod: '^3.23.0'
    },
    devDependencies: {
      '@cucumber/cucumber': '^10.9.0',
      '@types/express': '^4.17.21',
      '@types/jest': '^29.5.0',
      '@types/node': '^20.0.0',
      '@types/supertest': '^6.0.0',
      jest: '^29.7.0',
      prisma: '^5.22.0',
      supertest: '^7.0.0',
      'ts-jest': '^29.2.0',
      'ts-node': '^10.9.2',
      typescript: '^5.4.0'
    }
  };
}

export function generateContracts(parsed: ParsedFeature, ir: SpecificationIR, config: GherkinAIConfig): GeneratedContractsOutput {
  const arch = getArchRule(config.architecture);
  const spec = getStackSpec(config.stack);
  const isCqrs = config.architecture === 'cqrs';

  const featurePascal = parsed.featureName.replace(/[^a-zA-Z0-9]/g, '');

  const cqrsSection = isCqrs ? `
// --------------------------------------------------------------------------
// CQRS + Event Sourcing Infrastructure Contracts
// --------------------------------------------------------------------------
export interface IAggregateRoot<T> {
  id: string;
  version: number;
  uncommittedEvents: IDomainEvent[];
  apply(event: IDomainEvent): void;
  clearUncommittedEvents(): void;
}

export interface IEventStore {
  saveEvents(aggregateId: string, events: IDomainEvent[], expectedVersion: number): Promise<void>;
  getEventsForAggregate(aggregateId: string): Promise<IDomainEvent[]>;
}

export interface ISnapshotStore<T> {
  getSnapshot(aggregateId: string): Promise<{ version: number; state: T } | null>;
  saveSnapshot(aggregateId: string, version: number, state: T): Promise<void>;
}
` : '';

  const contractsTs = `/* ==========================================================================
   Generated Domain Contracts & DTO Schemas
   Feature: ${parsed.featureName}
   Architecture: ${arch.name}
   Stack: ${config.stack.language} + ${config.stack.framework} + ${config.stack.orm}
   Generated by gherkin-ai CLI v${CLI_VERSION}
   ========================================================================== */

import { z } from 'zod';

// --------------------------------------------------------------------------
// 1. Domain Event Interfaces
// --------------------------------------------------------------------------
export interface IDomainEvent {
  eventId: string;
  occurredOn: Date;
  eventType: string;
}

${ir.events.map((ev, i) => `export interface Event${i + 1} extends IDomainEvent {
  eventType: '${ev.name.replace(/[^a-zA-Z0-9]/g, '')}';
  payload: {
${ir.fields.map(f => `    ${f.name}: ${f.type};`).join('\n')}
  };
}`).join('\n\n')}

// --------------------------------------------------------------------------
// 2. Command DTO Schemas (Zod Validation)
// --------------------------------------------------------------------------
export const ${featurePascal}CommandSchema = z.object({
  requestId: z.string().uuid(),
  timestamp: z.string().datetime(),
  payload: z.object({
${ir.fields.map(f => {
  let zType = f.type === 'number' ? 'z.number()' : 'z.string()';
  f.validations.forEach((v: any) => {
    if (v.type === 'email') zType += '.email()';
    if (v.type === 'range' && v.params) zType += `.min(${v.params.min || 0}).max(${v.params.max || 100})`;
  });
  return `    ${f.name}: ${zType}`;
}).join(',\n')}
  })
});

export type ${featurePascal}Command = z.infer<typeof ${featurePascal}CommandSchema>;

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
export interface I${featurePascal}Repository {
  findById(id: string): Promise<unknown | null>;
  save(entity: unknown): Promise<void>;
  delete(id: string): Promise<void>;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
export interface IEventPublisher {
  publish(event: IDomainEvent): Promise<void>;
}
${cqrsSection}`;

  const feDecisions = (config.frontendStack && config.frontendStack.framework !== 'none') ? `
- **Frontend Framework**: ${config.frontendStack.framework}
- **Frontend Language**: ${config.frontendStack.language}
- **Frontend Bundler**: ${config.frontendStack.bundler || 'none'}
- **Frontend Unit Testing**: ${config.frontendStack.unitTesting || 'none'}
- **Frontend E2E Testing**: ${config.frontendStack.e2eTesting || 'none'}` : '';

  const langProhibited: Record<string, string[]> = {
    php: ['laravel/framework', 'symfony/symfony', 'illuminate/*'],
    python: ['django', 'fastapi', 'flask', 'eval()'],
    java: ['org.springframework.*', 'java.sql.Statement without PreparedStatement'],
    csharp: ['Microsoft.AspNetCore.*', 'System.Data.SqlClient unparameterized queries'],
    typescript: ['express', '@nestjs/common', 'prisma', 'typeorm'],
    javascript: ['express', 'pg', 'mysql2']
  };

  const effectiveProhibited = Array.from(new Set([
    ...arch.prohibitedImports,
    ...(langProhibited[config.stack.language?.toLowerCase() || ''] || [])
  ]));

  const adrMd = `# ADR 001: Architecture Decisions for ${parsed.featureName}

## Status
Accepted

## Context
Project requiring structured implementation matching Gherkin specification.

## Decisions
- **Architecture Style**: ${arch.name} (${arch.id})
- **Primary Backend Language**: ${config.stack.language}
- **Backend Framework**: ${config.stack.framework} (${spec.frameworkVersion})
- **ORM / Persistence**: ${config.stack.orm} (${spec.ormPackage})
- **Validation**: ${config.stack.validation} (${spec.validationPackage})
- **Authentication**: ${config.stack.auth} (bcrypt cost factor ${spec.bcryptCostFactor}, JWT TTL ${spec.jwtTtlSeconds}s)
- **Backend Testing Framework**: ${config.stack.testing} (${spec.testPackages.join(', ')})${feDecisions}

## Prohibited Layer Dependencies
Domain core must NOT import:
${effectiveProhibited.map(p => `- \`${p}\``).join('\n')}
`;

  const openApiJson = JSON.stringify({
    openapi: '3.0.3',
    info: {
      title: `${parsed.featureName} API Specification`,
      version: '1.0.0',
      description: `Auto-generated OpenAPI specification for ${parsed.featureName} from Gherkin feature spec.`
    },
    paths: ir.apiEndpoints.reduce((acc, ep) => {
      if (!acc[ep.path]) acc[ep.path] = {};
      
      acc[ep.path][ep.method.toLowerCase()] = {
        summary: `${ep.method} ${ep.path}`,
        operationId: ep.operationId,
        security: ep.authRequired ? [{ bearerAuth: [] }] : [],
        requestBody: ep.method !== 'GET' ? {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  requestId: { type: 'string', format: 'uuid' },
                  timestamp: { type: 'string', format: 'date-time' },
                  payload: { 
                    type: 'object',
                    properties: ep.requestFields.reduce((fAcc, f) => {
                      fAcc[f.name] = { type: f.type === 'number' ? 'number' : 'string' };
                      return fAcc;
                    }, {} as Record<string, any>),
                    required: ep.requestFields.filter(f => f.required).map(f => f.name)
                  }
                },
                required: ['requestId', 'timestamp', 'payload']
              }
            }
          }
        } : undefined,
        responses: ep.httpCodes.reduce((resAcc, code) => {
          resAcc[code.code] = { description: code.description };
          return resAcc;
        }, {} as Record<string, any>)
      };
      
      return acc;
    }, {} as Record<string, any>),
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT'
        }
      }
    }
  }, null, 2);

  const asyncApiJson = JSON.stringify({
    asyncapi: '2.6.0',
    info: {
      title: `${parsed.featureName} AsyncAPI Specification`,
      version: '1.0.0',
      description: `Auto-generated AsyncAPI events for ${parsed.featureName} from Gherkin feature spec.`
    },
    defaultContentType: 'application/json',
    channels: ir.events.reduce((acc, ev) => {
      const eventName = ev.name;
      acc[`${featurePascal.toLowerCase()}/events/${eventName.toLowerCase()}`] = {
        bindings: {
          rabbitmq: {
            is: 'routingKey',
            queue: {
              name: `${featurePascal.toLowerCase()}.${eventName.toLowerCase()}.queue`,
              durable: true,
              exclusive: false,
              autoDelete: false
            },
            bindingVersion: '0.2.0'
          },
          kafka: {
            topic: `${featurePascal.toLowerCase()}.${eventName.toLowerCase()}`,
            partitions: 3,
            replicas: 2,
            bindingVersion: '0.3.0'
          }
        },
        publish: {
          summary: `Publish ${eventName} event`,
          message: {
            name: eventName,
            correlationId: {
              description: 'Correlation ID set in the header',
              location: '$message.header#/correlationId'
            },
            headers: {
              type: 'object',
              properties: {
                correlationId: { type: 'string', format: 'uuid', description: 'Correlation ID for distributed tracing' },
                causationId: { type: 'string', format: 'uuid', description: 'ID of the event/command that caused this event' },
                schemaVersion: { type: 'string', default: '1.0' },
                retryCount: { type: 'integer', default: 0 },
                dlqReason: { type: 'string', description: 'Reason for moving to DLQ (if applicable)' }
              },
              required: ['correlationId', 'schemaVersion']
            },
            payload: {
              type: 'object',
              properties: {
                eventId: { type: 'string', format: 'uuid' },
                occurredOn: { type: 'string', format: 'date-time' },
                eventType: { type: 'string', enum: [eventName] },
                payload: { 
                  type: 'object',
                  properties: ir.fields.reduce((fAcc, f) => {
                    fAcc[f.name] = { type: f.type === 'number' ? 'number' : 'string' };
                    return fAcc;
                  }, {} as Record<string, any>),
                  required: ir.fields.filter(f => f.required).map(f => f.name)
                }
              },
              required: ['eventId', 'occurredOn', 'eventType', 'payload']
            }
          }
        }
      };
      return acc;
    }, {} as Record<string, any>)
  }, null, 2);

  // Generate Native Contract file based on target stack language
  let nativeContract: GeneratedContractsOutput['nativeContract'];

  if (config.stack.language === 'python') {
    nativeContract = {
      filename: `${featurePascal.toLowerCase()}.contract.py`,
      content: generatePythonContracts(parsed, ir, config)
    };
  } else if (config.stack.language === 'php') {
    nativeContract = {
      // Several declarations in one file (not PSR-4 autoloaded); kept as a reference contract and linted.
      filename: `contracts/${featurePascal.toLowerCase()}.contract.php`,
      content: generatePhpContracts(parsed, ir, config)
    };
  } else if (config.stack.language === 'go') {
    nativeContract = {
      // Inside the module so `go build ./...` type-checks it.
      filename: `internal/contracts/${featurePascal.toLowerCase()}.contract.go`,
      content: generateGoContracts(parsed, ir, config)
    };
  } else if (config.stack.language === 'csharp') {
    nativeContract = {
      filename: `${featurePascal.toLowerCase()}.contract.cs`,
      content: generateCsharpContracts(parsed, ir, config)
    };
  } else if (config.stack.language === 'kotlin') {
    nativeContract = {
      filename: `${featurePascal.toLowerCase()}.contract.kt`,
      content: generateKotlinContracts(parsed, ir, config)
    };
  }

  // Generate dynamic project root file
  let projectRootFile: GeneratedContractsOutput['projectRootFile'];
  
  if (config.stack.language === 'csharp' || config.stack.language === '.net' || config.stack.language === 'dotnet') {
    projectRootFile = [
      {
        filename: `${config.projectName || 'MyProject'}.csproj`,
        content: `<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>${(config.projectName || 'MyEnterpriseApp').replace(/[^a-zA-Z0-9.]/g, '') || 'MyEnterpriseApp'}</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.2" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.1.3" />
    <PackageReference Include="Polly.Core" Version="8.3.1" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.3.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.0.0-beta.12" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.9.0" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="8.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>
  <ItemGroup>
    <!-- The .NET Aspire AppHost is its own project (Aspire SDK); keep it out of this compilation unit. -->
    <Compile Remove="src/Api/AppHost/**" />
    <!-- Tests are their own project (tests/*.Tests) referencing this one. -->
    <Compile Remove="tests/**" />
    <!-- Reqnroll writes feature code-behind next to the .feature files; it belongs to the test project. -->
    <Compile Remove="features/**" />
    <None Remove="tests/**" />
    <Content Remove="tests/**" />
  </ItemGroup>
</Project>`
      },
      {
        filename: `validate.sh`,
        content: `#!/bin/bash
echo "Running .NET Build validation inside Docker..."
docker run --rm -v $(pwd):/app -w /app mcr.microsoft.com/dotnet/sdk:8.0 dotnet build
`
      }
    ];
  } else if (config.stack.language === 'java') {
    projectRootFile = {
      filename: `pom.xml`,
      content: renderPom(toKebab(config.projectName || 'demo'))
    };
  } else if (config.stack.language === 'kotlin') {
    projectRootFile = [
      { filename: `build.gradle.kts`, content: renderGradleKts() },
      { filename: `settings.gradle.kts`, content: renderGradleSettings(toKebab(config.projectName || 'demo')) }
    ];
  } else if (config.stack.language === 'go') {
    projectRootFile = { filename: 'go.mod', content: renderGoMod(toKebab(config.projectName || 'app')) };
  } else if (['typescript', 'javascript', 'node'].includes(config.stack.language || '')) {
    projectRootFile = {
      filename: `package.json`,
      content: JSON.stringify({
        name: config.projectName || 'my-project',
        version: '1.0.0',
        private: true,
        ...nodeDependencies(config)
      }, null, 2)
    };
  }

  return { contractsTs, adrMd, openApiJson, asyncApiJson, nativeContract, projectRootFile };
}
