/* ==========================================================================
   gherkin-ai-cli - Executable Test Seeds & Fixtures Generator
   ========================================================================== */

import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';
import { getStackSpec } from '../core/stack-specs';

export function generateFixtures(parsed: ParsedFeature, config: GherkinAIConfig): { fixturesTs: string; seedSql: string } {
  const spec = getStackSpec(config.stack);

  const fixturesTs = `/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: ${parsed.featureName}
   Generated by gherkin-ai CLI v1.0.0
   ========================================================================== */

import bcrypt from 'bcrypt';

export interface TestUserFixture {
  id: string;
  email: string;
  passwordRaw: string;
  passwordHash: string;
  role: string;
  isActive: boolean;
}

export async function createTestUserFixture(): Promise<TestUserFixture> {
  const saltRounds = ${spec.bcryptCostFactor};
  const passwordRaw = 'Pass123!';
  const passwordHash = await bcrypt.hash(passwordRaw, saltRounds);

  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    email: 'dev@example.com',
    passwordRaw,
    passwordHash,
    role: 'ADMIN',
    isActive: true
  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
${parsed.domainAnalysis.fixtures.map(f => `  ${JSON.stringify(f)}`).join(',\n')}
];
`;

  const seedSql = `-- Generated Seed SQL Fixtures for PostgreSQL / MySQL
-- Feature: ${parsed.featureName}

INSERT INTO users (id, email, password_hash, role, is_active, created_at)
VALUES (
  'f47ac10b-58cc-4372-a567-0e02b2c3d479',
  'dev@example.com',
  '$2b$12$eImiTXuWVxfM37uY4JANjO5E.y5bXm8A8fK0iE8zK4aM4iO2oU7pS', -- 'Pass123!' hashed with bcrypt cost 12
  'ADMIN',
  true,
  NOW()
) ON CONFLICT (email) DO NOTHING;
`;

  return { fixturesTs, seedSql };
}
