/* ==========================================================================
   gherkin-ai-cli - Executable Test Seeds & Fixtures Generator
   ========================================================================== */

import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';
import { getStackSpec } from '../core/stack-specs';

export function generateFixtures(parsed: ParsedFeature, config: GherkinAIConfig): { fixturesTs: string; seedSql: string } {
  const spec = getStackSpec(config.stack);

  const fixtureName = parsed.featureName.replace(/[^a-zA-Z0-9]/g, '') + 'Fixture';
  
  const properties = parsed.domainAnalysis.fields.map(f => {
    let type = f.type === 'number' ? 'number' : 'string';
    return `  ${f.name}: ${type};`;
  }).join('\n');

  const defaults = parsed.domainAnalysis.fields.map(f => {
    let val = f.type === 'number' ? '0' : "'test_value'";
    if (f.name.toLowerCase().includes('email')) val = "'test@example.com'";
    return `    ${f.name}: ${val},`;
  }).join('\n');

  const fixturesTs = `/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: ${parsed.featureName}
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface ${fixtureName} {
  id: string;
${properties}
}

export function create${fixtureName}(): ${fixtureName} {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
${defaults}
  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
${parsed.domainAnalysis.fixtures.map(f => `  ${JSON.stringify(f)}`).join(',\n')}
];
`;

  const columns = ['id', ...parsed.domainAnalysis.fields.map(f => f.name)].join(', ');
  const values = ["'f47ac10b-58cc-4372-a567-0e02b2c3d479'", ...parsed.domainAnalysis.fields.map(f => f.type === 'number' ? '0' : "'test'")].join(', ');
  const tableName = parsed.featureName.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();

  const seedSql = `-- Generated Seed SQL Fixtures for PostgreSQL / MySQL
-- Feature: ${parsed.featureName}

INSERT INTO ${tableName} (${columns})
VALUES (
  ${values}
) ON CONFLICT (id) DO NOTHING;
`;

  return { fixturesTs, seedSql };
}
