/* ==========================================================================
   gherkin-ai-cli - Python FastAPI & pytest-bdd Preset Generator  [stable]

   Installable project (pyproject.toml): domain kernel + pytest, a FastAPI
   API executing the kernel commands (TestClient tests), pytest-bdd bound to
   the feature (pending steps skip), SQLAlchemy patterns (outbox, saga,
   idempotency, multitenancy) and an import smoke test for every module.
   Verified by scripts/golden-build.js (fastapi).
   ========================================================================== */

import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';
import { generatePythonOutboxInfrastructure } from './python/python-outbox-generator';
import { generatePythonSagaInfrastructure } from './python/python-saga-generator';
import { generatePythonIdempotencyInfrastructure } from './python/python-idempotency-generator';
import { generatePythonMultiTenancyInfrastructure } from './python/python-multitenancy-generator';
import { buildDomainModel, toKebab } from './kernel/domain-model';
import { PyFile, pyModulesOf, renderPyImportSmokeTest, renderPyKernel, renderPyKernelTests, renderPytestBdd, withInitFiles } from './kernel/python';
import { PY_INTEGRATION_MARKER, PY_RUNTIME_DEPENDENCIES, renderPyRuntime } from './kernel/runtime/python';
import { PY_DATABASE, PY_EVENT_BUS, pyEventBusTest, pyFeatureFile, renderPyproject, underAppPackage } from './python/python-common';

export function generatePythonFastApiPreset(parsed: ParsedFeature, config?: GherkinAIConfig, featureFile?: string): { filename: string; content: string }[] {
  const m = buildDomainModel(parsed);

  const main = `"""FastAPI application for ${JSON.stringify(m.feature)} (generated by gherkin-ai)."""
from typing import Any, Dict

from fastapi import FastAPI, HTTPException

from app.domain import ${m.pascal}Aggregate, ${m.pascal}Command, DomainValidationError

app = FastAPI(title=${JSON.stringify(m.feature)})

# In-memory store: replace with a repository backed by app.database.
_store: Dict[str, ${m.pascal}Aggregate] = {}

_COMMANDS = {
${m.commands.map(c => `    "${c.snake}": ${m.pascal}Aggregate.${c.snake},`).join('\n')}
}


@app.get("/health")
def health() -> Dict[str, str]:
    return {"status": "ok"}


@app.post("/api/v1/${m.kebab}/{aggregate_id}/{command}", status_code=201)
def execute(aggregate_id: str, command: str, payload: Dict[str, Any] | None = None) -> Dict[str, Any]:
    handler = _COMMANDS.get(command)
    if handler is None:
        raise HTTPException(status_code=404, detail=f"Unknown command {command}")
    aggregate = _store.setdefault(aggregate_id, ${m.pascal}Aggregate(aggregate_id))
    try:
        event = handler(aggregate, ${m.pascal}Command(aggregate_id, payload or {}))
    except DomainValidationError as err:
        raise HTTPException(status_code=422, detail=str(err)) from err
    return {"type": event.type.value, "aggregateId": event.aggregate_id, "version": event.version}
`;

  const firstCmd = m.commands[0];
  const apiTest = `from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def test_health():
    assert client.get("/health").json() == {"status": "ok"}


def test_executes_a_domain_command_and_returns_the_event():
    res = client.post("/api/v1/${m.kebab}/agg-api/${firstCmd.snake}", json={"source": "api-test"})
    assert res.status_code == 201
    assert res.json() == {"type": "${firstCmd.event}", "aggregateId": "agg-api", "version": 1}


def test_unknown_command_returns_404():
    assert client.post("/api/v1/${m.kebab}/agg-api/does_not_exist").status_code == 404
`;

  const runtime = renderPyRuntime(m);
  const appFiles: PyFile[] = withInitFiles([
    { filename: 'app/database.py', content: PY_DATABASE },
    { filename: 'app/infrastructure/event_bus.py', content: PY_EVENT_BUS },
    { filename: 'app/main.py', content: main },
    ...renderPyKernel(m),
    // Runtime kernel: PostgreSQL + RabbitMQ + OpenTelemetry, verified by tests/integration (docs/RUNTIME-KERNEL.md).
    ...runtime.filter(f => f.filename.startsWith('app/')),
    ...underAppPackage([
      ...generatePythonOutboxInfrastructure(),
      ...generatePythonSagaInfrastructure(m.pascal),
      ...generatePythonIdempotencyInfrastructure(),
      ...generatePythonMultiTenancyInfrastructure()
    ])
  ]);

  return [
    ...appFiles,
    ...renderPyKernelTests(m),
    ...runtime.filter(f => f.filename.startsWith('tests/')),
    ...renderPytestBdd(m, pyFeatureFile(m, featureFile)),
    pyEventBusTest(),
    { filename: 'tests/test_api.py', content: apiTest },
    renderPyImportSmokeTest(pyModulesOf(appFiles.map(f => f.filename))),
    {
      filename: 'pyproject.toml',
      content: renderPyproject(
        toKebab(config?.projectName || m.kebab),
        ['fastapi>=0.115', 'uvicorn>=0.30', 'sqlalchemy>=2.0', 'pydantic>=2.7', ...PY_RUNTIME_DEPENDENCIES],
        ['pytest>=8.3', 'pytest-bdd>=7.3', 'httpx>=0.27'],
        [PY_INTEGRATION_MARKER]
      )
    }
  ];
}
