/* ==========================================================================
   gherkin-ai-cli - Python Django + DRF Preset Generator  [stable]

   Django project (config/) + app package: domain kernel + pytest, DRF API
   executing the kernel commands, a Django-native transactional outbox model
   (with migration) fed from aggregate events, pytest-django tests and
   pytest-bdd bound to the feature (pending steps skip).
   Verified by scripts/golden-build.js (django).
   ========================================================================== */

import { ParsedFeature } from '../core/gherkin-parser';
import { GherkinAIConfig } from '../core/config';
import { buildDomainModel, toKebab } from './kernel/domain-model';
import { PyFile, pyModulesOf, renderPyImportSmokeTest, renderPyKernel, renderPyKernelTests, renderPytestBdd, withInitFiles } from './kernel/python';
import { PY_INTEGRATION_MARKER, PY_RUNTIME_DEPENDENCIES, renderPyRuntime } from './kernel/runtime/python';
import { PY_EVENT_BUS, pyEventBusTest, pyFeatureFile, renderPyproject } from './python/python-common';

export function generatePythonDjangoPreset(parsed: ParsedFeature, config?: GherkinAIConfig, featureFile?: string): { filename: string; content: string }[] {
  const m = buildDomainModel(parsed);
  const firstCmd = m.commands[0];

  const settings = `"""Django settings (generated by gherkin-ai). Override with environment variables in production."""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "insecure-dev-key-change-me")
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",")

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "rest_framework",
    "app",
]

MIDDLEWARE = [
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.getenv("DJANGO_DB_PATH", str(BASE_DIR / "db.sqlite3")),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
USE_TZ = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [],
    "UNAUTHENTICATED_USER": None,
}
`;

  const models = `"""Transactional outbox (Django ORM). Domain events are stored in the same transaction as state changes."""
import uuid

from django.db import models


class OutboxMessage(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    aggregate_id = models.CharField(max_length=128, db_index=True)
    event_type = models.CharField(max_length=128)
    version = models.PositiveIntegerField()
    payload = models.JSONField(default=dict)
    occurred_on = models.DateTimeField()
    processed_on = models.DateTimeField(null=True, blank=True, db_index=True)
    retry_count = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ["occurred_on"]
        constraints = [models.UniqueConstraint(fields=["aggregate_id", "version"], name="outbox_unique_aggregate_version")]
`;

  const migration = `from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("aggregate_id", models.CharField(db_index=True, max_length=128)),
                ("event_type", models.CharField(max_length=128)),
                ("version", models.PositiveIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("occurred_on", models.DateTimeField()),
                ("processed_on", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["occurred_on"]},
        ),
        migrations.AddConstraint(
            model_name="outboxmessage",
            constraint=models.UniqueConstraint(fields=("aggregate_id", "version"), name="outbox_unique_aggregate_version"),
        ),
    ]
`;

  const outboxService = `"""Persists an aggregate's pending events into the outbox atomically."""
from django.db import transaction

from app.models import OutboxMessage


def save_pending_events(aggregate) -> int:
    with transaction.atomic():
        for event in aggregate.pending_events:
            OutboxMessage.objects.create(
                aggregate_id=event.aggregate_id,
                event_type=event.type.value,
                version=event.version,
                payload=event.payload,
                occurred_on=event.occurred_on,
            )
    return len(aggregate.pending_events)
`;

  const views = `"""DRF API executing the domain kernel commands (generated by gherkin-ai)."""
from rest_framework.decorators import api_view
from rest_framework.response import Response

from app.domain import ${m.pascal}Aggregate, ${m.pascal}Command, DomainValidationError
from app.outbox import save_pending_events

_COMMANDS = {
${m.commands.map(c => `    "${c.snake}": ${m.pascal}Aggregate.${c.snake},`).join('\n')}
}


@api_view(["GET"])
def health(request):
    return Response({"status": "ok"})


@api_view(["POST"])
def execute(request, aggregate_id: str, command: str):
    handler = _COMMANDS.get(command)
    if handler is None:
        return Response({"detail": f"Unknown command {command}"}, status=404)
    aggregate = ${m.pascal}Aggregate(aggregate_id)
    try:
        event = handler(aggregate, ${m.pascal}Command(aggregate_id, dict(request.data or {})))
    except DomainValidationError as err:
        return Response({"detail": str(err)}, status=422)
    save_pending_events(aggregate)
    return Response({"type": event.type.value, "aggregateId": event.aggregate_id, "version": event.version}, status=201)
`;

  const apiTest = `import pytest

from app.models import OutboxMessage


def test_health(client):
    assert client.get("/health").json() == {"status": "ok"}


@pytest.mark.django_db
def test_executes_a_command_and_stores_the_event_in_the_outbox(client):
    res = client.post("/api/v1/${m.kebab}/agg-api/${firstCmd.snake}", {"source": "api-test"}, content_type="application/json")
    assert res.status_code == 201
    assert res.json() == {"type": "${firstCmd.event}", "aggregateId": "agg-api", "version": 1}
    stored = OutboxMessage.objects.get(aggregate_id="agg-api")
    assert stored.event_type == "${firstCmd.event}"
    assert stored.processed_on is None


def test_unknown_command_returns_404(client):
    assert client.post("/api/v1/${m.kebab}/agg-api/does_not_exist").status_code == 404
`;

  const runtime = renderPyRuntime(m);
  const appFiles: PyFile[] = withInitFiles([
    { filename: 'config/settings.py', content: settings },
    {
      filename: 'config/urls.py',
      content: `from django.urls import path

from app import views

urlpatterns = [
    path("health", views.health),
    path("api/v1/${m.kebab}/<str:aggregate_id>/<str:command>", views.execute),
]
`
    },
    { filename: 'config/wsgi.py', content: `import os\n\nfrom django.core.wsgi import get_wsgi_application\n\nos.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")\napplication = get_wsgi_application()\n` },
    { filename: 'app/apps.py', content: `from django.apps import AppConfig\n\n\nclass AppConfig_(AppConfig):\n    name = "app"\n    default_auto_field = "django.db.models.BigAutoField"\n` },
    { filename: 'app/models.py', content: models },
    { filename: 'app/migrations/0001_initial.py', content: migration },
    { filename: 'app/outbox.py', content: outboxService },
    { filename: 'app/views.py', content: views },
    { filename: 'app/infrastructure/event_bus.py', content: PY_EVENT_BUS },
    ...renderPyKernel(m),
    // Runtime kernel: PostgreSQL + RabbitMQ + OpenTelemetry, verified by tests/integration (docs/RUNTIME-KERNEL.md).
    ...runtime.filter(f => f.filename.startsWith('app/'))
  ]);

  return [
    ...appFiles,
    {
      filename: 'manage.py',
      content: `#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
`
    },
    ...renderPyKernelTests(m),
    ...runtime.filter(f => f.filename.startsWith('tests/')),
    ...renderPytestBdd(m, pyFeatureFile(m, featureFile)),
    pyEventBusTest(),
    { filename: 'tests/test_api.py', content: apiTest },
    renderPyImportSmokeTest(pyModulesOf(appFiles.map(f => f.filename)).filter(mod => mod !== 'config.wsgi')),
    {
      filename: 'pyproject.toml',
      content: renderPyproject(
        toKebab(config?.projectName || m.kebab),
        ['django>=5.0,<6', 'djangorestframework>=3.15', ...PY_RUNTIME_DEPENDENCIES],
        ['pytest>=8.3', 'pytest-django>=4.9', 'pytest-bdd>=7.3'],
        ['DJANGO_SETTINGS_MODULE = "config.settings"', PY_INTEGRATION_MARKER]
      )
    }
  ];
}
