/* ==========================================================================
   gherkin-ai-cli - Prisma Schema Generator from Semantic IR
   ========================================================================== */

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { SpecificationIR } from '../core/semantic-ir';
import { GherkinAIConfig } from '../core/config';

export function generatePrismaSchema(ir: SpecificationIR, config: GherkinAIConfig): string {
  const dbProvider = config.stack.database === 'mysql' ? 'mysql' :
                     config.stack.database === 'mongodb' ? 'mongodb' :
                     config.stack.database === 'sqlite' ? 'sqlite' : 'postgresql';

  let prismaContent = `// Prisma Schema generated by gherkin-ai CLI
// Project: ${config.projectName}
// Architecture: ${config.architecture}

datasource db {
  provider = "${dbProvider}"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

`;

  // Generate Enum models for State Machines
  if (ir.stateMachines && ir.stateMachines.length > 0) {
    for (const sm of ir.stateMachines) {
      const enumName = toPascalCase(sm.entity) + 'Status';
      prismaContent += `enum ${enumName} {\n`;
      for (const state of sm.states) {
        const uppercaseState = state.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
        prismaContent += `  ${uppercaseState}\n`;
      }
      prismaContent += `}\n\n`;
    }
  }

  // Generate Models from Command / Query Entities
  const entityMap: Record<string, { name: string; type: string; isId?: boolean; isUnique?: boolean }[]> = {};

  // Infer User entity if authentication is enabled or referenced in actors
  if (ir.actors && ir.actors.length > 0) {
    entityMap['User'] = [
      { name: 'id', type: 'String', isId: true },
      { name: 'email', type: 'String', isUnique: true },
      { name: 'passwordHash', type: 'String' },
      { name: 'role', type: 'String' },
      { name: 'createdAt', type: 'DateTime' },
      { name: 'updatedAt', type: 'DateTime' }
    ];
  }

  // Infer entities from Commands
  if (ir.commands && ir.commands.length > 0) {
    for (const cmd of ir.commands) {
      const entityName = toPascalCase(cmd.subject || cmd.name.replace(/^(create|update|delete|cancel|place|process)/i, ''));
      if (entityName && entityName.length > 2 && !entityMap[entityName]) {
        const fields: { name: string; type: string; isId?: boolean; isUnique?: boolean }[] = [
          { name: 'id', type: 'String', isId: true }
        ];

        if (cmd.inputFields && cmd.inputFields.length > 0) {
          for (const f of cmd.inputFields) {
            if (f.name !== 'id') {
              const fieldType = f.type === 'number' ? 'Int' :
                                f.type === 'boolean' ? 'Boolean' :
                                f.type === 'date' ? 'DateTime' : 'String';
              fields.push({ name: f.name, type: fieldType });
            }
          }
        }

        // Check if state machine applies to this entity
        const sm = ir.stateMachines?.find(s => s.entity.toLowerCase() === entityName.toLowerCase());
        if (sm) {
          fields.push({ name: 'status', type: toPascalCase(sm.entity) + 'Status' });
        }

        fields.push({ name: 'createdAt', type: 'DateTime' });
        fields.push({ name: 'updatedAt', type: 'DateTime' });

        entityMap[entityName] = fields;
      }
    }
  }

  // Render models
  for (const [modelName, fields] of Object.entries(entityMap)) {
    prismaContent += `model ${modelName} {\n`;
    for (const f of fields) {
      let line = `  ${f.name} ${f.type}`;
      if (f.isId) {
        line += ' @id @default(uuid())';
      } else if (f.name === 'createdAt') {
        line += ' @default(now())';
      } else if (f.name === 'updatedAt') {
        line += ' @updatedAt';
      } else if (f.isUnique) {
        line += ' @unique';
      }
      prismaContent += line + '\n';
    }
    prismaContent += `}\n\n`;
  }

  return prismaContent;
}

export function isPrismaInstalled(targetDir: string = process.cwd()): boolean {
  const pkgPath = path.join(targetDir, 'package.json');
  if (!fs.existsSync(pkgPath)) return false;
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
    return Boolean(deps['prisma'] || deps['@prisma/client']);
  } catch {
    return false;
  }
}

export function formatPrismaSchemaIfInstalled(schemaPath: string, targetDir: string = process.cwd()): boolean {
  if (!isPrismaInstalled(targetDir)) {
    return false;
  }
  try {
    execSync(`npx prisma format --schema="${schemaPath}"`, { cwd: targetDir, stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('') || 'Entity';
}
