/* ==========================================================================
   gherkin-ai-cli - Prisma Schema Generator from Semantic IR
   ========================================================================== */

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { SpecificationIR } from '../core/semantic-ir';
import { GherkinAIConfig } from '../core/config';

export function generatePrismaSchema(ir: SpecificationIR, config: GherkinAIConfig): string {
  const dbProvider = config.stack.database === 'mysql' ? 'mysql' :
                     config.stack.database === 'mongodb' ? 'mongodb' :
                     config.stack.database === 'sqlite' ? 'sqlite' : 'postgresql';

  let prismaContent = `// Prisma Schema generated by gherkin-ai CLI
// Project: ${config.projectName}
// Architecture: ${config.architecture}

datasource db {
  provider = "${dbProvider}"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

`;

  // Generate Enum models for State Machines
  if (ir.stateMachines && ir.stateMachines.length > 0) {
    for (const sm of ir.stateMachines) {
      const enumName = toPascalCase(sm.entity) + 'Status';
      prismaContent += `enum ${enumName} {\n`;
      for (const state of sm.states) {
        const uppercaseState = state.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
        prismaContent += `  ${uppercaseState}\n`;
      }
      prismaContent += `}\n\n`;
    }
  }

  // Generate Models from Command / Query Entities
  const entityMap: Record<string, { name: string; type: string; isId?: boolean; isUnique?: boolean; isOptional?: boolean; relationTarget?: string }[]> = {};

  // Infer User entity if authentication is enabled or referenced in actors
  if (ir.actors && ir.actors.length > 0) {
    entityMap['User'] = [
      { name: 'id', type: 'String', isId: true },
      { name: 'email', type: 'String', isUnique: true },
      { name: 'passwordHash', type: 'String' },
      { name: 'role', type: 'String' },
      { name: 'createdAt', type: 'DateTime' },
      { name: 'updatedAt', type: 'DateTime' }
    ];
  }

  // Infer entities from Commands
  if (ir.commands && ir.commands.length > 0) {
    for (const cmd of ir.commands) {
      const entityName = toPascalCase(cmd.subject || cmd.name.replace(/^(create|update|delete|cancel|place|process)/i, ''));
      if (entityName && entityName.length > 2 && !entityMap[entityName]) {
        const fields: { name: string; type: string; isId?: boolean; isUnique?: boolean; isOptional?: boolean; relationTarget?: string }[] = [
          { name: 'id', type: 'String', isId: true }
        ];

        // Ensure multi-tenancy isolation field
        fields.push({ name: 'tenantId', type: 'String' });

        if (cmd.inputFields && cmd.inputFields.length > 0) {
          for (const f of cmd.inputFields) {
            if (f.name !== 'id' && f.name !== 'tenantId') {
              let fieldType = f.type === 'number' ? 'Int' :
                                f.type === 'boolean' ? 'Boolean' :
                                f.type === 'date' ? 'DateTime' : 'String';
              
              // Infer relations based on "Id" suffix
              let relationTarget = undefined;
              if (f.name.endsWith('Id') && f.name.length > 2) {
                const targetModel = toPascalCase(f.name.slice(0, -2));
                relationTarget = targetModel;
              }

              // Optional support based on constraints (mocked logic from IR)
              const isOptional = f.name.toLowerCase().includes('optional') || f.name.toLowerCase() === 'notes';

              fields.push({ name: f.name, type: fieldType, isOptional, relationTarget });
            }
          }
        }

        // Check if state machine applies to this entity
        const sm = ir.stateMachines?.find(s => s.entity.toLowerCase() === entityName.toLowerCase());
        if (sm) {
          fields.push({ name: 'status', type: toPascalCase(sm.entity) + 'Status' });
        }

        fields.push({ name: 'createdAt', type: 'DateTime' });
        fields.push({ name: 'updatedAt', type: 'DateTime' });

        entityMap[entityName] = fields;
      }
    }
  }

  // Generate models
  for (const [modelName, fields] of Object.entries(entityMap)) {
    prismaContent += `model ${modelName} {\n`;
    
    // Track relations to append them
    const relations: string[] = [];

    for (const f of fields) {
      let line = `  ${f.name} ${f.type}${f.isOptional ? '?' : ''}`;
      
      if (f.isId) {
        line += ' @id @default(uuid())';
      } else if (f.name === 'createdAt') {
        line += ' @default(now())';
      } else if (f.name === 'updatedAt') {
        line += ' @updatedAt';
      } else if (f.isUnique) {
        line += ' @unique';
      }

      if (f.relationTarget) {
        // e.g. userId String -> user User @relation(fields: [userId], references: [id])
        const relationFieldName = f.name.slice(0, -2);
        relations.push(`  ${relationFieldName} ${f.relationTarget}? @relation(fields: [${f.name}], references: [id])`);
      }

      prismaContent += line + '\n';
    }

    if (relations.length > 0) {
      prismaContent += '\\n' + relations.join('\\n') + '\\n';
    }

    // Compound Indexes
    prismaContent += `\n  @@index([tenantId, createdAt])\n`;
    
    if (fields.some(f => f.name === 'status')) {
      prismaContent += `  @@index([tenantId, status])\n`;
    }

    // Snake case mapping
    const snakeCaseName = modelName.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`).replace(/^_/, '');
    prismaContent += `\n  @@map("${snakeCaseName}")\n`;

    prismaContent += `}\n\n`;
  }

  // ENTERPRISE GUARANTEES: Inject Outbox and Idempotency Models natively
  prismaContent += `model OutboxMessage {
  id          String    @id @default(uuid())
  eventType   String
  payload     String    @db.Text
  occurredOn  DateTime  @default(now())
  processedOn DateTime?
  retryCount  Int       @default(0)
  lastError   String?   @db.Text
  
  @@index([processedOn, retryCount, occurredOn])
  @@map("outbox_messages")
}

model ProcessedEvent {
  eventId      String   @id
  status       String   // PROCESSING, COMPLETED, FAILED
  responseBody String?  @db.Text
  processedAt  DateTime @default(now())

  @@index([status, processedAt])
  @@map("processed_events")
}\n\n`;

  return prismaContent;
}

export function isPrismaInstalled(targetDir: string = process.cwd()): boolean {
  const pkgPath = path.join(targetDir, 'package.json');
  if (!fs.existsSync(pkgPath)) return false;
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
    return Boolean(deps['prisma'] || deps['@prisma/client']);
  } catch {
    return false;
  }
}

export function formatPrismaSchemaIfInstalled(schemaPath: string, targetDir: string = process.cwd()): boolean {
  if (!isPrismaInstalled(targetDir)) {
    return false;
  }
  try {
    execSync(`npx prisma format --schema="${schemaPath}"`, { cwd: targetDir, stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('') || 'Entity';
}
