/* ==========================================================================
   gherkin-ai-cli - gRPC (Protobuf) and GraphQL contracts from the domain model

   Both mirror the HTTP contract every generated backend exposes:
     command(id, payload) -> CommandResult { type, aggregateId, version }
   Validated in CI with `buf build && buf lint` and graphql-js buildSchema.
   ========================================================================== */

import { DomainModel } from './domain-model';

export interface ContractFile {
  filename: string;
  content: string;
}

export function renderProto(m: DomainModel): ContractFile[] {
  const pkg = `${m.snake}.v1`;
  return [
    {
      filename: 'contracts/buf.yaml',
      content: `version: v2
modules:
  - path: proto
lint:
  use:
    - STANDARD
breaking:
  use:
    - FILE
`
    },
    {
      filename: `contracts/proto/${m.snake}/v1/${m.snake}.proto`,
      content: `// gRPC contract for "${m.feature}" (generated by gherkin-ai).
// Mirrors POST /api/v1/${m.kebab}/{id}/{command} of the generated HTTP API.
syntax = "proto3";

package ${pkg};

import "google/protobuf/struct.proto";

service ${m.pascal}Service {
${m.commands.map(c => `  rpc ${c.name}(${c.name}Request) returns (${c.name}Response);`).join('\n')}
}
${m.commands.map(c => `
message ${c.name}Request {
  // Aggregate identifier the command targets.
  string id = 1;
  google.protobuf.Struct payload = 2;
  // Optional idempotency key (same semantics as X-Idempotency-Key).
  string idempotency_key = 3;
}

message ${c.name}Response {
  CommandResult result = 1;
}`).join('\n')}

message CommandResult {
  EventType type = 1;
  string aggregate_id = 2;
  int64 version = 3;
}

enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0;
${m.events.map((e, i) => `  EVENT_TYPE_${e.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()} = ${i + 1};`).join('\n')}
}
`
    }
  ];
}

export function renderGraphql(m: DomainModel): ContractFile {
  return {
    filename: `contracts/${m.snake}.graphql`,
    content: `# GraphQL contract for "${m.feature}" (generated by gherkin-ai).
# Mirrors POST /api/v1/${m.kebab}/{id}/{command} of the generated HTTP API.

"""Arbitrary JSON object (command payload)."""
scalar JSON

enum EventType {
${m.events.map(e => `  ${e}`).join('\n')}
}

type CommandResult {
  type: EventType!
  aggregateId: ID!
  version: Int!
}

type Query {
  """Liveness of the ${m.feature} service."""
  health: String!
}

type Mutation {
${m.commands.map(c => `  ${c.method}(id: ID!, payload: JSON, idempotencyKey: String): CommandResult!`).join('\n')}
}
`
  };
}

/** Node script (CommonJS) that validates the generated contracts; used by CI and golden builds. */
export const VALIDATE_CONTRACTS_SCRIPT = `#!/usr/bin/env node
// Validates contracts/*.graphql with graphql-js (generated by gherkin-ai). Protobuf is validated with \`buf\`.
const fs = require('fs');
const path = require('path');
const { buildSchema } = require('graphql');

const dir = path.join(__dirname);
const files = fs.readdirSync(dir).filter(f => f.endsWith('.graphql'));
for (const file of files) {
  const schema = buildSchema(fs.readFileSync(path.join(dir, file), 'utf8'));
  const mutations = Object.keys(schema.getMutationType()?.getFields() ?? {});
  console.log(\`\${file}: valid (\${mutations.length} mutations)\`);
}
if (files.length === 0) {
  console.error('No GraphQL contracts found');
  process.exit(1);
}
`;
