/* ==========================================================================
   gherkin-ai-cli - C# domain kernel (.NET 8, xUnit, Reqnroll)
   ========================================================================== */

import { DomainModel, cucumberExpression } from './domain-model';

const cs = (s: string) => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;

export function renderCsAggregate(m: DomainModel, ns: string): string {
  return `// Domain kernel for "${m.feature}" (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
namespace ${ns}.Domain.Kernel;

public sealed class DomainValidationException : Exception
{
    public DomainValidationException(string message) : base(message) { }
}

public static class ${m.pascal}States
{
${m.states.map(s => `    public const string ${s} = ${cs(s)};`).join('\n')}
}

public static class ${m.pascal}EventTypes
{
${m.events.map(e => `    public const string ${e} = ${cs(e)};`).join('\n')}
}

public sealed record ${m.pascal}Command(string Id, IReadOnlyDictionary<string, object?>? Payload = null);

public sealed record ${m.pascal}DomainEvent(string Type, string AggregateId, long Version, DateTimeOffset OccurredOn, IReadOnlyDictionary<string, object?> Payload);

public sealed class ${m.pascal}Aggregate
{
    private readonly List<${m.pascal}DomainEvent> _pendingEvents = new();

    public ${m.pascal}Aggregate(string id)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new DomainValidationException("${m.pascal} id is required");
        Id = id;
    }

    public string Id { get; }
    public string State { get; private set; } = ${m.pascal}States.${m.initialState};
    public long Version { get; private set; }

    /// <summary>Events recorded since the aggregate was loaded (to be saved via the outbox).</summary>
    public IReadOnlyList<${m.pascal}DomainEvent> PendingEvents => _pendingEvents;
${m.commands.map(c => `
    public ${m.pascal}DomainEvent ${c.name}(${m.pascal}Command command)
    {
        AssertValid(command);
        return Record(${m.pascal}EventTypes.${c.event}, command.Payload);
    }`).join('\n')}

    private void AssertValid(${m.pascal}Command command)
    {
        if (command is null || string.IsNullOrWhiteSpace(command.Id)) throw new DomainValidationException("Command id is required");
        if (command.Id != Id) throw new DomainValidationException($"Command targets {command.Id}, not {Id}");
    }

    private ${m.pascal}DomainEvent Record(string type, IReadOnlyDictionary<string, object?>? payload)
    {
        Version += 1;
        var @event = new ${m.pascal}DomainEvent(type, Id, Version, DateTimeOffset.UtcNow, payload ?? new Dictionary<string, object?>());
        _pendingEvents.Add(@event);
        return @event;
    }
}
`;
}

export function renderCsAggregateTests(m: DomainModel, ns: string): string {
  return `using ${ns}.Domain.Kernel;
using Xunit;

namespace ${ns}.Tests.Domain;

public class ${m.pascal}AggregateTests
{
    [Fact]
    public void Starts_in_the_initial_state_with_no_events()
    {
        var aggregate = new ${m.pascal}Aggregate("agg-1");
        Assert.Equal(${m.pascal}States.${m.initialState}, aggregate.State);
        Assert.Equal(0, aggregate.Version);
        Assert.Empty(aggregate.PendingEvents);
    }

    [Fact]
    public void Rejects_an_aggregate_without_id()
    {
        Assert.Throws<DomainValidationException>(() => new ${m.pascal}Aggregate(""));
    }
${m.commands.map(c => `
    [Fact]
    public void ${c.name}_records_${c.event}_and_bumps_the_version()
    {
        var aggregate = new ${m.pascal}Aggregate("agg-1");
        var @event = aggregate.${c.name}(new ${m.pascal}Command("agg-1"));
        Assert.Equal(${m.pascal}EventTypes.${c.event}, @event.Type);
        Assert.Equal(1, @event.Version);
        Assert.Equal(1, aggregate.Version);
        Assert.Single(aggregate.PendingEvents);
    }

    [Fact]
    public void ${c.name}_rejects_a_command_without_id()
    {
        var aggregate = new ${m.pascal}Aggregate("agg-1");
        Assert.Throws<DomainValidationException>(() => aggregate.${c.name}(new ${m.pascal}Command("")));
        Assert.Empty(aggregate.PendingEvents);
    }`).join('\n')}
}
`;
}

export function renderReqnrollSteps(m: DomainModel, ns: string): string {
  return `// Reqnroll step definitions for "${m.feature}" (generated by gherkin-ai).
// Each step is wired to the feature and pending until implemented (reqnroll.json ignores pending steps).
using ${ns}.Domain.Kernel;
using Reqnroll;

namespace ${ns}.Tests.Steps;

[Binding]
public class ${m.pascal}StepDefinitions
{
    private ${m.pascal}Aggregate _aggregate = new("scenario-aggregate");

    [BeforeScenario]
    public void ResetAggregate() => _aggregate = new ${m.pascal}Aggregate("scenario-aggregate");
${m.steps.map(s => `
    [${s.keyword}(${cs(cucumberExpression(s.text))})]
    public void ${s.id}()
    {
        // Pending: drive _aggregate (or the HTTP API) and assert the outcome.
        throw new PendingStepException();
    }`).join('\n')}
}
`;
}

export function renderCsTestProject(ns: string, appProject: string): string {
  return `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>${ns}.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Reqnroll.xUnit" Version="2.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.10" />
    <PackageReference Include="Testcontainers" Version="3.10.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="3.10.0" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="3.10.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../${appProject}" />
  </ItemGroup>
  <ItemGroup>
    <!-- The specification lives at the repository root; bind it into the test run. -->
    <ReqnrollFeatureFiles Include="../../features/**/*.feature" Link="Features/%(RecursiveDir)%(Filename)%(Extension)" />
    <!-- Reqnroll writes the code-behind next to the linked feature (outside this folder): compile it here. -->
    <Compile Include="../../features/**/*.feature.cs" Link="Features/%(RecursiveDir)%(Filename)%(Extension)" Visible="false" />
    <None Update="reqnroll.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
`;
}

export const REQNROLL_JSON = JSON.stringify({
  $schema: 'https://schemas.reqnroll.net/reqnroll-config-latest.json',
  runtime: { missingOrPendingStepsOutcome: 'Ignore' }
}, null, 2) + '\n';
