/* ==========================================================================
   gherkin-ai-cli - Elixir domain kernel (Phoenix API, ExUnit, Gherkin binder)
   ========================================================================== */

import { DomainModel, stepRegex } from './domain-model';

export interface ExFile {
  filename: string;
  content: string;
}

const exStr = (s: string) => JSON.stringify(s).replace(/#\{/g, '\\#{');
// Elixir ~r/.../ sigil with | delimiters: escape the delimiter only.
const exRegex = (text: string) => `~r|${stepRegex(text).replace(/\|/g, '\\|')}|`;

export interface ElixirNames {
  /** OTP application name, e.g. golden_elixir */
  otp: string;
  /** Root module, e.g. GoldenElixir */
  mod: string;
}

export function renderElixirProject(m: DomainModel, n: ElixirNames, featureFile: string): ExFile[] {
  const agg = `${n.mod}.Domain.${m.pascal}Aggregate`;
  const web = `${n.mod}Web`;
  const first = m.commands[0];
  return [
    {
      filename: 'mix.exs',
      content: `defmodule ${n.mod}.MixProject do
  use Mix.Project

  def project do
    [
      app: :${n.otp},
      version: "0.1.0",
      elixir: "~> 1.15",
      elixirc_paths: elixirc_paths(Mix.env()),
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  def application do
    [mod: {${n.mod}.Application, []}, extra_applications: [:logger]]
  end

  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  defp deps do
    [
      {:phoenix, "~> 1.7.14"},
      {:jason, "~> 1.4"},
      {:bandit, "~> 1.5"}
    ]
  end
end
`
    },
    {
      filename: 'config/config.exs',
      content: `import Config

config :${n.otp}, ${web}.Endpoint,
  adapter: Bandit.PhoenixAdapter,
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT", "4000"))],
  server: config_env() != :test,
  secret_key_base: System.get_env("SECRET_KEY_BASE", String.duplicate("dev-secret-change-me-", 4)),
  render_errors: [formats: [json: ${web}.ErrorJSON], layout: false]

config :phoenix, :json_library, Jason
config :logger, level: if(config_env() == :test, do: :warning, else: :info)
`
    },
    {
      filename: `lib/${n.otp}/application.ex`,
      content: `defmodule ${n.mod}.Application do
  @moduledoc false
  use Application

  @impl true
  def start(_type, _args) do
    Supervisor.start_link([${web}.Endpoint], strategy: :one_for_one, name: ${n.mod}.Supervisor)
  end
end
`
    },
    {
      filename: `lib/${n.otp}/domain/${m.snake}_aggregate.ex`,
      content: `defmodule ${agg} do
  @moduledoc """
  Domain kernel for ${exStr(m.feature)} (generated by gherkin-ai).
  Pure, functional domain logic: no framework, no I/O. Extend the command handlers with your business rules.
  """

  @states ~w(${m.states.join(' ')})
  @event_types ~w(${m.events.join(' ')})

  defstruct id: nil, state: ${exStr(m.initialState)}, version: 0, pending_events: []

  @type event :: %{type: String.t(), aggregate_id: String.t(), version: pos_integer(), occurred_on: DateTime.t(), payload: map()}
  @type t :: %__MODULE__{id: String.t(), state: String.t(), version: non_neg_integer(), pending_events: [event()]}

  def states, do: @states
  def event_types, do: @event_types

  @spec new(String.t()) :: {:ok, t()} | {:error, String.t()}
  def new(id) when is_binary(id) do
    if String.trim(id) == "", do: {:error, "${m.pascal} id is required"}, else: {:ok, %__MODULE__{id: id}}
  end

  def new(_), do: {:error, "${m.pascal} id is required"}
${m.commands.map(c => `
  @spec ${c.snake}(t(), map()) :: {:ok, t(), event()} | {:error, String.t()}
  def ${c.snake}(%__MODULE__{} = aggregate, command), do: execute(aggregate, command, ${exStr(c.event)})`).join('\n')}

  defp execute(aggregate, command, type) do
    with :ok <- validate(aggregate, command) do
      version = aggregate.version + 1
      event = %{type: type, aggregate_id: aggregate.id, version: version, occurred_on: DateTime.utc_now(), payload: Map.get(command, :payload, %{})}
      {:ok, %{aggregate | version: version, pending_events: aggregate.pending_events ++ [event]}, event}
    end
  end

  defp validate(aggregate, command) do
    id = Map.get(command, :id)

    cond do
      not is_binary(id) or String.trim(id) == "" -> {:error, "Command id is required"}
      id != aggregate.id -> {:error, "Command targets #{id}, not #{aggregate.id}"}
      true -> :ok
    end
  end
end
`
    },
    {
      filename: `lib/${n.otp}_web/endpoint.ex`,
      content: `defmodule ${web}.Endpoint do
  use Phoenix.Endpoint, otp_app: :${n.otp}

  plug Plug.RequestId
  plug Plug.Parsers, parsers: [:json], pass: ["application/json"], json_decoder: Phoenix.json_library()
  plug ${web}.Router
end
`
    },
    {
      filename: `lib/${n.otp}_web/router.ex`,
      content: `defmodule ${web}.Router do
  use Phoenix.Router

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ${web} do
    pipe_through :api
    get "/health", ${m.pascal}Controller, :health
    post "/api/v1/${m.kebab}/:id/:command", ${m.pascal}Controller, :execute
  end
end
`
    },
    {
      filename: `lib/${n.otp}_web/error_json.ex`,
      content: `defmodule ${web}.ErrorJSON do
  def render(template, _assigns), do: %{detail: Phoenix.Controller.status_message_from_template(template)}
end
`
    },
    {
      filename: `lib/${n.otp}_web/controllers/${m.snake}_controller.ex`,
      content: `defmodule ${web}.${m.pascal}Controller do
  use Phoenix.Controller, formats: [:json]

  alias ${agg}

  @commands %{
${m.commands.map(c => `    "${c.snake}" => &${m.pascal}Aggregate.${c.snake}/2`).join(',\n')}
  }

  def health(conn, _params), do: json(conn, %{status: "ok"})

  def execute(conn, %{"id" => id, "command" => command} = params) do
    payload = Map.drop(params, ["id", "command"])

    with {:ok, handler} <- Map.fetch(@commands, command),
         {:ok, aggregate} <- ${m.pascal}Aggregate.new(id),
         {:ok, _aggregate, event} <- handler.(aggregate, %{id: id, payload: payload}) do
      conn |> put_status(:created) |> json(%{type: event.type, aggregateId: event.aggregate_id, version: event.version})
    else
      :error -> conn |> put_status(:not_found) |> json(%{detail: "Unknown command #{command}"})
      {:error, reason} -> conn |> put_status(:unprocessable_entity) |> json(%{detail: reason})
    end
  end
end
`
    },
    { filename: 'test/test_helper.exs', content: `ExUnit.start()\n` },
    {
      filename: `test/${n.otp}/domain/${m.snake}_aggregate_test.exs`,
      content: `defmodule ${agg}Test do
  use ExUnit.Case, async: true

  alias ${agg}

  test "starts in the initial state with no events" do
    assert {:ok, aggregate} = ${m.pascal}Aggregate.new("agg-1")
    assert aggregate.state == ${exStr(m.initialState)}
    assert aggregate.version == 0
    assert aggregate.pending_events == []
  end

  test "rejects an aggregate without id" do
    assert {:error, _} = ${m.pascal}Aggregate.new("")
  end
${m.commands.map(c => `
  test "${c.snake} records ${c.event} and bumps the version" do
    {:ok, aggregate} = ${m.pascal}Aggregate.new("agg-1")
    assert {:ok, updated, event} = ${m.pascal}Aggregate.${c.snake}(aggregate, %{id: "agg-1"})
    assert event.type == ${exStr(c.event)}
    assert event.version == 1
    assert updated.version == 1
    assert updated.pending_events == [event]
  end

  test "${c.snake} rejects a command without id" do
    {:ok, aggregate} = ${m.pascal}Aggregate.new("agg-1")
    assert {:error, _} = ${m.pascal}Aggregate.${c.snake}(aggregate, %{id: ""})
  end`).join('\n')}
end
`
    },
    {
      filename: `test/${n.otp}_web/${m.snake}_controller_test.exs`,
      content: `defmodule ${web}.${m.pascal}ControllerTest do
  use ExUnit.Case, async: true
  import Plug.Conn
  import Phoenix.ConnTest

  @endpoint ${web}.Endpoint

  test "reports health" do
    conn = get(build_conn(), "/health")
    assert json_response(conn, 200) == %{"status" => "ok"}
  end

  test "executes a domain command and returns the event" do
    conn =
      build_conn()
      |> put_req_header("content-type", "application/json")
      |> post("/api/v1/${m.kebab}/agg-api/${first.snake}", Jason.encode!(%{source: "api-test"}))

    assert json_response(conn, 201) == %{"type" => ${exStr(first.event)}, "aggregateId" => "agg-api", "version" => 1}
  end

  test "returns 404 for unknown commands" do
    conn = post(build_conn(), "/api/v1/${m.kebab}/agg-api/does_not_exist")
    assert json_response(conn, 404)
  end
end
`
    },
    {
      filename: 'test/support/gherkin.ex',
      content: `defmodule ${n.mod}.Gherkin do
  @moduledoc """
  Minimal Gherkin reader for ExUnit (generated by gherkin-ai): returns scenarios with their
  steps, resolving And/But to the previous keyword. Enough to bind feature files to tests.
  """

  @spec scenarios(String.t()) :: [{String.t(), [{String.t(), String.t()}]}]
  def scenarios(source) do
    source
    |> String.split(~r/\\R/)
    |> Enum.map(&String.trim/1)
    |> Enum.reduce({[], nil, "Given"}, &line/2)
    |> then(fn {acc, current, _} -> Enum.reverse(push(acc, current)) end)
  end

  defp line("Scenario:" <> name, {acc, current, _}), do: {push(acc, current), {String.trim(name), []}, "Given"}
  defp line("Scenario Outline:" <> name, {acc, current, _}), do: {push(acc, current), {String.trim(name), []}, "Given"}

  defp line(text, {acc, {name, steps}, last}) do
    case Regex.run(~r/^(Given|When|Then|And|But)\\s+(.+)$/, text) do
      [_, kw, step] when kw in ["And", "But"] -> {acc, {name, steps ++ [{last, step}]}, last}
      [_, kw, step] -> {acc, {name, steps ++ [{kw, step}]}, kw}
      _ -> {acc, {name, steps}, last}
    end
  end

  defp line(_text, state), do: state

  defp push(acc, nil), do: acc
  defp push(acc, scenario), do: [scenario | acc]
end
`
    },
    {
      filename: `test/features/${m.snake}_feature_test.exs`,
      content: `defmodule ${n.mod}.Features.${m.pascal}FeatureTest do
  @moduledoc """
  Binds ${featureFile} to ExUnit (generated by gherkin-ai).
  Each scenario is a test, skipped while it has pending steps. Undefined steps fail the build.
  """
  use ExUnit.Case, async: true

  alias ${agg}

  @feature Path.expand("../../${featureFile}", __DIR__)
  @external_resource @feature

  # {keyword, regex, status}: switch a step to :implemented once its clause below asserts real behavior.
  @steps [
${m.steps.map(s => `    {${exStr(s.keyword)}, ${exRegex(s.text)}, :pending}`).join(',\n')}
  ]

  @scenarios ${n.mod}.Gherkin.scenarios(File.read!(@feature))

  defp definition(keyword, text), do: Enum.find(@steps, fn {kw, re, _} -> kw == keyword and Regex.match?(re, text) end)

  test "every step in the feature has a definition" do
    undefined =
      for {name, steps} <- @scenarios, {kw, text} <- steps, definition(kw, text) == nil, do: "#{name}: #{kw} #{text}"

    assert undefined == [], "Undefined steps:\\n" <> Enum.join(undefined, "\\n")
  end

  for {name, steps} <- @scenarios do
    pending? = Enum.any?(steps, fn {kw, text} -> match?({_, _, :pending}, Enum.find(@steps, fn {k, re, _} -> k == kw and Regex.match?(re, text) end)) end)
    if pending?, do: @tag(:skip)

    test "Scenario: #{name}" do
      {:ok, _aggregate} = ${m.pascal}Aggregate.new("scenario-aggregate")
      # Pending: implement the steps, mark them :implemented in @steps and assert here.
      :ok
    end
  end
end
`
    }
  ];
}
