/* ==========================================================================
   gherkin-ai-cli - Go domain kernel (chi, testing, godog)
   ========================================================================== */

import { DomainModel, stepRegex, toPascal } from './domain-model';

export interface GoFile {
  filename: string;
  content: string;
}

const goStr = (s: string) => JSON.stringify(s);
const stateConst = (s: string) => `State${toPascal(s)}`;
const eventConst = (e: string) => `Event${e}`;

export function renderGoKernel(m: DomainModel, module: string): GoFile[] {
  return [
    {
      filename: `internal/domain/${m.snake}.go`,
      content: `// Package domain holds the domain kernel for ${goStr(m.feature)} (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
package domain

import (
	"errors"
	"fmt"
	"strings"
	"time"
)

// ErrValidation is wrapped by every domain validation failure.
var ErrValidation = errors.New("domain validation error")

type State string

const (
${m.states.map(s => `	${stateConst(s)} State = ${goStr(s)}`).join('\n')}
)

type EventType string

const (
${m.events.map(e => `	${eventConst(e)} EventType = ${goStr(e)}`).join('\n')}
)

type Command struct {
	ID      string
	Payload map[string]any
}

type DomainEvent struct {
	Type        EventType
	AggregateID string
	Version     int64
	OccurredOn  time.Time
	Payload     map[string]any
}

type ${m.pascal}Aggregate struct {
	ID            string
	State         State
	Version       int64
	pendingEvents []DomainEvent
}

func New${m.pascal}Aggregate(id string) (*${m.pascal}Aggregate, error) {
	if strings.TrimSpace(id) == "" {
		return nil, fmt.Errorf("%w: ${m.pascal} id is required", ErrValidation)
	}
	return &${m.pascal}Aggregate{ID: id, State: ${stateConst(m.initialState)}}, nil
}

// PendingEvents returns the events recorded since the aggregate was loaded (to be saved via the outbox).
func (a *${m.pascal}Aggregate) PendingEvents() []DomainEvent {
	return append([]DomainEvent(nil), a.pendingEvents...)
}
${m.commands.map(c => `
func (a *${m.pascal}Aggregate) ${c.name}(cmd Command) (DomainEvent, error) {
	if err := a.assertValid(cmd); err != nil {
		return DomainEvent{}, err
	}
	return a.record(${eventConst(c.event)}, cmd.Payload), nil
}`).join('\n')}

func (a *${m.pascal}Aggregate) assertValid(cmd Command) error {
	if strings.TrimSpace(cmd.ID) == "" {
		return fmt.Errorf("%w: command id is required", ErrValidation)
	}
	if cmd.ID != a.ID {
		return fmt.Errorf("%w: command targets %s, not %s", ErrValidation, cmd.ID, a.ID)
	}
	return nil
}

func (a *${m.pascal}Aggregate) record(t EventType, payload map[string]any) DomainEvent {
	a.Version++
	if payload == nil {
		payload = map[string]any{}
	}
	event := DomainEvent{Type: t, AggregateID: a.ID, Version: a.Version, OccurredOn: time.Now().UTC(), Payload: payload}
	a.pendingEvents = append(a.pendingEvents, event)
	return event
}
`
    },
    {
      filename: `internal/domain/${m.snake}_test.go`,
      content: `package domain

import (
	"errors"
	"testing"
)

func TestStartsInTheInitialStateWithNoEvents(t *testing.T) {
	a, err := New${m.pascal}Aggregate("agg-1")
	if err != nil {
		t.Fatal(err)
	}
	if a.State != ${stateConst(m.initialState)} || a.Version != 0 || len(a.PendingEvents()) != 0 {
		t.Fatalf("unexpected initial aggregate: %+v", a)
	}
}

func TestRejectsAnAggregateWithoutID(t *testing.T) {
	if _, err := New${m.pascal}Aggregate(""); !errors.Is(err, ErrValidation) {
		t.Fatalf("expected ErrValidation, got %v", err)
	}
}
${m.commands.map(c => `
func Test${c.name}RecordsEventAndBumpsTheVersion(t *testing.T) {
	a, _ := New${m.pascal}Aggregate("agg-1")
	event, err := a.${c.name}(Command{ID: "agg-1"})
	if err != nil {
		t.Fatal(err)
	}
	if event.Type != ${eventConst(c.event)} || event.Version != 1 || a.Version != 1 || len(a.PendingEvents()) != 1 {
		t.Fatalf("unexpected result: %+v / %+v", event, a)
	}
}

func Test${c.name}RejectsACommandWithoutID(t *testing.T) {
	a, _ := New${m.pascal}Aggregate("agg-1")
	if _, err := a.${c.name}(Command{}); !errors.Is(err, ErrValidation) {
		t.Fatalf("expected ErrValidation, got %v", err)
	}
	if len(a.PendingEvents()) != 0 {
		t.Fatal("no event must be recorded on failure")
	}
}`).join('\n')}
`
    },
    {
      filename: 'internal/httpapi/router.go',
      content: `// Package httpapi exposes the domain kernel over HTTP (chi).
package httpapi

import (
	"encoding/json"
	"errors"
	"net/http"
	"sync"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"

	"${module}/internal/domain"
)

type commandFunc func(*domain.${m.pascal}Aggregate, domain.Command) (domain.DomainEvent, error)

var commands = map[string]commandFunc{
${m.commands.map(c => `	"${c.snake}": (*domain.${m.pascal}Aggregate).${c.name},`).join('\n')}
}

// NewRouter wires the routes. The in-memory store is a placeholder for a repository.
func NewRouter() http.Handler {
	var mu sync.Mutex
	store := map[string]*domain.${m.pascal}Aggregate{}

	r := chi.NewRouter()
	r.Use(middleware.Recoverer)

	r.Get("/health", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
	})

	r.Post("/api/v1/${m.kebab}/{id}/{command}", func(w http.ResponseWriter, req *http.Request) {
		handler, ok := commands[chi.URLParam(req, "command")]
		if !ok {
			writeJSON(w, http.StatusNotFound, map[string]string{"detail": "unknown command"})
			return
		}
		id := chi.URLParam(req, "id")
		var payload map[string]any
		_ = json.NewDecoder(req.Body).Decode(&payload)

		mu.Lock()
		defer mu.Unlock()
		aggregate, exists := store[id]
		if !exists {
			created, err := domain.New${m.pascal}Aggregate(id)
			if err != nil {
				writeJSON(w, http.StatusUnprocessableEntity, map[string]string{"detail": err.Error()})
				return
			}
			aggregate = created
			store[id] = aggregate
		}
		event, err := handler(aggregate, domain.Command{ID: id, Payload: payload})
		if errors.Is(err, domain.ErrValidation) {
			writeJSON(w, http.StatusUnprocessableEntity, map[string]string{"detail": err.Error()})
			return
		}
		writeJSON(w, http.StatusCreated, map[string]any{"type": event.Type, "aggregateId": event.AggregateID, "version": event.Version})
	})
	return r
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}
`
    },
    {
      filename: 'internal/httpapi/router_test.go',
      content: `package httpapi

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestHealth(t *testing.T) {
	rec := httptest.NewRecorder()
	NewRouter().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/health", nil))
	if rec.Code != http.StatusOK {
		t.Fatalf("status %d", rec.Code)
	}
}

func TestExecutesADomainCommand(t *testing.T) {
	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodPost, "/api/v1/${m.kebab}/agg-api/${m.commands[0].snake}", strings.NewReader(\`{"source":"api-test"}\`))
	NewRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusCreated {
		t.Fatalf("status %d: %s", rec.Code, rec.Body.String())
	}
	var body map[string]any
	_ = json.Unmarshal(rec.Body.Bytes(), &body)
	if body["type"] != ${goStr(m.commands[0].event)} || body["version"] != float64(1) {
		t.Fatalf("unexpected body: %v", body)
	}
}

func TestUnknownCommandReturns404(t *testing.T) {
	rec := httptest.NewRecorder()
	NewRouter().ServeHTTP(rec, httptest.NewRequest(http.MethodPost, "/api/v1/${m.kebab}/agg-api/nope", nil))
	if rec.Code != http.StatusNotFound {
		t.Fatalf("status %d", rec.Code)
	}
}
`
    },
    {
      filename: 'cmd/server/main.go',
      content: `package main

import (
	"log"
	"net/http"
	"os"

	"${module}/internal/httpapi"
)

func main() {
	addr := ":" + envOr("PORT", "8080")
	log.Printf("listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, httpapi.NewRouter()))
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
`
    },
    {
      filename: 'test/bdd/features_test.go',
      content: `// Package bdd runs ./features with godog (generated by gherkin-ai).
// Steps are pending until implemented; non-strict mode reports them without failing.
package bdd

import (
	"context"
	"testing"

	"github.com/cucumber/godog"

	"${module}/internal/domain"
)

type world struct {
	aggregate *domain.${m.pascal}Aggregate
}
${m.steps.map(s => `
func (w *world) ${toPascal(s.id)}(ctx context.Context) error {
	// Pending: drive w.aggregate (or the HTTP API) and assert the outcome.
	return godog.ErrPending
}`).join('\n')}

func initializeScenario(sc *godog.ScenarioContext) {
	w := &world{}
	sc.Before(func(ctx context.Context, _ *godog.Scenario) (context.Context, error) {
		aggregate, err := domain.New${m.pascal}Aggregate("scenario-aggregate")
		w.aggregate = aggregate
		return ctx, err
	})
${m.steps.map(s => `	sc.Step(\`${stepRegex(s.text).replace(/`/g, '')}\`, w.${toPascal(s.id)})`).join('\n')}
}

func TestFeatures(t *testing.T) {
	suite := godog.TestSuite{
		ScenarioInitializer: initializeScenario,
		Options: &godog.Options{
			Format:   "pretty",
			Paths:    []string{"../../features"},
			Strict:   false,
			TestingT: t,
		},
	}
	if suite.Run() != 0 {
		t.Fatal("feature run failed")
	}
}
`
    }
  ];
}

export function renderGoMod(module: string): string {
  return `module ${module}

go 1.22

require (
	github.com/cucumber/godog v0.14.1
	github.com/go-chi/chi/v5 v5.1.0
	github.com/google/uuid v1.6.0
	github.com/jackc/pgx/v5 v5.7.1
)
`;
}
