/* ==========================================================================
   gherkin-ai-cli - Java domain kernel (Spring Boot 3, JUnit 5, Cucumber-JVM)
   ========================================================================== */

import { DomainModel, cucumberExpression } from './domain-model';

export interface JavaFile {
  filename: string;
  content: string;
}

const js = (s: string) => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const toJavaMethod = (id: string) => id.replace(/_([a-z0-9])/g, (_m, c: string) => c.toUpperCase());

export function javaPackagePath(pkg: string): string {
  return pkg.replace(/\./g, '/');
}

export function renderJavaKernel(m: DomainModel, pkg: string): JavaFile[] {
  const dir = `src/main/java/${javaPackagePath(pkg)}/domain`;
  const p = `package ${pkg}.domain;\n\n`;
  return [
    {
      filename: `${dir}/DomainValidationException.java`,
      content: `${p}public class DomainValidationException extends RuntimeException {
    public DomainValidationException(String message) {
        super(message);
    }
}
`
    },
    {
      filename: `${dir}/${m.pascal}State.java`,
      content: `${p}public enum ${m.pascal}State {
    ${m.states.join(',\n    ')}
}
`
    },
    {
      filename: `${dir}/${m.pascal}EventType.java`,
      content: `${p}public enum ${m.pascal}EventType {
    ${m.events.join(',\n    ')}
}
`
    },
    {
      filename: `${dir}/${m.pascal}Command.java`,
      content: `${p}import java.util.Map;

public record ${m.pascal}Command(String id, Map<String, Object> payload) {
    public ${m.pascal}Command(String id) {
        this(id, Map.of());
    }
}
`
    },
    {
      filename: `${dir}/${m.pascal}DomainEvent.java`,
      content: `${p}import java.time.Instant;
import java.util.Map;

public record ${m.pascal}DomainEvent(${m.pascal}EventType type, String aggregateId, long version, Instant occurredOn, Map<String, Object> payload) {
}
`
    },
    {
      filename: `${dir}/${m.pascal}Aggregate.java`,
      content: `${p}import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * Domain kernel for "${m.feature}" (generated by gherkin-ai).
 * Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
 */
public class ${m.pascal}Aggregate {
    private final String id;
    private ${m.pascal}State state = ${m.pascal}State.${m.initialState};
    private long version;
    private final List<${m.pascal}DomainEvent> pendingEvents = new ArrayList<>();

    public ${m.pascal}Aggregate(String id) {
        if (id == null || id.isBlank()) throw new DomainValidationException("${m.pascal} id is required");
        this.id = id;
    }

    public String getId() { return id; }
    public ${m.pascal}State getState() { return state; }
    public long getVersion() { return version; }

    /** Events recorded since the aggregate was loaded (to be saved via the outbox). */
    public List<${m.pascal}DomainEvent> getPendingEvents() { return Collections.unmodifiableList(pendingEvents); }
${m.commands.map(c => `
    public ${m.pascal}DomainEvent ${c.method}(${m.pascal}Command command) {
        assertValid(command);
        return record(${m.pascal}EventType.${c.event}, command.payload());
    }`).join('\n')}

    private void assertValid(${m.pascal}Command command) {
        if (command == null || command.id() == null || command.id().isBlank()) throw new DomainValidationException("Command id is required");
        if (!command.id().equals(id)) throw new DomainValidationException("Command targets " + command.id() + ", not " + id);
    }

    private ${m.pascal}DomainEvent record(${m.pascal}EventType type, Map<String, Object> payload) {
        version += 1;
        var event = new ${m.pascal}DomainEvent(type, id, version, Instant.now(), payload == null ? Map.of() : payload);
        pendingEvents.add(event);
        return event;
    }
}
`
    }
  ];
}

export function renderJavaKernelTests(m: DomainModel, pkg: string): JavaFile[] {
  const base = `src/test/java/${javaPackagePath(pkg)}`;
  return [
    {
      filename: `${base}/domain/${m.pascal}AggregateTest.java`,
      content: `package ${pkg}.domain;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class ${m.pascal}AggregateTest {

    @Test
    void startsInTheInitialStateWithNoEvents() {
        var aggregate = new ${m.pascal}Aggregate("agg-1");
        assertEquals(${m.pascal}State.${m.initialState}, aggregate.getState());
        assertEquals(0, aggregate.getVersion());
        assertTrue(aggregate.getPendingEvents().isEmpty());
    }

    @Test
    void rejectsAnAggregateWithoutId() {
        assertThrows(DomainValidationException.class, () -> new ${m.pascal}Aggregate(""));
    }
${m.commands.map(c => `
    @Test
    void ${c.method}Records${c.event}AndBumpsTheVersion() {
        var aggregate = new ${m.pascal}Aggregate("agg-1");
        var event = aggregate.${c.method}(new ${m.pascal}Command("agg-1"));
        assertEquals(${m.pascal}EventType.${c.event}, event.type());
        assertEquals(1, event.version());
        assertEquals(1, aggregate.getVersion());
        assertEquals(1, aggregate.getPendingEvents().size());
    }

    @Test
    void ${c.method}RejectsACommandWithoutId() {
        var aggregate = new ${m.pascal}Aggregate("agg-1");
        assertThrows(DomainValidationException.class, () -> aggregate.${c.method}(new ${m.pascal}Command("")));
        assertTrue(aggregate.getPendingEvents().isEmpty());
    }`).join('\n')}
}
`
    },
    {
      filename: `${base}/bdd/RunCucumberTest.java`,
      content: `package ${pkg}.bdd;

import static io.cucumber.junit.platform.engine.Constants.GLUE_PROPERTY_NAME;
import static io.cucumber.junit.platform.engine.Constants.PLUGIN_PROPERTY_NAME;

import org.junit.platform.suite.api.ConfigurationParameter;
import org.junit.platform.suite.api.IncludeEngines;
import org.junit.platform.suite.api.SelectClasspathResource;
import org.junit.platform.suite.api.Suite;

/** Runs the feature files (copied from ./features as test resources). Pending steps are reported as skipped. */
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("features")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "${pkg}.bdd")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "pretty")
public class RunCucumberTest {
}
`
    },
    {
      filename: `${base}/bdd/${m.pascal}Steps.java`,
      content: `package ${pkg}.bdd;

import ${pkg}.domain.${m.pascal}Aggregate;
import io.cucumber.java.Before;
import org.opentest4j.TestAbortedException;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

/** Step definitions for "${m.feature}" (generated by gherkin-ai): wired to the feature, pending until implemented.
 *  Pending steps abort (reported as skipped) instead of failing the build. */
public class ${m.pascal}Steps {
    private ${m.pascal}Aggregate aggregate;

    @Before
    public void resetAggregate() {
        aggregate = new ${m.pascal}Aggregate("scenario-aggregate");
    }
${m.steps.map(s => `
    @${s.keyword}(${js(cucumberExpression(s.text))})
    public void ${toJavaMethod(s.id)}() {
        // Pending: drive the aggregate (or the HTTP API) and assert the outcome.
        throw new TestAbortedException("Pending step: implement it, then remove this line");
    }`).join('\n')}
}
`
    }
  ];
}

export function renderSpringApplication(pkg: string): JavaFile {
  return {
    filename: `src/main/java/${javaPackagePath(pkg)}/Application.java`,
    content: `package ${pkg};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
`
  };
}

export function renderPom(artifactId: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.5</version>
    <relativePath/>
  </parent>

  <groupId>com.example</groupId>
  <artifactId>${artifactId}</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
    <java.version>17</java.version>
    <cucumber.version>7.20.1</cucumber.version>
    <opentelemetry.version>1.43.0</opentelemetry.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom</artifactId>
        <version>\${opentelemetry.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-bom</artifactId>
        <version>\${cucumber.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-sdk</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-exporter-otlp</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.cucumber</groupId>
      <artifactId>cucumber-java</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.cucumber</groupId>
      <artifactId>cucumber-junit-platform-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-suite</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <testResources>
      <testResource>
        <directory>src/test/resources</directory>
      </testResource>
      <!-- The Gherkin specification is the single source of truth: run it from ./features. -->
      <testResource>
        <directory>features</directory>
        <targetPath>features</targetPath>
      </testResource>
    </testResources>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
`;
}
