/* ==========================================================================
   gherkin-ai-cli - Kotlin domain kernel (Spring Boot 3, Gradle KTS, JUnit 5, Cucumber-JVM)
   ========================================================================== */

import { DomainModel, cucumberExpression } from './domain-model';
import { javaPackagePath, JavaFile } from './java';

// Kotlin string literal: escape backslash, quote and the string-template marker.
const kt = (s: string) => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const toKtMethod = (id: string) => id.replace(/_([a-z0-9])/g, (_m, c: string) => c.toUpperCase());

export function renderKotlinKernel(m: DomainModel, pkg: string): JavaFile[] {
  const dir = `src/main/kotlin/${javaPackagePath(pkg)}/domain`;
  return [{
    filename: `${dir}/${m.pascal}Aggregate.kt`,
    content: `package ${pkg}.domain

import java.time.Instant

// Domain kernel for "${m.feature}" (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.

class DomainValidationException(message: String) : RuntimeException(message)

enum class ${m.pascal}State { ${m.states.join(', ')} }

enum class ${m.pascal}EventType { ${m.events.join(', ')} }

data class ${m.pascal}Command(val id: String, val payload: Map<String, Any?> = emptyMap())

data class ${m.pascal}DomainEvent(
    val type: ${m.pascal}EventType,
    val aggregateId: String,
    val version: Long,
    val occurredOn: Instant,
    val payload: Map<String, Any?>
)

class ${m.pascal}Aggregate(val id: String) {
    var state: ${m.pascal}State = ${m.pascal}State.${m.initialState}
        private set
    var version: Long = 0
        private set
    private val _pendingEvents = mutableListOf<${m.pascal}DomainEvent>()

    /** Events recorded since the aggregate was loaded (to be saved via the outbox). */
    val pendingEvents: List<${m.pascal}DomainEvent> get() = _pendingEvents.toList()

    init {
        if (id.isBlank()) throw DomainValidationException("${m.pascal} id is required")
    }

    companion object {
        /** Rebuilds an aggregate from persisted state; no events are recorded. */
        @JvmStatic
        fun restore(id: String, state: ${m.pascal}State, version: Long): ${m.pascal}Aggregate =
            ${m.pascal}Aggregate(id).also {
                it.state = state
                it.version = version
            }
    }
${m.commands.map(c => `
    fun ${c.method}(command: ${m.pascal}Command): ${m.pascal}DomainEvent {
        assertValid(command)
        return record(${m.pascal}EventType.${c.event}, command.payload)
    }`).join('\n')}

    private fun assertValid(command: ${m.pascal}Command) {
        if (command.id.isBlank()) throw DomainValidationException("Command id is required")
        if (command.id != id) throw DomainValidationException("Command targets \${command.id}, not \$id")
    }

    private fun record(type: ${m.pascal}EventType, payload: Map<String, Any?>): ${m.pascal}DomainEvent {
        version += 1
        val event = ${m.pascal}DomainEvent(type, id, version, Instant.now(), payload)
        _pendingEvents += event
        return event
    }
}
`
  }];
}

export function renderKotlinKernelTests(m: DomainModel, pkg: string): JavaFile[] {
  const base = `src/test/kotlin/${javaPackagePath(pkg)}`;
  return [
    {
      filename: `${base}/domain/${m.pascal}AggregateTest.kt`,
      content: `package ${pkg}.domain

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

class ${m.pascal}AggregateTest {

    @Test
    fun \`starts in the initial state with no events\`() {
        val aggregate = ${m.pascal}Aggregate("agg-1")
        assertEquals(${m.pascal}State.${m.initialState}, aggregate.state)
        assertEquals(0, aggregate.version)
        assertTrue(aggregate.pendingEvents.isEmpty())
    }

    @Test
    fun \`rejects an aggregate without id\`() {
        assertFailsWith<DomainValidationException> { ${m.pascal}Aggregate("") }
    }
${m.commands.map(c => `
    @Test
    fun \`${c.method} records ${c.event} and bumps the version\`() {
        val aggregate = ${m.pascal}Aggregate("agg-1")
        val event = aggregate.${c.method}(${m.pascal}Command("agg-1"))
        assertEquals(${m.pascal}EventType.${c.event}, event.type)
        assertEquals(1, event.version)
        assertEquals(1, aggregate.version)
        assertEquals(1, aggregate.pendingEvents.size)
    }

    @Test
    fun \`${c.method} rejects a command without id\`() {
        val aggregate = ${m.pascal}Aggregate("agg-1")
        assertFailsWith<DomainValidationException> { aggregate.${c.method}(${m.pascal}Command("")) }
        assertTrue(aggregate.pendingEvents.isEmpty())
    }`).join('\n')}
}
`
    },
    {
      filename: `${base}/bdd/RunCucumberTest.kt`,
      content: `package ${pkg}.bdd

import io.cucumber.junit.platform.engine.Constants.GLUE_PROPERTY_NAME
import io.cucumber.junit.platform.engine.Constants.PLUGIN_PROPERTY_NAME
import org.junit.platform.suite.api.ConfigurationParameter
import org.junit.platform.suite.api.IncludeEngines
import org.junit.platform.suite.api.SelectClasspathResource
import org.junit.platform.suite.api.Suite

/** Runs ./features (copied as test resources). Pending steps are reported as skipped. */
@Suite(failIfNoTests = false) // the runtime integration run (tag "integration") selects no scenarios
@IncludeEngines("cucumber")
@SelectClasspathResource("features")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "${pkg}.bdd")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "pretty")
class RunCucumberTest
`
    },
    {
      filename: `${base}/bdd/${m.pascal}Steps.kt`,
      content: `package ${pkg}.bdd

import ${pkg}.domain.${m.pascal}Aggregate
import io.cucumber.java.Before
import io.cucumber.java.en.Given
import io.cucumber.java.en.Then
import io.cucumber.java.en.When
import org.opentest4j.TestAbortedException

/** Step definitions for "${m.feature}" (generated by gherkin-ai): wired to the feature, pending until implemented.
 *  Pending steps abort (reported as skipped) instead of failing the build. */
class ${m.pascal}Steps {
    private lateinit var aggregate: ${m.pascal}Aggregate

    @Before
    fun resetAggregate() {
        aggregate = ${m.pascal}Aggregate("scenario-aggregate")
    }
${m.steps.map(s => `
    @${s.keyword}(${kt(cucumberExpression(s.text))})
    fun ${toKtMethod(s.id)}() {
        // Pending: drive the aggregate (or the HTTP API) and assert the outcome.
        throw TestAbortedException("Pending step: implement it, then remove this line")
    }`).join('\n')}
}
`
    }
  ];
}

export function renderKotlinApplication(pkg: string): JavaFile {
  return {
    filename: `src/main/kotlin/${javaPackagePath(pkg)}/Application.kt`,
    content: `package ${pkg}

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.scheduling.annotation.EnableScheduling

@SpringBootApplication
@EnableScheduling
class Application

fun main(args: Array<String>) {
    runApplication<Application>(*args)
}
`
  };
}

export function renderGradleKts(): string {
  return `plugins {
    id("org.springframework.boot") version "3.3.5"
    id("io.spring.dependency-management") version "1.1.6"
    kotlin("jvm") version "1.9.25"
    kotlin("plugin.spring") version "1.9.25"
    kotlin("plugin.jpa") version "1.9.25"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom("io.opentelemetry:opentelemetry-bom:1.43.0")
        mavenBom("io.cucumber:cucumber-bom:7.20.1")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("io.opentelemetry:opentelemetry-api")
    implementation("io.opentelemetry:opentelemetry-sdk")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp")
    implementation("com.rabbitmq:amqp-client")
    runtimeOnly("org.postgresql:postgresql")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testImplementation("io.opentelemetry:opentelemetry-sdk-testing")
    testImplementation("io.cucumber:cucumber-java")
    testImplementation("io.cucumber:cucumber-junit-platform-engine")
    testImplementation("org.junit.platform:junit-platform-suite")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

kotlin {
    compilerOptions {
        freeCompilerArgs.addAll("-Xjsr305=strict")
    }
}

// The Gherkin specification is the single source of truth: run it from ./features.
tasks.processTestResources {
    from("features") { into("features") }
}

tasks.withType<Test> {
    useJUnitPlatform()
    testLogging { events("passed", "skipped", "failed") }
}

// Runtime integration tests (tag "integration") need DATABASE_URL / AMQP_URL: gradle integrationTest
tasks.test {
    useJUnitPlatform { excludeTags("integration") }
}

val integrationTest by tasks.registering(Test::class) {
    description = "Runs the runtime integration tests against PostgreSQL and RabbitMQ."
    group = "verification"
    testClassesDirs = sourceSets.test.get().output.classesDirs
    classpath = sourceSets.test.get().runtimeClasspath
    useJUnitPlatform { includeTags("integration") }
}
`;
}

export function renderGradleSettings(projectName: string): string {
  return `rootProject.name = "${projectName}"\n`;
}
