/* ==========================================================================
   gherkin-ai-cli - PHP domain kernel (Laravel 13, PHPUnit 12, Behat)
   ========================================================================== */

import { PHP_RUNTIME_REQUIRE } from './runtime/php';
import { DomainModel, stepRegex, toPascal } from './domain-model';

export interface PhpFile {
  filename: string;
  content: string;
}

const phpStr = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const phpMethod = (id: string) => id.replace(/_([a-z0-9])/g, (_m, c: string) => c.toUpperCase());

export function renderPhpKernel(m: DomainModel): PhpFile[] {
  const ns = `App\\Domain\\${m.pascal}`;
  const dir = `app/Domain/${m.pascal}`;
  const head = `<?php\n\ndeclare(strict_types=1);\n\nnamespace ${ns};\n\n`;
  return [
    { filename: `${dir}/DomainValidationException.php`, content: `${head}final class DomainValidationException extends \\DomainException\n{\n}\n` },
    { filename: `${dir}/${m.pascal}State.php`, content: `${head}enum ${m.pascal}State: string\n{\n${m.states.map(s => `    case ${toPascal(s)} = ${phpStr(s)};`).join('\n')}\n}\n` },
    { filename: `${dir}/${m.pascal}EventType.php`, content: `${head}enum ${m.pascal}EventType: string\n{\n${m.events.map(e => `    case ${e} = ${phpStr(e)};`).join('\n')}\n}\n` },
    {
      filename: `${dir}/${m.pascal}Command.php`,
      content: `${head}final readonly class ${m.pascal}Command
{
    /** @param array<string, mixed> $payload */
    public function __construct(public string $id, public array $payload = [])
    {
    }
}
`
    },
    {
      filename: `${dir}/${m.pascal}DomainEvent.php`,
      content: `${head}use DateTimeImmutable;

final readonly class ${m.pascal}DomainEvent
{
    /** @param array<string, mixed> $payload */
    public function __construct(
        public ${m.pascal}EventType $type,
        public string $aggregateId,
        public int $version,
        public DateTimeImmutable $occurredOn,
        public array $payload,
    ) {
    }
}
`
    },
    {
      filename: `${dir}/${m.pascal}Aggregate.php`,
      content: `${head}use DateTimeImmutable;

/**
 * Domain kernel for "${m.feature}" (generated by gherkin-ai).
 * Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
 */
final class ${m.pascal}Aggregate
{
    private ${m.pascal}State $state = ${m.pascal}State::${toPascal(m.initialState)};
    private int $version = 0;
    /** @var list<${m.pascal}DomainEvent> */
    private array $pendingEvents = [];

    public function __construct(private readonly string $id)
    {
        if (trim($id) === '') {
            throw new DomainValidationException('${m.pascal} id is required');
        }
    }

    /** Rebuilds an aggregate from persisted state; no events are recorded. */
    public static function restore(string $id, ${m.pascal}State $state, int $version): self
    {
        $aggregate = new self($id);
        $aggregate->state = $state;
        $aggregate->version = $version;
        return $aggregate;
    }

    public function id(): string { return $this->id; }
    public function state(): ${m.pascal}State { return $this->state; }
    public function version(): int { return $this->version; }

    /** @return list<${m.pascal}DomainEvent> Events recorded since load (to be saved via the outbox). */
    public function pendingEvents(): array { return $this->pendingEvents; }
${m.commands.map(c => `
    public function ${c.method}(${m.pascal}Command $command): ${m.pascal}DomainEvent
    {
        $this->assertValid($command);
        return $this->record(${m.pascal}EventType::${c.event}, $command->payload);
    }`).join('\n')}

    private function assertValid(${m.pascal}Command $command): void
    {
        if (trim($command->id) === '') {
            throw new DomainValidationException('Command id is required');
        }
        if ($command->id !== $this->id) {
            throw new DomainValidationException("Command targets {$command->id}, not {$this->id}");
        }
    }

    /** @param array<string, mixed> $payload */
    private function record(${m.pascal}EventType $type, array $payload): ${m.pascal}DomainEvent
    {
        $this->version++;
        $event = new ${m.pascal}DomainEvent($type, $this->id, $this->version, new DateTimeImmutable(), $payload);
        $this->pendingEvents[] = $event;
        return $event;
    }
}
`
    }
  ];
}

export function renderPhpController(m: DomainModel): PhpFile {
  return {
    filename: `app/Http/Controllers/${m.pascal}Controller.php`,
    content: `<?php

declare(strict_types=1);

namespace App\\Http\\Controllers;

use App\\Domain\\${m.pascal}\\${m.pascal}Aggregate;
use App\\Domain\\${m.pascal}\\${m.pascal}Command;
use App\\Domain\\${m.pascal}\\DomainValidationException;
use Illuminate\\Http\\JsonResponse;
use Illuminate\\Http\\Request;

final class ${m.pascal}Controller
{
    private const COMMANDS = [
${m.commands.map(c => `        '${c.snake}' => '${c.method}',`).join('\n')}
    ];

    public function execute(Request $request, string $id, string $command): JsonResponse
    {
        $method = self::COMMANDS[$command] ?? null;
        if ($method === null) {
            return response()->json(['detail' => "Unknown command {$command}"], 404);
        }
        try {
            // In-memory aggregate: replace with a repository + outbox.
            $event = (new ${m.pascal}Aggregate($id))->{$method}(new ${m.pascal}Command($id, $request->all()));
        } catch (DomainValidationException $e) {
            return response()->json(['detail' => $e->getMessage()], 422);
        }
        return response()->json(['type' => $event->type->value, 'aggregateId' => $event->aggregateId, 'version' => $event->version], 201);
    }
}
`
  };
}

export function renderPhpTests(m: DomainModel): PhpFile[] {
  const first = m.commands[0];
  return [
    {
      filename: 'tests/TestCase.php',
      content: `<?php\n\nnamespace Tests;\n\nuse Illuminate\\Foundation\\Testing\\TestCase as BaseTestCase;\n\nabstract class TestCase extends BaseTestCase\n{\n}\n`
    },
    {
      filename: `tests/Unit/${m.pascal}AggregateTest.php`,
      content: `<?php

declare(strict_types=1);

namespace Tests\\Unit;

use App\\Domain\\${m.pascal}\\${m.pascal}Aggregate;
use App\\Domain\\${m.pascal}\\${m.pascal}Command;
use App\\Domain\\${m.pascal}\\${m.pascal}EventType;
use App\\Domain\\${m.pascal}\\${m.pascal}State;
use App\\Domain\\${m.pascal}\\DomainValidationException;
use PHPUnit\\Framework\\TestCase;

final class ${m.pascal}AggregateTest extends TestCase
{
    public function test_starts_in_the_initial_state_with_no_events(): void
    {
        $aggregate = new ${m.pascal}Aggregate('agg-1');
        self::assertSame(${m.pascal}State::${toPascal(m.initialState)}, $aggregate->state());
        self::assertSame(0, $aggregate->version());
        self::assertSame([], $aggregate->pendingEvents());
    }

    public function test_rejects_an_aggregate_without_id(): void
    {
        $this->expectException(DomainValidationException::class);
        new ${m.pascal}Aggregate('');
    }
${m.commands.map(c => `
    public function test_${c.snake}_records_event_and_bumps_the_version(): void
    {
        $aggregate = new ${m.pascal}Aggregate('agg-1');
        $event = $aggregate->${c.method}(new ${m.pascal}Command('agg-1'));
        self::assertSame(${m.pascal}EventType::${c.event}, $event->type);
        self::assertSame(1, $event->version);
        self::assertSame(1, $aggregate->version());
        self::assertCount(1, $aggregate->pendingEvents());
    }

    public function test_${c.snake}_rejects_a_command_without_id(): void
    {
        $aggregate = new ${m.pascal}Aggregate('agg-1');
        try {
            $aggregate->${c.method}(new ${m.pascal}Command(''));
            self::fail('Expected DomainValidationException');
        } catch (DomainValidationException) {
            self::assertSame([], $aggregate->pendingEvents());
        }
    }`).join('\n')}
}
`
    },
    {
      filename: `tests/Feature/${m.pascal}ApiTest.php`,
      content: `<?php

declare(strict_types=1);

namespace Tests\\Feature;

use Tests\\TestCase;

final class ${m.pascal}ApiTest extends TestCase
{
    public function test_health_endpoint(): void
    {
        $this->get('/up')->assertOk();
    }

    public function test_executes_a_domain_command(): void
    {
        $this->postJson('/api/v1/${m.kebab}/agg-api/${first.snake}', ['source' => 'api-test'])
            ->assertCreated()
            ->assertExactJson(['type' => '${first.event}', 'aggregateId' => 'agg-api', 'version' => 1]);
    }

    public function test_unknown_command_returns_404(): void
    {
        $this->postJson('/api/v1/${m.kebab}/agg-api/does_not_exist')->assertNotFound();
    }
}
`
    },
    {
      filename: `features/bootstrap/${m.pascal}Context.php`,
      content: `<?php

declare(strict_types=1);

use App\\Domain\\${m.pascal}\\${m.pascal}Aggregate;
use Behat\\Behat\\Context\\Context;
use Behat\\Behat\\Tester\\Exception\\PendingException;

/**
 * Behat context for "${m.feature}" (generated by gherkin-ai).
 * Steps are wired to the feature and pending until implemented (non-strict runs do not fail).
 */
final class ${m.pascal}Context implements Context
{
    private ${m.pascal}Aggregate $aggregate;

    /** @BeforeScenario */
    public function resetAggregate(): void
    {
        $this->aggregate = new ${m.pascal}Aggregate('scenario-aggregate');
    }
${m.steps.map(s => `
    /**
     * @${s.keyword} /${stepRegex(s.text).replace(/\*\//g, '*\\/')}/
     */
    public function ${phpMethod(s.id)}(): void
    {
        // Pending: drive $this->aggregate (or the HTTP API) and assert the outcome.
        throw new PendingException();
    }`).join('\n')}
}
`
    }
  ];
}

export function renderLaravelSkeleton(m: DomainModel, name: string): PhpFile[] {
  const keep = (dir: string): PhpFile => ({ filename: `${dir}/.gitignore`, content: '*\n!.gitignore\n' });
  return [
    {
      filename: 'composer.json',
      content: JSON.stringify({
        name: `app/${name}`,
        type: 'project',
        require: { php: '^8.3', 'laravel/framework': '^13.17', ...PHP_RUNTIME_REQUIRE },
        'require-dev': { 'phpunit/phpunit': '^12.5', 'behat/behat': '^3.34' },
        autoload: { 'psr-4': { 'App\\': 'app/' } },
        'autoload-dev': { 'psr-4': { 'Tests\\': 'tests/' } },
        // php-http/discovery (pulled in by OpenTelemetry) is a Composer plugin; it is not needed to run.
        config: { 'optimize-autoloader': true, 'sort-packages': true, 'allow-plugins': { 'php-http/discovery': false } },
        'minimum-stability': 'stable',
        'prefer-stable': true
      }, null, 2) + '\n'
    },
    {
      filename: 'artisan',
      content: `#!/usr/bin/env php
<?php

use Symfony\\Component\\Console\\Input\\ArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$status = (require_once __DIR__.'/bootstrap/app.php')->handleCommand(new ArgvInput);

exit($status);
`
    },
    {
      filename: 'bootstrap/app.php',
      content: `<?php

use Illuminate\\Foundation\\Application;
use Illuminate\\Foundation\\Configuration\\Exceptions;
use Illuminate\\Foundation\\Configuration\\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        api: __DIR__.'/../routes/api.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        //
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();
`
    },
    keep('bootstrap/cache'),
    {
      filename: 'public/index.php',
      content: `<?php

use Illuminate\\Http\\Request;

define('LARAVEL_START', microtime(true));

require __DIR__.'/../vendor/autoload.php';

(require_once __DIR__.'/../bootstrap/app.php')->handleRequest(Request::capture());
`
    },
    {
      filename: 'routes/api.php',
      content: `<?php

use App\\Http\\Controllers\\${m.pascal}Controller;
use Illuminate\\Support\\Facades\\Route;

Route::post('/v1/${m.kebab}/{id}/{command}', [${m.pascal}Controller::class, 'execute']);
`
    },
    keep('storage/app'),
    keep('storage/framework/cache'),
    keep('storage/framework/sessions'),
    keep('storage/framework/views'),
    keep('storage/logs'),
    {
      filename: 'phpunit.xml',
      content: `<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         colors="true">
    <testsuites>
        <testsuite name="Unit">
            <directory>tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory>tests/Feature</directory>
        </testsuite>
        <!-- Runtime integration tests (group "integration") need DATABASE_URL / AMQP_URL. -->
        <testsuite name="Integration">
            <directory>tests/Integration</directory>
        </testsuite>
    </testsuites>
    <source>
        <include>
            <directory>app</directory>
        </include>
    </source>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="APP_KEY" value="base64:2fl+Ktvkfl+Fuz4Qp/A75G2RTiWVA/ZoKZvp6fiiM10="/>
        <env name="CACHE_STORE" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
    </php>
</phpunit>
`
    },
    {
      filename: 'behat.yml',
      content: `default:
  autoload:
    '': '%paths.base%/features/bootstrap'
  suites:
    default:
      paths: ['%paths.base%/features']
      contexts: ['${m.pascal}Context']
`
    }
  ];
}
