/* ==========================================================================
   gherkin-ai-cli - Python domain kernel (pytest, pytest-bdd)
   Shared by the FastAPI and Django presets.
   ========================================================================== */

import { DomainModel } from './domain-model';

export interface PyFile {
  filename: string;
  content: string;
}

const py = (s: string) => JSON.stringify(s); // JSON string literals are valid Python string literals

export function renderPyKernel(m: DomainModel, pkg = 'app'): PyFile[] {
  return [
    { filename: `${pkg}/domain/__init__.py`, content: `from .${m.snake} import *  # noqa: F401,F403\n` },
    {
      filename: `${pkg}/domain/${m.snake}.py`,
      content: `"""Domain kernel for ${py(m.feature)} (generated by gherkin-ai).

Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List

__all__ = [
    "DomainValidationError",
    "${m.pascal}State",
    "${m.pascal}EventType",
    "${m.pascal}Command",
    "${m.pascal}DomainEvent",
    "${m.pascal}Aggregate",
]


class DomainValidationError(ValueError):
    """Raised when a command or aggregate violates a domain invariant."""


class ${m.pascal}State(str, Enum):
${m.states.map(s => `    ${s} = ${py(s)}`).join('\n')}


class ${m.pascal}EventType(str, Enum):
${m.events.map(e => `    ${e} = ${py(e)}`).join('\n')}


@dataclass(frozen=True)
class ${m.pascal}Command:
    id: str
    payload: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ${m.pascal}DomainEvent:
    type: ${m.pascal}EventType
    aggregate_id: str
    version: int
    occurred_on: datetime
    payload: Dict[str, Any]


class ${m.pascal}Aggregate:
    def __init__(self, id: str) -> None:
        if not id or not id.strip():
            raise DomainValidationError("${m.pascal} id is required")
        self.id = id
        self.state = ${m.pascal}State.${m.initialState}
        self.version = 0
        self._pending_events: List[${m.pascal}DomainEvent] = []

    @property
    def pending_events(self) -> List[${m.pascal}DomainEvent]:
        """Events recorded since the aggregate was loaded (to be saved via the outbox)."""
        return list(self._pending_events)
${m.commands.map(c => `
    def ${c.snake}(self, command: ${m.pascal}Command) -> ${m.pascal}DomainEvent:
        self._assert_valid(command)
        return self._record(${m.pascal}EventType.${c.event}, command.payload)`).join('\n')}

    def _assert_valid(self, command: ${m.pascal}Command) -> None:
        if command is None or not command.id or not command.id.strip():
            raise DomainValidationError("Command id is required")
        if command.id != self.id:
            raise DomainValidationError(f"Command targets {command.id}, not {self.id}")

    def _record(self, type_: ${m.pascal}EventType, payload: Dict[str, Any]) -> ${m.pascal}DomainEvent:
        self.version += 1
        event = ${m.pascal}DomainEvent(type_, self.id, self.version, datetime.now(timezone.utc), dict(payload or {}))
        self._pending_events.append(event)
        return event
`
    }
  ];
}

export function renderPyKernelTests(m: DomainModel, pkg = 'app'): PyFile[] {
  return [{
    filename: `tests/test_${m.snake}_aggregate.py`,
    content: `import pytest

from ${pkg}.domain import (
    DomainValidationError,
    ${m.pascal}Aggregate,
    ${m.pascal}Command,
    ${m.pascal}EventType,
    ${m.pascal}State,
)


def test_starts_in_the_initial_state_with_no_events():
    aggregate = ${m.pascal}Aggregate("agg-1")
    assert aggregate.state == ${m.pascal}State.${m.initialState}
    assert aggregate.version == 0
    assert aggregate.pending_events == []


def test_rejects_an_aggregate_without_id():
    with pytest.raises(DomainValidationError):
        ${m.pascal}Aggregate("")
${m.commands.map(c => `

def test_${c.snake}_records_event_and_bumps_the_version():
    aggregate = ${m.pascal}Aggregate("agg-1")
    event = aggregate.${c.snake}(${m.pascal}Command("agg-1", {"source": "test"}))
    assert event.type == ${m.pascal}EventType.${c.event}
    assert event.version == 1
    assert aggregate.version == 1
    assert aggregate.pending_events == [event]


def test_${c.snake}_rejects_a_command_without_id():
    aggregate = ${m.pascal}Aggregate("agg-1")
    with pytest.raises(DomainValidationError):
        aggregate.${c.snake}(${m.pascal}Command(""))
    assert aggregate.pending_events == []`).join('\n')}
`
  }];
}

/** pytest-bdd binding: every scenario of the feature becomes a test; steps skip until implemented. */
export function renderPytestBdd(m: DomainModel, featureFile: string, pkg = 'app'): PyFile[] {
  return [{
    filename: `tests/bdd/test_${m.snake}_scenarios.py`,
    content: `"""pytest-bdd step definitions for ${py(m.feature)} (generated by gherkin-ai).

Every scenario in the feature runs as a test. Steps are pending: they skip until implemented.
"""
import pytest
from pytest_bdd import given, scenarios, then, when

from ${pkg}.domain import ${m.pascal}Aggregate

scenarios(${py(featureFile)})


@pytest.fixture
def aggregate():
    return ${m.pascal}Aggregate("scenario-aggregate")
${m.steps.map(s => `

@${s.keyword.toLowerCase()}(${py(s.text)})
def ${s.id}(aggregate):
    # Pending: drive the aggregate (or the HTTP API) and assert the outcome.
    pytest.skip("Pending step: implement it, then remove this line")`).join('\n')}
`
  }];
}

/** Imports every generated module so a broken import fails the build (Python's "compile" check). */
export function renderPyImportSmokeTest(modules: string[]): PyFile {
  return {
    filename: 'tests/test_generated_modules_import.py',
    content: `import importlib

import pytest

GENERATED_MODULES = ${JSON.stringify(modules, null, 4).replace(/\n\]/, ',\n]')}


@pytest.mark.parametrize("module", GENERATED_MODULES)
def test_generated_module_imports(module):
    importlib.import_module(module)
`
  };
}

/** Converts generated file paths (app/x/y.py) into importable module names. */
export function pyModulesOf(filenames: string[]): string[] {
  return filenames
    .filter(f => f.endsWith('.py') && !f.startsWith('tests/'))
    .map(f => f.replace(/\.py$/, '').replace(/\/__init__$/, '').replace(/\//g, '.'))
    .filter((m, i, a) => a.indexOf(m) === i)
    .sort();
}

/** Adds an empty __init__.py to every package directory of the given files that lacks one. */
export function withInitFiles(files: PyFile[]): PyFile[] {
  const present = new Set(files.map(f => f.filename));
  const dirs = new Set<string>();
  for (const f of files) {
    if (!f.filename.endsWith('.py')) continue;
    const parts = f.filename.split('/').slice(0, -1);
    for (let i = 1; i <= parts.length; i++) dirs.add(parts.slice(0, i).join('/'));
  }
  const extra = [...dirs].filter(d => d && !present.has(`${d}/__init__.py`)).map(d => ({ filename: `${d}/__init__.py`, content: '' }));
  return [...files, ...extra];
}
