/* ==========================================================================
   gherkin-ai-cli - Ruby domain kernel (Rails 8 API, RSpec, Cucumber)
   ========================================================================== */

import { DomainModel, stepRegex, toPascal } from './domain-model';

export interface RbFile {
  filename: string;
  content: string;
}

const rbStr = (s: string) => JSON.stringify(s);

export function renderRubyKernel(m: DomainModel): RbFile[] {
  return [
    { filename: 'app/domain/domain_validation_error.rb', content: `# frozen_string_literal: true\n\nclass DomainValidationError < StandardError; end\n` },
    {
      filename: `app/domain/${m.snake}_command.rb`,
      content: `# frozen_string_literal: true\n\n${m.pascal}Command = Data.define(:id, :payload) do\n  def initialize(id:, payload: {})\n    super\n  end\nend\n`
    },
    {
      filename: `app/domain/${m.snake}_domain_event.rb`,
      content: `# frozen_string_literal: true\n\n${m.pascal}DomainEvent = Data.define(:type, :aggregate_id, :version, :occurred_on, :payload)\n`
    },
    {
      filename: `app/domain/${m.snake}_aggregate.rb`,
      content: `# frozen_string_literal: true

# Domain kernel for ${rbStr(m.feature)} (generated by gherkin-ai).
# Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
class ${m.pascal}Aggregate
  STATES = %w[${m.states.join(' ')}].freeze
  EVENT_TYPES = %w[${m.events.join(' ')}].freeze

  attr_reader :id, :state, :version

  def initialize(id)
    raise DomainValidationError, "${m.pascal} id is required" if id.to_s.strip.empty?

    @id = id
    @state = ${rbStr(m.initialState)}
    @version = 0
    @pending_events = []
  end

  # Events recorded since the aggregate was loaded (to be saved via the outbox).
  def pending_events
    @pending_events.dup
  end
${m.commands.map(c => `
  def ${c.snake}(command)
    assert_valid!(command)
    record(${rbStr(c.event)}, command.payload)
  end`).join('\n')}

  private

  def assert_valid!(command)
    raise DomainValidationError, 'Command id is required' if command.nil? || command.id.to_s.strip.empty?
    raise DomainValidationError, "Command targets #{command.id}, not #{id}" unless command.id == id
  end

  def record(type, payload)
    @version += 1
    event = ${m.pascal}DomainEvent.new(type: type, aggregate_id: id, version: @version, occurred_on: Time.now.utc, payload: payload || {})
    @pending_events << event
    event
  end
end
`
    }
  ];
}

export function renderRailsApp(m: DomainModel, appModule: string): RbFile[] {
  const first = m.commands[0];
  return [
    {
      filename: 'Gemfile',
      content: `source "https://rubygems.org"

ruby ">= 3.2"

gem "rails", "~> 8.0.0"
gem "puma", ">= 6.0"

group :development, :test do
  gem "rspec-rails", "~> 7.1"
end

group :test do
  gem "cucumber", "~> 9.2"
  gem "rack-test", "~> 2.1"
end
`
    },
    {
      filename: 'config/boot.rb',
      content: `ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)\n\nrequire "bundler/setup"\n`
    },
    {
      filename: 'config/application.rb',
      content: `require_relative "boot"

# API-only app without a database: load just the frameworks the generated code uses.
require "rails"
require "action_controller/railtie"

Bundler.require(*Rails.groups)

module ${appModule}
  class Application < Rails::Application
    config.load_defaults 8.0
    config.api_only = true
    config.eager_load = ENV["RAILS_ENV"] == "production"
    config.secret_key_base = ENV.fetch("SECRET_KEY_BASE", "dev-secret-change-me")
    config.hosts.clear if Rails.env.test?
  end
end
`
    },
    { filename: 'config/environment.rb', content: `require_relative "application"\n\nRails.application.initialize!\n` },
    {
      filename: 'config/routes.rb',
      content: `Rails.application.routes.draw do
  get "health", to: "${m.snake}#health"
  post "api/v1/${m.kebab}/:id/:command", to: "${m.snake}#execute"
end
`
    },
    { filename: 'config.ru', content: `require_relative "config/environment"\n\nrun Rails.application\n` },
    { filename: 'Rakefile', content: `require_relative "config/application"\n\nRails.application.load_tasks\n` },
    {
      filename: 'bin/rails',
      content: `#!/usr/bin/env ruby\nAPP_PATH = File.expand_path("../config/application", __dir__)\nrequire_relative "../config/boot"\nrequire "rails/commands"\n`
    },
    { filename: 'app/controllers/application_controller.rb', content: `class ApplicationController < ActionController::API\nend\n` },
    {
      filename: `app/controllers/${m.snake}_controller.rb`,
      content: `# frozen_string_literal: true

class ${m.pascal}Controller < ApplicationController
  COMMANDS = %w[${m.commands.map(c => c.snake).join(' ')}].freeze

  def health
    render json: { status: "ok" }
  end

  def execute
    command = params[:command]
    return render(json: { detail: "Unknown command #{command}" }, status: :not_found) unless COMMANDS.include?(command)

    # In-memory aggregate: replace with a repository + outbox.
    aggregate = ${m.pascal}Aggregate.new(params[:id])
    payload = params.to_unsafe_h.except("controller", "action", "id", "command", "${m.snake}")
    event = aggregate.public_send(command, ${m.pascal}Command.new(id: params[:id], payload: payload))
    render json: { type: event.type, aggregateId: event.aggregate_id, version: event.version }, status: :created
  rescue DomainValidationError => e
    render json: { detail: e.message }, status: :unprocessable_entity
  end
end
`
    },
    { filename: '.rspec', content: `--require rails_helper\n--format progress\n` },
    {
      filename: 'spec/rails_helper.rb',
      content: `ENV["RAILS_ENV"] ||= "test"
require_relative "../config/environment"
require "rspec/rails"

RSpec.configure do |config|
  config.infer_spec_type_from_file_location!
end
`
    },
    {
      filename: `spec/domain/${m.snake}_aggregate_spec.rb`,
      content: `RSpec.describe ${m.pascal}Aggregate do
  subject(:aggregate) { described_class.new("agg-1") }

  it "starts in the initial state with no events" do
    expect(aggregate.state).to eq(${rbStr(m.initialState)})
    expect(aggregate.version).to eq(0)
    expect(aggregate.pending_events).to be_empty
  end

  it "rejects an aggregate without id" do
    expect { described_class.new("") }.to raise_error(DomainValidationError)
  end
${m.commands.map(c => `
  it "${c.snake} records ${c.event} and bumps the version" do
    event = aggregate.${c.snake}(${m.pascal}Command.new(id: "agg-1"))
    expect(event.type).to eq(${rbStr(c.event)})
    expect(event.version).to eq(1)
    expect(aggregate.version).to eq(1)
    expect(aggregate.pending_events).to eq([event])
  end

  it "${c.snake} rejects a command without id" do
    expect { aggregate.${c.snake}(${m.pascal}Command.new(id: "")) }.to raise_error(DomainValidationError)
    expect(aggregate.pending_events).to be_empty
  end`).join('\n')}
end
`
    },
    {
      filename: `spec/requests/${m.snake}_spec.rb`,
      content: `RSpec.describe "${m.pascal} API", type: :request do
  it "reports health" do
    get "/health"
    expect(response).to have_http_status(:ok)
    expect(response.parsed_body).to eq("status" => "ok")
  end

  it "executes a domain command and returns the event" do
    post "/api/v1/${m.kebab}/agg-api/${first.snake}", params: { source: "api-test" }, as: :json
    expect(response).to have_http_status(:created)
    expect(response.parsed_body).to eq("type" => ${rbStr(first.event)}, "aggregateId" => "agg-api", "version" => 1)
  end

  it "returns 404 for unknown commands" do
    post "/api/v1/${m.kebab}/agg-api/does_not_exist"
    expect(response).to have_http_status(:not_found)
  end
end
`
    },
    { filename: 'cucumber.yml', content: `# Pending steps are reported without failing the run.\ndefault: --no-strict --publish-quiet --format progress\n` },
    {
      filename: 'features/support/env.rb',
      content: `ENV["RAILS_ENV"] ||= "test"\nrequire_relative "../../config/environment"\n`
    },
    {
      filename: `features/step_definitions/${m.snake}_steps.rb`,
      content: `# Step definitions for ${rbStr(m.feature)} (generated by gherkin-ai): wired to the feature, pending until implemented.

Before do
  @aggregate = ${m.pascal}Aggregate.new("scenario-aggregate")
end
${m.steps.map(s => `
${toPascal(s.keyword)}(/${stepRegex(s.text).replace(/\//g, '\\/')}/) do
  # Pending: drive @aggregate (or the HTTP API) and assert the outcome.
  pending
end`).join('\n')}
`
    }
  ];
}
