/* ==========================================================================
   gherkin-ai-cli - Rust domain kernel (Axum 0.7, tokio, cargo test)
   ========================================================================== */

import { DomainModel, stepRegex, toPascal } from './domain-model';

export interface RsFile {
  filename: string;
  content: string;
}

const rsStr = (s: string) => JSON.stringify(s);
// Raw string literal r#"..."# so regex backslashes stay literal.
const rsRaw = (s: string) => `r#"${s.replace(/"#/g, '"\\#')}"#`;

export function renderRustProject(m: DomainModel, crate: string, featureFile: string): RsFile[] {
  const first = m.commands[0];
  return [
    {
      filename: 'Cargo.toml',
      content: `[package]
name = "${crate}"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }

[dev-dependencies]
http-body-util = "0.1"
regex = "1"
tower = { version = "0.5", features = ["util"] }
`
    },
    {
      filename: 'src/lib.rs',
      content: `//! ${m.feature} service (generated by gherkin-ai).
pub mod api;
pub mod domain;
`
    },
    {
      filename: 'src/domain.rs',
      content: `//! Domain kernel for ${rsStr(m.feature)} (generated by gherkin-ai).
//! Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
use std::collections::HashMap;
use std::time::SystemTime;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DomainValidationError(pub String);

impl std::fmt::Display for DomainValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for DomainValidationError {}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {
${m.states.map(s => `    ${toPascal(s)},`).join('\n')}
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventType {
${m.events.map(e => `    ${e},`).join('\n')}
}

impl EventType {
    pub fn as_str(&self) -> &'static str {
        match self {
${m.events.map(e => `            EventType::${e} => ${rsStr(e)},`).join('\n')}
        }
    }
}

#[derive(Debug, Clone, Default)]
pub struct Command {
    pub id: String,
    pub payload: HashMap<String, serde_json::Value>,
}

impl Command {
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into(), payload: HashMap::new() }
    }
}

#[derive(Debug, Clone)]
pub struct DomainEvent {
    pub event_type: EventType,
    pub aggregate_id: String,
    pub version: u64,
    pub occurred_on: SystemTime,
    pub payload: HashMap<String, serde_json::Value>,
}

#[derive(Debug)]
pub struct ${m.pascal}Aggregate {
    pub id: String,
    pub state: State,
    pub version: u64,
    pending_events: Vec<DomainEvent>,
}

impl ${m.pascal}Aggregate {
    pub fn new(id: impl Into<String>) -> Result<Self, DomainValidationError> {
        let id = id.into();
        if id.trim().is_empty() {
            return Err(DomainValidationError("${m.pascal} id is required".into()));
        }
        Ok(Self { id, state: State::${toPascal(m.initialState)}, version: 0, pending_events: Vec::new() })
    }

    /// Events recorded since the aggregate was loaded (to be saved via the outbox).
    pub fn pending_events(&self) -> &[DomainEvent] {
        &self.pending_events
    }
${m.commands.map(c => `
    pub fn ${c.snake}(&mut self, command: Command) -> Result<DomainEvent, DomainValidationError> {
        self.assert_valid(&command)?;
        Ok(self.record(EventType::${c.event}, command.payload))
    }`).join('\n')}

    fn assert_valid(&self, command: &Command) -> Result<(), DomainValidationError> {
        if command.id.trim().is_empty() {
            return Err(DomainValidationError("Command id is required".into()));
        }
        if command.id != self.id {
            return Err(DomainValidationError(format!("Command targets {}, not {}", command.id, self.id)));
        }
        Ok(())
    }

    fn record(&mut self, event_type: EventType, payload: HashMap<String, serde_json::Value>) -> DomainEvent {
        self.version += 1;
        let event = DomainEvent { event_type, aggregate_id: self.id.clone(), version: self.version, occurred_on: SystemTime::now(), payload };
        self.pending_events.push(event.clone());
        event
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn starts_in_the_initial_state_with_no_events() {
        let aggregate = ${m.pascal}Aggregate::new("agg-1").unwrap();
        assert_eq!(aggregate.state, State::${toPascal(m.initialState)});
        assert_eq!(aggregate.version, 0);
        assert!(aggregate.pending_events().is_empty());
    }

    #[test]
    fn rejects_an_aggregate_without_id() {
        assert!(${m.pascal}Aggregate::new("").is_err());
    }
${m.commands.map(c => `
    #[test]
    fn ${c.snake}_records_event_and_bumps_the_version() {
        let mut aggregate = ${m.pascal}Aggregate::new("agg-1").unwrap();
        let event = aggregate.${c.snake}(Command::new("agg-1")).unwrap();
        assert_eq!(event.event_type, EventType::${c.event});
        assert_eq!(event.version, 1);
        assert_eq!(aggregate.version, 1);
        assert_eq!(aggregate.pending_events().len(), 1);
    }

    #[test]
    fn ${c.snake}_rejects_a_command_without_id() {
        let mut aggregate = ${m.pascal}Aggregate::new("agg-1").unwrap();
        assert!(aggregate.${c.snake}(Command::new("")).is_err());
        assert!(aggregate.pending_events().is_empty());
    }`).join('\n')}
}
`
    },
    {
      filename: 'src/api.rs',
      content: `//! HTTP API (Axum) executing the domain kernel commands.
use axum::extract::Path;
use axum::http::StatusCode;
use axum::routing::{get, post};
use axum::{Json, Router};
use serde_json::{json, Value};

use crate::domain::{${m.pascal}Aggregate, Command};

pub fn router() -> Router {
    Router::new()
        .route("/health", get(|| async { Json(json!({ "status": "ok" })) }))
        .route("/api/v1/${m.kebab}/:id/:command", post(execute))
}

async fn execute(Path((id, command)): Path<(String, String)>, body: Option<Json<Value>>) -> (StatusCode, Json<Value>) {
    // In-memory aggregate: replace with a repository + outbox.
    let mut aggregate = match ${m.pascal}Aggregate::new(id.clone()) {
        Ok(a) => a,
        Err(e) => return (StatusCode::UNPROCESSABLE_ENTITY, Json(json!({ "detail": e.0 }))),
    };
    let payload = body
        .and_then(|Json(v)| v.as_object().cloned())
        .map(|m| m.into_iter().collect())
        .unwrap_or_default();
    let cmd = Command { id, payload };
    let result = match command.as_str() {
${m.commands.map(c => `        "${c.snake}" => aggregate.${c.snake}(cmd),`).join('\n')}
        _ => return (StatusCode::NOT_FOUND, Json(json!({ "detail": format!("Unknown command {command}") }))),
    };
    match result {
        Ok(event) => (
            StatusCode::CREATED,
            Json(json!({ "type": event.event_type.as_str(), "aggregateId": event.aggregate_id, "version": event.version })),
        ),
        Err(e) => (StatusCode::UNPROCESSABLE_ENTITY, Json(json!({ "detail": e.0 }))),
    }
}
`
    },
    {
      filename: 'src/main.rs',
      content: `#[tokio::main]
async fn main() {
    let port = std::env::var("PORT").unwrap_or_else(|_| "8080".into());
    let listener = tokio::net::TcpListener::bind(format!("0.0.0.0:{port}")).await.expect("bind");
    println!("listening on :{port}");
    axum::serve(listener, ${crate}::api::router()).await.expect("server");
}
`
    },
    {
      filename: 'tests/api.rs',
      content: `use axum::body::Body;
use axum::http::{Request, StatusCode};
use http_body_util::BodyExt;
use serde_json::Value;
use tower::ServiceExt;

async fn call(method: &str, uri: &str, body: &str) -> (StatusCode, Value) {
    let req = Request::builder().method(method).uri(uri).header("content-type", "application/json").body(Body::from(body.to_string())).unwrap();
    let res = ${crate}::api::router().oneshot(req).await.unwrap();
    let status = res.status();
    let bytes = res.into_body().collect().await.unwrap().to_bytes();
    (status, serde_json::from_slice(&bytes).unwrap_or(Value::Null))
}

#[tokio::test]
async fn reports_health() {
    let (status, body) = call("GET", "/health", "").await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body["status"], "ok");
}

#[tokio::test]
async fn executes_a_domain_command() {
    let (status, body) = call("POST", "/api/v1/${m.kebab}/agg-api/${first.snake}", r#"{"source":"api-test"}"#).await;
    assert_eq!(status, StatusCode::CREATED);
    assert_eq!(body["type"], ${rsStr(first.event)});
    assert_eq!(body["version"], 1);
}

#[tokio::test]
async fn unknown_command_returns_404() {
    let (status, _) = call("POST", "/api/v1/${m.kebab}/agg-api/does_not_exist", "{}").await;
    assert_eq!(status, StatusCode::NOT_FOUND);
}
`
    },
    {
      filename: 'tests/features.rs',
      content: `//! Binds ${featureFile} to cargo test (generated by gherkin-ai).
//! Fails when a step has no definition; reports pending steps without failing.
use regex::Regex;

#[derive(PartialEq)]
enum Status {
    Pending,
    #[allow(dead_code)]
    Implemented,
}

/// (keyword, regex, status): switch a step to Implemented once it asserts real behavior.
fn step_definitions() -> Vec<(&'static str, Regex, Status)> {
    vec![
${m.steps.map(s => `        (${rsStr(s.keyword)}, Regex::new(${rsRaw(stepRegex(s.text))}).unwrap(), Status::Pending),`).join('\n')}
    ]
}

fn scenarios(source: &str) -> Vec<(String, Vec<(String, String)>)> {
    let mut out: Vec<(String, Vec<(String, String)>)> = Vec::new();
    let mut last = "Given".to_string();
    for line in source.lines().map(str::trim) {
        if let Some(name) = line.strip_prefix("Scenario:").or_else(|| line.strip_prefix("Scenario Outline:")) {
            out.push((name.trim().to_string(), Vec::new()));
            last = "Given".into();
            continue;
        }
        for kw in ["Given", "When", "Then", "And", "But"] {
            if let Some(text) = line.strip_prefix(kw).and_then(|t| t.strip_prefix(' ')) {
                if kw != "And" && kw != "But" {
                    last = kw.to_string();
                }
                if let Some((_, steps)) = out.last_mut() {
                    steps.push((last.clone(), text.trim().to_string()));
                }
                break;
            }
        }
    }
    out
}

#[test]
fn every_feature_step_is_defined() {
    let source = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/${featureFile}")).expect("feature file");
    let defs = step_definitions();
    let mut undefined = Vec::new();
    let mut pending = 0;
    for (scenario, steps) in scenarios(&source) {
        for (kw, text) in steps {
            match defs.iter().find(|(k, re, _)| *k == kw && re.is_match(&text)) {
                None => undefined.push(format!("{scenario}: {kw} {text}")),
                Some((_, _, Status::Pending)) => pending += 1,
                Some(_) => {}
            }
        }
    }
    assert!(undefined.is_empty(), "Undefined steps:\\n{}", undefined.join("\\n"));
    if pending > 0 {
        println!("{pending} pending step(s) in ${featureFile}");
    }
}
`
    }
  ];
}
