/* ==========================================================================
   gherkin-ai-cli - TypeScript domain kernel (NestJS / Express / Node)
   ========================================================================== */

import { DomainModel, cucumberExpression } from './domain-model';

export interface GeneratedFile {
  filename: string;
  content: string;
}

const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

export function renderTsAggregate(m: DomainModel): string {
  const stateUnion = m.states.map(s => q(s)).join(' | ');
  const eventUnion = m.events.map(e => q(e)).join(' | ');
  return `// Domain kernel for "${m.feature}" (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.

export type ${m.pascal}State = ${stateUnion};
export type ${m.pascal}EventType = ${eventUnion};

export interface ${m.pascal}DomainEvent {
  type: ${m.pascal}EventType;
  aggregateId: string;
  version: number;
  occurredOn: Date;
  payload: Record<string, unknown>;
}

export interface ${m.pascal}Command {
  /** Identifier of the aggregate the command targets. */
  id: string;
  payload?: Record<string, unknown>;
}

export class DomainValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'DomainValidationError';
  }
}

export class ${m.pascal}Aggregate {
  private _state: ${m.pascal}State = ${q(m.initialState)};
  private _version = 0;
  private readonly _events: ${m.pascal}DomainEvent[] = [];

  constructor(public readonly id: string) {
    if (!id || !id.trim()) throw new DomainValidationError('${m.pascal} id is required');
  }

  get state(): ${m.pascal}State {
    return this._state;
  }

  get version(): number {
    return this._version;
  }

  /** Events recorded since the aggregate was loaded (to be saved via an outbox). */
  get pendingEvents(): readonly ${m.pascal}DomainEvent[] {
    return this._events;
  }
${m.commands.map(c => `
  ${c.method}(command: ${m.pascal}Command): ${m.pascal}DomainEvent {
    this.assertValid(command);
    return this.record(${q(c.event)}, command.payload ?? {});
  }`).join('\n')}

  private assertValid(command: ${m.pascal}Command): void {
    if (!command || !command.id || !command.id.trim()) throw new DomainValidationError('Command id is required');
    if (command.id !== this.id) throw new DomainValidationError(\`Command targets \${command.id}, not \${this.id}\`);
  }

  private record(type: ${m.pascal}EventType, payload: Record<string, unknown>): ${m.pascal}DomainEvent {
    this._version += 1;
    const event: ${m.pascal}DomainEvent = { type, aggregateId: this.id, version: this._version, occurredOn: new Date(), payload };
    this._events.push(event);
    return event;
  }
}
`;
}

export function renderTsAggregateSpec(m: DomainModel, importPath: string): string {
  return `import { ${m.pascal}Aggregate, DomainValidationError } from '${importPath}';

describe('${m.pascal}Aggregate', () => {
  it('starts in the initial state with no events', () => {
    const aggregate = new ${m.pascal}Aggregate('agg-1');
    expect(aggregate.state).toBe(${q(m.initialState)});
    expect(aggregate.version).toBe(0);
    expect(aggregate.pendingEvents).toHaveLength(0);
  });

  it('rejects an aggregate without id', () => {
    expect(() => new ${m.pascal}Aggregate('')).toThrow(DomainValidationError);
  });
${m.commands.map(c => `
  it('${c.method} records ${c.event} and bumps the version', () => {
    const aggregate = new ${m.pascal}Aggregate('agg-1');
    const event = aggregate.${c.method}({ id: 'agg-1', payload: { source: 'test' } });
    expect(event.type).toBe(${q(c.event)});
    expect(event.version).toBe(1);
    expect(aggregate.version).toBe(1);
    expect(aggregate.pendingEvents).toEqual([event]);
  });

  it('${c.method} rejects a command without id', () => {
    const aggregate = new ${m.pascal}Aggregate('agg-1');
    expect(() => aggregate.${c.method}({ id: '' })).toThrow(DomainValidationError);
    expect(aggregate.pendingEvents).toHaveLength(0);
  });`).join('\n')}
});
`;
}

/** cucumber-js step definitions bound to the feature; every step starts as pending. */
export function renderCucumberJsSteps(m: DomainModel, aggregateImport: string): string {
  return `// cucumber-js step definitions for "${m.feature}" (generated by gherkin-ai).
// Each step is wired to the feature and returns 'pending' until implemented.
import { Given, When, Then, Before } from '@cucumber/cucumber';
import { ${m.pascal}Aggregate } from '${aggregateImport}';

interface World {
  aggregate?: ${m.pascal}Aggregate;
}

Before(function (this: World) {
  this.aggregate = new ${m.pascal}Aggregate('scenario-aggregate');
});
${m.steps.map(s => `
${s.keyword}(${q(cucumberExpression(s.text))}, function (this: World) {
  // Pending (${s.id}): drive this.aggregate (or the HTTP API) and assert the outcome.
  return 'pending';
});`).join('\n')}
`;
}

export function renderCucumberJsConfig(stepsGlob: string): string {
  return `// Pending steps are reported but do not fail the run (strict: false).
module.exports = {
  default: {
    paths: ['features/**/*.feature'],
    requireModule: ['ts-node/register'],
    require: ['${stepsGlob}'],
    strict: false,
    format: ['progress']
  }
};
`;
}

export function renderJestConfig(roots: string[]): string {
  return `/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ${JSON.stringify(roots)},
  testMatch: ['**/*.spec.ts']
};
`;
}

export function renderTsConfigs(): GeneratedFile[] {
  return [
    {
      filename: 'tsconfig.json',
      content: JSON.stringify({
        compilerOptions: {
          target: 'ES2021', module: 'commonjs', moduleResolution: 'node', outDir: 'dist', rootDir: '.',
          strict: true, esModuleInterop: true, experimentalDecorators: true, emitDecoratorMetadata: true,
          skipLibCheck: true, resolveJsonModule: true, types: ['node', 'jest']
        },
        include: ['src/**/*.ts', 'test/**/*.ts', 'contracts.ts']
      }, null, 2) + '\n'
    },
    {
      filename: 'tsconfig.build.json',
      content: JSON.stringify({ extends: './tsconfig.json', exclude: ['node_modules', 'dist', 'test', '**/*.spec.ts'] }, null, 2) + '\n'
    }
  ];
}
