/* ==========================================================================
   gherkin-ai-cli - Project upgrade analysis (`ghk upgrade`)

   Read-only checks over a project directory:
   - which CLI version generated its files (the "Generated by" headers),
   - whether its gherkin-ai.config.json validates and what can be fixed,
   - CI scripts and MCP client configs that use flags or behavior the
     running CLI changed (see docs/MIGRATION-3.0.md),
   - legacy files 3.x no longer reads.
   Applying the result lives in src/commands/upgrade.ts.
   ========================================================================== */

import crypto from 'crypto';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { partialConfigSchema } from '../config/schema';
import { CONFIG_SCHEMA_ID } from '../config/json-schema';

export type FindingSeverity = 'required' | 'recommended' | 'info';
export type FindingArea = 'config' | 'generated' | 'automation' | 'mcp' | 'legacy' | 'cli';

export interface UpgradeFinding {
  id: string;
  area: FindingArea;
  severity: FindingSeverity;
  /** auto: `ghk upgrade --apply` handles it; manual: needs a person; none: informational. */
  fix: 'auto' | 'manual' | 'none';
  message: string;
  hint?: string;
  file?: string;
  line?: number;
}

// ---------------------------------------------------------------------------
// Versions
// ---------------------------------------------------------------------------

/** Compares semver strings; a prerelease sorts before its release (3.0.0-beta.1 < 3.0.0). */
export function compareVersions(a: string, b: string): number {
  const parse = (v: string) => {
    const [core, pre] = v.replace(/^v/, '').split('-', 2);
    return { nums: core.split('.').map(n => parseInt(n, 10) || 0), pre };
  };
  const x = parse(a);
  const y = parse(b);
  for (let i = 0; i < 3; i++) {
    const d = (x.nums[i] ?? 0) - (y.nums[i] ?? 0);
    if (d) return Math.sign(d);
  }
  if (x.pre === y.pre) return 0;
  if (!x.pre) return 1;
  if (!y.pre) return -1;
  return x.pre.localeCompare(y.pre, 'en', { numeric: true });
}

const majorOf = (v: string) => parseInt(v.replace(/^v/, ''), 10) || 0;

const GENERATED_HEADER = /Generated by gherkin-ai(?: CLI)? v(\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?)/;
const SKIP_DIRS = new Set(['node_modules', '.git', 'dist', 'build', 'bin', 'obj', 'target', '_build', 'deps', 'vendor', '.dart_tool', '.next', 'coverage']);

export interface GeneratedVersionInfo {
  /** Oldest CLI version found in a generated header. */
  oldest?: string;
  newest?: string;
  /** Files carrying a header, relative to the scanned directory (posix separators). */
  files: string[];
}

/** Reads the "Generated by gherkin-ai CLI vX" headers under `dir` (first 4 KB of each file). */
export function detectGeneratedVersion(dir: string, maxFiles = 2000): GeneratedVersionInfo {
  const versions: string[] = [];
  const files: string[] = [];
  let seen = 0;
  const walk = (current: string) => {
    let entries: fs.Dirent[];
    try { entries = fs.readdirSync(current, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      if (seen >= maxFiles) return;
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) {
        if (!SKIP_DIRS.has(entry.name)) walk(full);
        continue;
      }
      if (!entry.isFile()) continue;
      seen++;
      const version = readHeaderVersion(full);
      if (version) {
        versions.push(version);
        files.push(path.relative(dir, full).split(path.sep).join('/'));
      }
    }
  };
  if (fs.existsSync(dir)) walk(dir);
  const sorted = [...new Set(versions)].sort(compareVersions);
  return { oldest: sorted[0], newest: sorted[sorted.length - 1], files };
}

export function readHeaderVersion(file: string): string | undefined {
  let fd: number | undefined;
  try {
    fd = fs.openSync(file, 'r');
    const buf = Buffer.alloc(4096);
    const n = fs.readSync(fd, buf, 0, buf.length, 0);
    return GENERATED_HEADER.exec(buf.subarray(0, n).toString('utf8'))?.[1];
  } catch {
    return undefined;
  } finally {
    if (fd !== undefined) fs.closeSync(fd);
  }
}

export function generatedFindings(info: GeneratedVersionInfo, cliVersion: string, outputDir: string): UpgradeFinding[] {
  if (!info.oldest) {
    return [{ id: 'generated.none', area: 'generated', severity: 'info', fix: 'none', message: `No files generated by gherkin-ai were found in ${outputDir}.` }];
  }
  if (majorOf(info.oldest) < majorOf(cliVersion)) {
    return [{
      id: 'generated.regenerate',
      area: 'generated',
      severity: 'required',
      fix: 'auto',
      message: `${info.files.length} generated file(s) come from v${info.oldest}${info.newest !== info.oldest ? `–v${info.newest}` : ''}; v${cliVersion} generates complete, buildable projects with a different layout.`,
      hint: 'Regenerate on a separate branch and review the diff (`ghk upgrade --apply`).'
    }];
  }
  if (compareVersions(info.oldest, cliVersion) < 0) {
    return [{ id: 'generated.refresh', area: 'generated', severity: 'recommended', fix: 'auto', message: `Generated files come from v${info.oldest}; regenerating picks up fixes from v${cliVersion}.` }];
  }
  return [{ id: 'generated.current', area: 'generated', severity: 'info', fix: 'none', message: `Generated files are up to date (v${info.newest}).` }];
}

// ---------------------------------------------------------------------------
// Project configuration
// ---------------------------------------------------------------------------

export interface ConfigCheck {
  findings: UpgradeFinding[];
  /** The config with automatic fixes applied, when there is anything to fix. */
  fixed?: Record<string, unknown>;
}

export function checkProjectConfig(raw: unknown, file: string): ConfigCheck {
  const findings: UpgradeFinding[] = [];
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    findings.push({ id: 'config.invalid-json', area: 'config', severity: 'required', fix: 'manual', file, message: 'gherkin-ai.config.json must contain a JSON object.' });
    return { findings };
  }
  let config = raw as Record<string, unknown>;
  let changed = false;

  if (!('$schema' in config)) {
    // First key, so editors pick it up.
    config = { $schema: CONFIG_SCHEMA_ID, ...config };
    changed = true;
    findings.push({ id: 'config.schema-ref', area: 'config', severity: 'recommended', fix: 'auto', file, message: 'Add "$schema" so editors validate and autocomplete the config.' });
  }

  const known = new Set([...Object.keys(partialConfigSchema.shape), '$schema']);
  for (const key of Object.keys(config)) {
    if (!known.has(key)) {
      findings.push({ id: `config.unknown.${key}`, area: 'config', severity: 'recommended', fix: 'manual', file, message: `Unknown key "${key}" is ignored by v3.`, hint: 'Remove it or move it to the documented key (`ghk config schema`).' });
    }
  }

  const result = partialConfigSchema.safeParse(config);
  if (!result.success) {
    for (const issue of result.error.issues) {
      findings.push({ id: `config.invalid.${issue.path.join('.') || 'root'}`, area: 'config', severity: 'required', fix: 'manual', file, message: `${issue.path.join('.') || '(root)'}: ${issue.message}` });
    }
  }

  const llm = config.llm as Record<string, unknown> | undefined;
  if (typeof llm?.model === 'string' && /^(claude-(instant|2|3)|gpt-3\.5|gpt-4-(0314|0613|32k))/.test(llm.model)) {
    findings.push({ id: 'config.retired-model', area: 'config', severity: 'recommended', fix: 'manual', file, message: `llm.model "${llm.model}" is retired or about to be retired by its provider.`, hint: 'Remove it to use the default for the provider, or pin a current model.' });
  }

  const frontend = config.frontendStack as Record<string, unknown> | undefined;
  if (String(frontend?.framework ?? '').toLowerCase() === 'angular' && /ngrx(?!-?signals)/i.test(String(frontend?.stateManagement ?? ''))) {
    findings.push({ id: 'config.angular-ngrx-store', area: 'config', severity: 'info', fix: 'none', file, message: 'The classic NgRx store mode was removed; Angular projects are generated with NgRx Signals.' });
  }

  if (findings.every(f => f.severity === 'info')) {
    findings.push({ id: 'config.valid', area: 'config', severity: 'info', fix: 'none', file, message: 'The project configuration validates against the v3 schema.' });
  }
  return { findings, fixed: changed ? config : undefined };
}

// ---------------------------------------------------------------------------
// CI scripts and package.json scripts
// ---------------------------------------------------------------------------

const AUTOMATION_FILES = [
  '.gitlab-ci.yml', 'azure-pipelines.yml', 'bitbucket-pipelines.yml', 'Jenkinsfile', '.circleci/config.yml',
  'package.json', 'Makefile', 'Taskfile.yml', 'justfile'
];
const AUTOMATION_DIRS = ['.github/workflows', '.gitlab', '.azure-pipelines', 'scripts', 'ci'];

export function listAutomationFiles(cwd: string): string[] {
  const files = AUTOMATION_FILES.map(f => path.join(cwd, f)).filter(f => fs.existsSync(f));
  for (const dir of AUTOMATION_DIRS) {
    const full = path.join(cwd, dir);
    if (!fs.existsSync(full)) continue;
    for (const entry of fs.readdirSync(full, { withFileTypes: true })) {
      if (entry.isFile() && /\.(ya?ml|sh|ps1|groovy)$/i.test(entry.name)) files.push(path.join(full, entry.name));
    }
  }
  return files;
}

interface LineRule {
  id: string;
  severity: FindingSeverity;
  test: (line: string) => boolean;
  message: string;
  hint: string;
}

const CLI_INVOCATION = /\b(ghk|gherkin-ai|gherkin-cli)(@[\w.-]+)?\s/;

const LINE_RULES: LineRule[] = [
  {
    id: 'automation.login-flags',
    severity: 'required',
    test: l => /\blogin\b/.test(l) && /--(apiKey|token|user|endpoint|server)\b/.test(l),
    message: '`ghk login --apiKey/--token/--user/--endpoint/--server` were removed.',
    hint: 'Set the provider variable (OPENAI_API_KEY, AZURE_OPENAI_API_KEY, ...) or pipe the key to `ghk login --provider <name> --api-key-stdin`.'
  },
  {
    id: 'automation.auth-alias',
    severity: 'required',
    test: l => /\s(ghk|gherkin-ai|gherkin-cli)(@[\w.-]+)?\s+auth\b(?!\s+status)/.test(` ${l}`),
    message: '`ghk auth` is no longer an alias of `login`.',
    hint: 'Use `ghk login --provider <name>`, or `ghk auth status` to inspect credentials.'
  },
  {
    id: 'automation.converge-strict',
    severity: 'recommended',
    test: l => /\bconverge\b/.test(l) && /--strict\b/.test(l),
    message: '`converge --strict` is deprecated: the threshold is always enforced.',
    hint: 'Use `ghk converge --threshold <score>` (exit code 7 below it).'
  },
  {
    id: 'automation.unattended-apply',
    severity: 'required',
    test: l => /\b(autopilot|auto|verify|v-loop)\b/.test(l) && /--apply\b/.test(l) && !/--allow-unattended-writes\b/.test(l),
    message: '`--apply` is refused in CI unless unattended writes are allowed.',
    hint: 'Add --allow-unattended-writes (or policy.allowUnattendedWrites), or drop --apply and review the generated .patch files.'
  },
  {
    id: 'automation.autopilot-dry-run',
    severity: 'info',
    test: l => /\b(autopilot|auto)\b/.test(l) && !/--apply\b/.test(l),
    message: '`ghk autopilot` is now a dry run unless --apply is passed.',
    hint: 'Add --apply if this step is expected to write files.'
  },
  {
    id: 'automation.exit-code-1',
    severity: 'recommended',
    test: l => /(\$\?|\$LASTEXITCODE|exitCode|status)\s*(-eq|==|===)\s*1\b/.test(l),
    message: 'This line compares the CLI exit code against 1; v3 uses distinct codes (2 usage, 3 config, 4 gate, 5 policy, 6 provider, 7 drift).',
    hint: 'Check for non-zero, or for the specific code (see docs/ENTERPRISE.md).'
  }
];

const OLD_NODE = /(node-version|node_version|nodejs?[_-]?version)\s*[:=]\s*\[?\s*['"]?(1[4-9]|20|21)(\.[\dx]+)*['"]?|\bimage:\s*['"]?node:(1[4-9]|20|21)\b|\bnode:(1[4-9]|20|21)(-[\w.]+)?\b/;

export function scanAutomation(cwd: string, files = listAutomationFiles(cwd)): UpgradeFinding[] {
  const findings: UpgradeFinding[] = [];
  for (const file of files) {
    let text: string;
    try { text = fs.readFileSync(file, 'utf8'); } catch { continue; }
    if (!/\b(ghk|gherkin-ai|gherkin-cli)\b/.test(text)) continue;
    const rel = path.relative(cwd, file).split(path.sep).join('/');
    const lines = text.split(/\r?\n/);
    lines.forEach((line, i) => {
      if (OLD_NODE.test(line)) {
        findings.push({ id: 'automation.node-version', area: 'automation', severity: 'required', fix: 'manual', file: rel, line: i + 1, message: 'This pipeline runs gherkin-ai on Node.js < 22; v3 requires Node.js 22.12 or later.', hint: 'Use Node 22 or 24 (e.g. actions/setup-node with node-version: 22).' });
      }
      if (!CLI_INVOCATION.test(`${line} `)) return;
      for (const rule of LINE_RULES) {
        if (rule.test(line)) findings.push({ id: rule.id, area: 'automation', severity: rule.severity, fix: 'manual', file: rel, line: i + 1, message: rule.message, hint: rule.hint });
      }
    });
  }
  return findings;
}

// ---------------------------------------------------------------------------
// MCP client configs
// ---------------------------------------------------------------------------

const MCP_CONFIGS = ['.mcp.json', '.cursor/mcp.json', '.vscode/mcp.json', '.windsurf/mcp.json'];

export function scanMcpConfigs(cwd: string, cliVersion: string): UpgradeFinding[] {
  const findings: UpgradeFinding[] = [];
  for (const rel of MCP_CONFIGS) {
    const file = path.join(cwd, rel);
    if (!fs.existsSync(file)) continue;
    let json: any;
    try { json = JSON.parse(fs.readFileSync(file, 'utf8')); } catch { continue; }
    const servers = json?.mcpServers ?? json?.servers ?? {};
    for (const [name, entry] of Object.entries<any>(servers)) {
      const cmdline = [entry?.command, ...(entry?.args ?? [])].filter(Boolean).join(' ');
      if (!/gherkin-ai|ghk\b|gherkin-cli/.test(cmdline)) continue;
      const pinned = /gherkin-ai@(\d[\w.-]*)/.exec(cmdline)?.[1];
      if (/bin[\\/]gherkin-ai\.js/.test(cmdline) && !path.isAbsolute(String(entry?.args?.[0] ?? ''))) {
        findings.push({ id: 'mcp.relative-bin', area: 'mcp', severity: 'required', fix: 'manual', file: rel, message: `MCP server "${name}" runs bin/gherkin-ai.js through a relative path, which only works from the CLI's own checkout.`, hint: 'Run `ghk mcp install` to write a pinned `npx gherkin-ai@<version> mcp` entry.' });
      } else if (!pinned || compareVersions(pinned, cliVersion) !== 0) {
        findings.push({ id: 'mcp.unpinned', area: 'mcp', severity: 'recommended', fix: 'manual', file: rel, message: `MCP server "${name}" ${pinned ? `pins v${pinned}` : 'is not pinned to a version'}.`, hint: `Run \`ghk mcp install\` to pin gherkin-ai@${cliVersion}. The v3 server is read-only unless mcp.allowWrite is set.` });
      }
    }
  }
  return findings;
}

// ---------------------------------------------------------------------------
// Legacy files
// ---------------------------------------------------------------------------

export function scanLegacyFiles(cwd: string, home = os.homedir()): UpgradeFinding[] {
  const findings: UpgradeFinding[] = [];
  const authFile = path.join(home, '.gherkin-ai', 'auth.json');
  if (fs.existsSync(authFile)) {
    let hasSecret = false;
    try {
      const auth = JSON.parse(fs.readFileSync(authFile, 'utf8'));
      hasSecret = ['apiKey', 'token', 'key', 'secret'].some(k => typeof auth?.[k] === 'string' && auth[k].length > 0);
    } catch { /* unreadable: still worth reporting */ }
    findings.push(hasSecret
      ? { id: 'legacy.auth-json-secret', area: 'legacy', severity: 'recommended', fix: 'manual', file: '~/.gherkin-ai/auth.json', message: 'auth.json contains a credential in plain text; v3 no longer reads keys from it.', hint: 'Move the key to the OS keychain with `ghk login --provider <name>`, then delete the file.' }
      : { id: 'legacy.auth-json', area: 'legacy', severity: 'info', fix: 'none', file: '~/.gherkin-ai/auth.json', message: 'auth.json is only read for a legacy `provider` value; set llm.provider in ~/.gherkin-ai/config.json and delete it.' });
  }
  if (fs.existsSync(path.join(cwd, '.gherkin-ai', 'audit.log'))) {
    findings.push({ id: 'legacy.audit-log', area: 'legacy', severity: 'info', fix: 'none', file: '.gherkin-ai/audit.log', message: 'The plain-text audit log is replaced by .gherkin-ai/audit.jsonl; archive the old file if you need it.', hint: '`ghk audit export --format csv` exports the new trail for a SIEM.' });
  }
  if (fs.existsSync(path.join(cwd, '.ghe', 'logs', 'execution.log.jsonl'))) {
    findings.push({ id: 'legacy.execution-log', area: 'legacy', severity: 'info', fix: 'none', file: '.ghe/logs/execution.log.jsonl', message: 'v3 no longer writes .ghe/logs on every run; the old log can be deleted.', hint: 'Set logging.file to keep a rotated log file.' });
  }
  return findings;
}

// ---------------------------------------------------------------------------
// Stale generated files
// ---------------------------------------------------------------------------

export interface InventoryEntry { filePath: string; checksum?: string }

export function readInventory(cwd: string): InventoryEntry[] {
  try {
    const json = JSON.parse(fs.readFileSync(path.join(cwd, '.ghe', 'inventory.json'), 'utf8'));
    return Array.isArray(json?.artifacts) ? json.artifacts.filter((a: any) => typeof a?.filePath === 'string') : [];
  } catch {
    return [];
  }
}

export const sha256 = (content: string | Buffer) => crypto.createHash('sha256').update(content).digest('hex');

export interface StaleFiles {
  /** Previously generated, no longer generated, unchanged since: safe to delete. */
  removable: string[];
  /** Previously generated, no longer generated, but edited (or unverifiable): left in place. */
  kept: string[];
}

/**
 * Files under outputDir that an earlier generation produced and the new one did not.
 * Only a checksum in the previous .ghe/inventory.json proves a file is untouched; files
 * that merely carry a "Generated by gherkin-ai" header, or that git tracks inside a
 * dedicated outputDir, are listed as kept unless `prune` is set (the upgrade runs on
 * its own branch, so a pruned file is one `git checkout` away).
 */
export function findStaleFiles(opts: {
  outputDir: string;
  generated: Set<string>;
  previousInventory: InventoryEntry[];
  headerFiles: string[];
  /** Other files in a dedicated outputDir (e.g. `git ls-files`), relative to it. */
  trackedFiles?: string[];
  prune?: boolean;
}): StaleFiles {
  const removable: string[] = [];
  const kept: string[] = [];
  const candidates = new Map<string, string | undefined>();
  for (const entry of opts.previousInventory) candidates.set(entry.filePath.replace(/\\/g, '/'), entry.checksum);
  for (const file of [...opts.headerFiles, ...(opts.trackedFiles ?? [])]) if (!candidates.has(file)) candidates.set(file, undefined);

  for (const [rel, checksum] of candidates) {
    if (opts.generated.has(rel)) continue;
    const full = path.join(opts.outputDir, rel);
    if (!fs.existsSync(full)) continue;
    if (checksum ? sha256(fs.readFileSync(full)) === checksum : opts.prune) removable.push(rel);
    else kept.push(rel);
  }
  return { removable: removable.sort(), kept: kept.sort() };
}
