import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { execFileSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';
import {
  checkProjectConfig,
  compareVersions,
  detectGeneratedVersion,
  findStaleFiles,
  generatedFindings,
  scanAutomation,
  scanLegacyFiles,
  scanMcpConfigs,
  sha256
} from '../../src/core/upgrade';
import { handleUpgradeCommand } from '../../src/commands/upgrade';
import { CONFIG_SCHEMA_ID } from '../../src/core/config/json-schema';
import { CLI_VERSION } from '../../src/version';

const write = (root: string, rel: string, content: string) => {
  const file = path.join(root, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
};
const ids = (findings: { id: string }[]) => findings.map(f => f.id);

let tmp: string;
beforeEach(() => { tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'ghk-upgrade-')); });
afterEach(() => { fs.rmSync(tmp, { recursive: true, force: true }); });

describe('upgrade analysis', () => {
  it('orders versions, prereleases before releases', () => {
    expect(compareVersions('2.6.5', '3.0.0')).toBe(-1);
    expect(compareVersions('3.0.0-beta.1', '3.0.0')).toBe(-1);
    expect(compareVersions('3.0.0-beta.10', '3.0.0-beta.2')).toBe(1);
    expect(compareVersions('v3.1.0', '3.0.9')).toBe(1);
    expect(compareVersions('3.0.0', '3.0.0')).toBe(0);
  });

  it('reads the oldest generator version from file headers and requires regeneration across majors', () => {
    write(tmp, 'out/contracts.ts', '/* Generated by gherkin-ai CLI v2.6.1 */\n');
    write(tmp, 'out/src/a.ts', '// Generated by gherkin-ai CLI v2.6.5\n');
    write(tmp, 'out/node_modules/x/index.js', '// Generated by gherkin-ai CLI v1.0.0\n');
    write(tmp, 'out/readme.md', 'hand written\n');
    const info = detectGeneratedVersion(path.join(tmp, 'out'));
    expect(info).toMatchObject({ oldest: '2.6.1', newest: '2.6.5' });
    expect(info.files.sort()).toEqual(['contracts.ts', 'src/a.ts']);
    expect(generatedFindings(info, '3.0.0', './out')[0]).toMatchObject({ id: 'generated.regenerate', severity: 'required', fix: 'auto' });
    expect(generatedFindings({ oldest: '3.0.0', newest: '3.0.0', files: ['a'] }, '3.0.0', './out')[0].id).toBe('generated.current');
  });

  it('adds $schema automatically and reports schema errors and unknown keys', () => {
    const ok = checkProjectConfig({ projectName: 'x', outputDir: './out' }, 'gherkin-ai.config.json');
    expect(Object.keys(ok.fixed!)[0]).toBe('$schema');
    expect(ok.fixed!.$schema).toBe(CONFIG_SCHEMA_ID);
    expect(ids(ok.findings)).toContain('config.schema-ref');

    const bad = checkProjectConfig({ $schema: CONFIG_SCHEMA_ID, architecture: 'spaghetti', legacyThing: 1, llm: { model: 'claude-3-opus-20240229' } }, 'c.json');
    expect(bad.fixed).toBeUndefined();
    expect(bad.findings.find(f => f.id === 'config.invalid.architecture')).toMatchObject({ severity: 'required', fix: 'manual' });
    expect(ids(bad.findings)).toEqual(expect.arrayContaining(['config.unknown.legacyThing', 'config.retired-model']));
  });

  it('flags removed flags, old Node versions and exit-code checks in CI files that call the CLI', () => {
    write(tmp, '.github/workflows/ci.yml', [
      'jobs:',
      '  spec:',
      '    steps:',
      '      - uses: actions/setup-node@v4',
      '        with:',
      '          node-version: 20',
      '      - run: npx ghk login --apiKey $KEY',
      '      - run: npx gherkin-ai converge --strict',
      '      - run: ghk autopilot --apply',
      '      - run: ghk verify; if [ $? -eq 1 ]; then exit 1; fi',
      '      - run: ghk auth status'
    ].join('\n'));
    write(tmp, '.github/workflows/unrelated.yml', 'node-version: 18\n');
    const findings = scanAutomation(tmp);
    const at = (id: string) => findings.filter(f => f.id === id).map(f => f.line);
    expect(at('automation.node-version')).toEqual([6]);
    expect(at('automation.login-flags')).toEqual([7]);
    expect(at('automation.converge-strict')).toEqual([8]);
    expect(at('automation.unattended-apply')).toEqual([9]);
    expect(at('automation.exit-code-1')).toEqual([10]);
    expect(at('automation.auth-alias')).toEqual([]);
    expect(findings.every(f => f.file === '.github/workflows/ci.yml')).toBe(true);
  });

  it('flags MCP client entries that use a relative path or are not pinned to this version', () => {
    write(tmp, '.mcp.json', JSON.stringify({ mcpServers: { a: { command: 'node', args: ['bin/gherkin-ai.js', 'mcp'] }, b: { command: 'npx', args: ['-y', 'gherkin-ai', 'mcp'] }, c: { command: 'npx', args: ['-y', `gherkin-ai@${CLI_VERSION}`, 'mcp'] }, other: { command: 'npx', args: ['some-server'] } } }));
    expect(ids(scanMcpConfigs(tmp, CLI_VERSION))).toEqual(['mcp.relative-bin', 'mcp.unpinned']);
  });

  it('reports plain-text credentials in the legacy auth.json without echoing them', () => {
    write(tmp, 'home/.gherkin-ai/auth.json', JSON.stringify({ provider: 'openai', apiKey: 'sk-secret-value' }));
    const [finding] = scanLegacyFiles(tmp, path.join(tmp, 'home'));
    expect(finding.id).toBe('legacy.auth-json-secret');
    expect(JSON.stringify(finding)).not.toContain('sk-secret-value');
  });

  it('deletes only stale files that are provably unedited', () => {
    write(tmp, 'out/old-untouched.ts', 'A');
    write(tmp, 'out/old-edited.ts', 'B edited');
    write(tmp, 'out/old-header-only.ts', '// Generated by gherkin-ai CLI v2.6.1');
    write(tmp, 'out/still-generated.ts', 'C');
    const opts = {
      outputDir: path.join(tmp, 'out'),
      generated: new Set(['still-generated.ts']),
      previousInventory: [
        { filePath: 'old-untouched.ts', checksum: sha256('A') },
        { filePath: 'old-edited.ts', checksum: sha256('B') },
        { filePath: 'still-generated.ts', checksum: sha256('C') },
        { filePath: 'already-gone.ts', checksum: sha256('D') }
      ],
      headerFiles: ['old-header-only.ts']
    };
    expect(findStaleFiles(opts)).toEqual({ removable: ['old-untouched.ts'], kept: ['old-edited.ts', 'old-header-only.ts'] });
    expect(findStaleFiles({ ...opts, prune: true }).removable).toEqual(['old-header-only.ts', 'old-untouched.ts']);
  });
});

describe('ghk upgrade --apply', () => {
  const cwd = process.cwd();
  const sh = (args: string[]) => execFileSync('git', args, { cwd: tmp, stdio: 'pipe' }).toString().trim();

  beforeEach(() => {
    write(tmp, 'gherkin-ai.config.json', JSON.stringify({
      projectName: 'shop',
      architecture: 'hexagonal',
      stack: { language: 'typescript', framework: 'express', orm: 'none', database: 'postgresql', validation: 'zod', auth: 'jwt', testing: 'jest' },
      rules: {},
      outputDir: './generated-specs'
    }, null, 2));
    write(tmp, 'features/checkout.feature', 'Feature: Checkout\n  Scenario: Pay\n    Given a cart\n    When the customer pays\n    Then the order is paid\n');
    // A 2.x generation: one file listed in the inventory (unchanged), one only carrying the header.
    const legacy = '/* Generated by gherkin-ai CLI v2.6.1 */\nexport const legacy = 1;\n';
    write(tmp, 'generated-specs/frontend/store/checkout.store.ts', legacy);
    write(tmp, 'generated-specs/legacy-notes.ts', '// Generated by gherkin-ai CLI v2.6.1\n');
    write(tmp, '.ghe/inventory.json', JSON.stringify({ version: '1.0', artifacts: [{ filePath: 'frontend/store/checkout.store.ts', type: 'other', checksum: sha256(legacy) }] }));
    write(tmp, '.gitignore', '.ghe/\n.gherkin-ai/\n');
    sh(['init', '-q', '-b', 'main']);
    sh(['config', 'user.email', 'dev@example.com']);
    sh(['config', 'user.name', 'Dev']);
    sh(['add', '-A']);
    sh(['commit', '-q', '-m', 'v2 project']);
    process.chdir(tmp);
  });
  afterEach(() => process.chdir(cwd));

  it('regenerates on a new branch, fixes the config and removes unedited stale files', async () => {
    const report = await handleUpgradeCommand({ apply: true, commit: true, yes: true });

    expect(report.from).toBe('2.6.1');
    expect(report.applied).toMatchObject({ branch: `ghk-upgrade-v${CLI_VERSION}`, baseBranch: 'main', configUpdated: true, regenerated: ['features/checkout.feature'] });
    expect(report.applied!.removed).toEqual(['frontend/store/checkout.store.ts']);
    expect(report.applied!.kept).toEqual(['legacy-notes.ts']);
    expect(report.applied!.commit).toBeTruthy();
    expect(report.findings.some(f => f.id === 'generated.regenerate')).toBe(false);

    expect(sh(['rev-parse', '--abbrev-ref', 'HEAD'])).toBe(`ghk-upgrade-v${CLI_VERSION}`);
    expect(sh(['status', '--porcelain'])).toBe('');
    expect(JSON.parse(fs.readFileSync('gherkin-ai.config.json', 'utf8')).$schema).toBe(CONFIG_SCHEMA_ID);
    expect(fs.existsSync('generated-specs/frontend/store/checkout.store.ts')).toBe(false);
    expect(fs.existsSync('generated-specs/src/app.ts')).toBe(true);
    // main is untouched
    expect(sh(['show', 'main:gherkin-ai.config.json'])).not.toContain('$schema');
  });

  it('--prune also deletes files that are only evidenced by the header or by git in the output directory', async () => {
    write(tmp, 'generated-specs/checkout.spec.ts', '// 2.x Playwright skeleton without a header\n');
    sh(['add', '-A']);
    sh(['commit', '-q', '-m', 'more 2.x output']);

    const kept = await handleUpgradeCommand({ apply: true, yes: true, branch: 'up-keep' });
    expect(kept.applied!.kept).toEqual(['checkout.spec.ts', 'legacy-notes.ts']);
    expect(kept.findings.find(f => f.id === 'generated.stale-kept')).toMatchObject({ severity: 'recommended', fix: 'manual' });

    sh(['checkout', '-q', '-f', 'main']);
    sh(['clean', '-qfd']);
    const pruned = await handleUpgradeCommand({ apply: true, yes: true, branch: 'up-prune', prune: true });
    expect(pruned.applied!.removed).toEqual(['checkout.spec.ts', 'frontend/store/checkout.store.ts', 'legacy-notes.ts']);
    expect(fs.existsSync('generated-specs/checkout.spec.ts')).toBe(false);
  });

  it('refuses a dirty working tree and an existing branch', async () => {
    write(tmp, 'features/checkout.feature', 'Feature: Changed\n');
    await expect(handleUpgradeCommand({ apply: true, yes: true })).rejects.toThrow(/uncommitted changes/);
    sh(['checkout', '-q', '--', '.']);
    sh(['branch', 'taken']);
    await expect(handleUpgradeCommand({ apply: true, yes: true, branch: 'taken' })).rejects.toThrow(/already exists/);
  });

  it('--check exits with the gate code while required changes are pending and changes nothing', async () => {
    await expect(handleUpgradeCommand({ check: true, yes: true })).rejects.toMatchObject({ exitCode: 4 });
    expect(sh(['rev-parse', '--abbrev-ref', 'HEAD'])).toBe('main');
    expect(sh(['status', '--porcelain'])).toBe('');
  });
});
