/* ==========================================================================
   gherkin-ai-cli - Shared Python project files (FastAPI & Django presets)
   ========================================================================== */

import { DomainModel } from '../kernel/domain-model';
import { PyFile } from '../kernel/python';

export const PY_DATABASE = `"""SQLAlchemy engine/session shared by every generated model (generated by gherkin-ai)."""
import os

from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./app.db")

engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    """FastAPI dependency: one session per request."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
`;

export const PY_EVENT_BUS = `"""Minimal in-process event bus used by sagas to dispatch commands (generated by gherkin-ai).

Replace or bridge it to your broker (RabbitMQ, Kafka, SQS), ideally through the transactional outbox.
"""
from collections import defaultdict
from typing import Any, Callable, Dict, List

Handler = Callable[[Dict[str, Any]], None]


class EventBus:
    def __init__(self) -> None:
        self._handlers: Dict[str, List[Handler]] = defaultdict(list)
        self.published: List[tuple] = []

    def subscribe(self, name: str, handler: Handler) -> None:
        self._handlers[name].append(handler)

    def publish(self, name: str, payload: Dict[str, Any]) -> None:
        self.published.append((name, payload))
        for handler in self._handlers.get(name, []):
            handler(payload)


event_bus = EventBus()
`;

export function pyEventBusTest(): PyFile {
  return {
    filename: 'tests/test_event_bus.py',
    content: `from app.infrastructure.event_bus import EventBus


def test_publish_delivers_to_subscribers_and_records_history():
    bus = EventBus()
    received = []
    bus.subscribe("Ping", received.append)
    bus.publish("Ping", {"n": 1})
    assert received == [{"n": 1}]
    assert bus.published == [("Ping", {"n": 1})]
`
  };
}

/** Moves the legacy pattern generators' files under the app package. */
export function underAppPackage(files: { filename: string; content: string }[]): PyFile[] {
  return files.map(f => ({ filename: `app/${f.filename}`, content: f.content }));
}

export function pyFeatureFile(m: DomainModel, featureFile?: string): string {
  return featureFile || `features/${m.kebab}.feature`;
}

export function renderPyproject(name: string, deps: string[], testDeps: string[], pytestExtra: string[] = []): string {
  const list = (xs: string[]) => xs.map(d => `    "${d}",`).join('\n');
  return `[project]
name = "${name}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
${list(deps)}
]

[project.optional-dependencies]
test = [
${list(testDeps)}
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"${pytestExtra.some(l => l.includes('DJANGO')) ? ', "config*"' : ''}]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
bdd_features_base_dir = "."
${pytestExtra.join('\n')}
`;
}
